import type { OsImage } from './image-types';

const GIB = 1024 ** 3;

/**
 * Каталог образов — публичные дистрибутивы (shipped/зеркала) + свои приватные
 * сборки. Размеры реальные (несжатый qcow2), в байтах. `Size` сам подберёт
 * единицу для вывода.
 */
const IMAGES: OsImage[] = [
  {
    id: 'img-ubuntu-2404',
    name: 'ubuntu-24.04-lts',
    family: 'ubuntu',
    os: 'Ubuntu',
    version: '24.04 LTS',
    arch: 'x86_64',
    sizeBytes: Math.round(2.6 * GIB),
    minDiskBytes: 8 * GIB,
    visibility: 'public',
    status: 'ready',
    createdAt: '2026-05-02T00:00:00Z',
    techSlug: 'ubuntu',
    description: 'Noble Numbat. LTS until 2029.',
  },
  {
    id: 'img-ubuntu-2204',
    name: 'ubuntu-22.04-lts',
    family: 'ubuntu',
    os: 'Ubuntu',
    version: '22.04 LTS',
    arch: 'x86_64',
    sizeBytes: Math.round(2.4 * GIB),
    minDiskBytes: 8 * GIB,
    visibility: 'public',
    status: 'ready',
    createdAt: '2026-02-14T00:00:00Z',
    techSlug: 'ubuntu',
    description: 'Jammy Jellyfish. LTS until 2027.',
  },
  {
    id: 'img-ubuntu-2404-arm',
    name: 'ubuntu-24.04-lts-arm64',
    family: 'ubuntu',
    os: 'Ubuntu',
    version: '24.04 LTS',
    arch: 'arm64',
    sizeBytes: Math.round(2.5 * GIB),
    minDiskBytes: 8 * GIB,
    visibility: 'public',
    status: 'ready',
    createdAt: '2026-05-02T00:00:00Z',
    techSlug: 'ubuntu',
    description: 'Noble Numbat for ARM nodes.',
  },
  {
    id: 'img-debian-12',
    name: 'debian-12-bookworm',
    family: 'debian',
    os: 'Debian',
    version: '12 (bookworm)',
    arch: 'x86_64',
    sizeBytes: Math.round(1.9 * GIB),
    minDiskBytes: 6 * GIB,
    visibility: 'public',
    status: 'ready',
    createdAt: '2026-03-20T00:00:00Z',
    techSlug: 'debian',
    description: 'Stable Debian, minimal cloud image.',
  },
  {
    id: 'img-rocky-9',
    name: 'rocky-9.4',
    family: 'rocky',
    os: 'Rocky Linux',
    version: '9.4',
    arch: 'x86_64',
    sizeBytes: Math.round(1.7 * GIB),
    minDiskBytes: 10 * GIB,
    visibility: 'public',
    status: 'ready',
    createdAt: '2026-04-10T00:00:00Z',
    techSlug: 'rocky',
    description: 'RHEL-compatible enterprise distribution.',
  },
  {
    id: 'img-alma-9',
    name: 'almalinux-9.4',
    family: 'almalinux',
    os: 'AlmaLinux',
    version: '9.4',
    arch: 'x86_64',
    sizeBytes: Math.round(1.6 * GIB),
    minDiskBytes: 10 * GIB,
    visibility: 'public',
    status: 'ready',
    createdAt: '2026-04-11T00:00:00Z',
    techSlug: 'almalinux',
    description: 'RHEL-compatible, community-driven.',
  },
  {
    id: 'img-app-base-v3',
    name: 'app-base-v3',
    family: 'custom',
    os: 'Custom build',
    version: 'Debian 12 + app',
    arch: 'x86_64',
    sizeBytes: Math.round(4.2 * GIB),
    minDiskBytes: 16 * GIB,
    visibility: 'private',
    status: 'ready',
    createdAt: '2026-07-05T09:30:00Z',
    description: 'Golden image: Debian 12 + application runtime and agents.',
  },
  {
    id: 'img-ci-runner',
    name: 'ci-runner',
    family: 'custom',
    os: 'Custom build',
    version: 'Ubuntu 24.04 + CI',
    arch: 'x86_64',
    sizeBytes: Math.round(3.1 * GIB),
    minDiskBytes: 20 * GIB,
    visibility: 'private',
    status: 'creating',
    createdAt: '2026-07-09T06:15:00Z',
    description: 'Ubuntu + toolchain for CI runners.',
  },
];

export function listImages(): OsImage[] {
  return IMAGES;
}
