/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteBrandingOrgMutationResponse, DeleteBrandingOrg404 } from "../types/DeleteBrandingOrg.ts";
import { http } from "msw";

export function deleteBrandingOrgHandlerResponse204(data?: DeleteBrandingOrgMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function deleteBrandingOrgHandlerResponse404(data: DeleteBrandingOrg404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function deleteBrandingOrgHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.delete(`/branding/org/:orgId`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}