/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: kubb 4.39.2 silently
// skipped /branding/theme in the MSW + faker pass. See the kz note in
// msw/getBrandingThemeHandler.ts.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { http } from "msw";

export function deleteBrandingThemeHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.delete(`/branding/theme`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}
