/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetBrandingThemeQueryResponse, GetBrandingTheme403, GetBrandingTheme404 } from "../types/GetBrandingTheme.ts";
import { http } from "msw";

export function getBrandingThemeHandlerResponse200(data: GetBrandingThemeQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function getBrandingThemeHandlerResponse403(data: GetBrandingTheme403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function getBrandingThemeHandlerResponse404(data: GetBrandingTheme404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function getBrandingThemeHandler(data?: GetBrandingThemeQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/branding/theme`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}