/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetBrandingOrgQueryResponse, GetBrandingOrg404 } from "../types/GetBrandingOrg.ts";
import { http } from "msw";

export function getBrandingOrgHandlerResponse200(data: GetBrandingOrgQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function getBrandingOrgHandlerResponse404(data: GetBrandingOrg404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function getBrandingOrgHandler(data?: GetBrandingOrgQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/branding/org/:orgId`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}