/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: kubb 4.39.2 silently
// skipped /branding/theme in the MSW + faker pass (the client + hook +
// type files were emitted, but the msw/ and fixtures/ files were not).
// This file restores parity so the dev:mock worker covers the
// marketplace-theme endpoints the FE actually hits. If a future regen
// starts emitting these again, delete this file and the kubb output
// will take over.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetBrandingThemeQueryResponse } from "../types/GetBrandingTheme.ts";
import { http } from "msw";

export function getBrandingThemeHandlerResponse200(data: GetBrandingThemeQueryResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function getBrandingThemeHandler(data?: GetBrandingThemeQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.get(`/branding/theme`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}
