export { cloneVSphereTemplateHandler, cloneVSphereTemplateHandlerResponse200, cloneVSphereTemplateHandlerResponse404, cloneVSphereTemplateHandlerResponse502, cloneVSphereTemplateHandlerResponse503, cloneVSphereTemplateHandlerResponse504 } from "./cloneVSphereTemplateHandler.ts";
export { deleteBrandingOrgHandler, deleteBrandingOrgHandlerResponse204, deleteBrandingOrgHandlerResponse404 } from "./deleteBrandingOrgHandler.ts";
export { deleteBrandingThemeHandler, deleteBrandingThemeHandlerResponse204, deleteBrandingThemeHandlerResponse403 } from "./deleteBrandingThemeHandler.ts";
export { deleteQuotaAssignmentHandler, deleteQuotaAssignmentHandlerResponse204, deleteQuotaAssignmentHandlerResponse404 } from "./deleteQuotaAssignmentHandler.ts";
export { deleteVmHandler, deleteVmHandlerResponse204, deleteVmHandlerResponse404 } from "./deleteVmHandler.ts";
export { getAuditHandler, getAuditHandlerResponse200 } from "./getAuditHandler.ts";
export { getBrandingBootHandler, getBrandingBootHandlerResponse200 } from "./getBrandingBootHandler.ts";
export { getBrandingGlobalHandler, getBrandingGlobalHandlerResponse200 } from "./getBrandingGlobalHandler.ts";
export { getBrandingOrgHandler, getBrandingOrgHandlerResponse200, getBrandingOrgHandlerResponse404 } from "./getBrandingOrgHandler.ts";
export { getBrandingThemeHandler, getBrandingThemeHandlerResponse200, getBrandingThemeHandlerResponse403, getBrandingThemeHandlerResponse404 } from "./getBrandingThemeHandler.ts";
export { getOidcAuthorizeHandler } from "./getOidcAuthorizeHandler.ts";
export { getOidcCallbackHandler } from "./getOidcCallbackHandler.ts";
export { getOrgAuthProviderHandler, getOrgAuthProviderHandlerResponse200, getOrgAuthProviderHandlerResponse404 } from "./getOrgAuthProviderHandler.ts";
export { getQuotaDefinitionsHandler, getQuotaDefinitionsHandlerResponse200 } from "./getQuotaDefinitionsHandler.ts";
export { getVSphereInventoryHandler, getVSphereInventoryHandlerResponse200, getVSphereInventoryHandlerResponse503 } from "./getVSphereInventoryHandler.ts";
export { getVmHandler, getVmHandlerResponse200, getVmHandlerResponse404 } from "./getVmHandler.ts";
export { listEffectiveQuotasHandler, listEffectiveQuotasHandlerResponse200 } from "./listEffectiveQuotasHandler.ts";
export { listQuotaAssignmentsHandler, listQuotaAssignmentsHandlerResponse200 } from "./listQuotaAssignmentsHandler.ts";
export { listQuotaUsageHandler, listQuotaUsageHandlerResponse200 } from "./listQuotaUsageHandler.ts";
export { listVmsHandler, listVmsHandlerResponse200 } from "./listVmsHandler.ts";
export { nodeCommandPollHandler, nodeCommandPollHandlerResponse200 } from "./nodeCommandPollHandler.ts";
export { nodeCommandResultHandler, nodeCommandResultHandlerResponse200, nodeCommandResultHandlerResponse400 } from "./nodeCommandResultHandler.ts";
export { nodeHeartbeatHandler, nodeHeartbeatHandlerResponse200, nodeHeartbeatHandlerResponse400 } from "./nodeHeartbeatHandler.ts";
export { nodeJoinHandler, nodeJoinHandlerResponse201, nodeJoinHandlerResponse400 } from "./nodeJoinHandler.ts";
export { postAuthLoginHandler, postAuthLoginHandlerResponse200, postAuthLoginHandlerResponse401, postAuthLoginHandlerResponse422 } from "./postAuthLoginHandler.ts";
export { postOidcLogoutHandler, postOidcLogoutHandlerResponse204 } from "./postOidcLogoutHandler.ts";
export { provisionVmHandler, provisionVmHandlerResponse201, provisionVmHandlerResponse422 } from "./provisionVmHandler.ts";
export { refreshVSphereInventoryHandler, refreshVSphereInventoryHandlerResponse202, refreshVSphereInventoryHandlerResponse502, refreshVSphereInventoryHandlerResponse503 } from "./refreshVSphereInventoryHandler.ts";
export { startVmHandler, startVmHandlerResponse200 } from "./startVmHandler.ts";
export { stopVmHandler, stopVmHandlerResponse200 } from "./stopVmHandler.ts";
export { testOrgAuthProviderHandler, testOrgAuthProviderHandlerResponse200, testOrgAuthProviderHandlerResponse404 } from "./testOrgAuthProviderHandler.ts";
export { updateBrandingGlobalHandler, updateBrandingGlobalHandlerResponse200, updateBrandingGlobalHandlerResponse400 } from "./updateBrandingGlobalHandler.ts";
export { updateBrandingOrgHandler, updateBrandingOrgHandlerResponse200, updateBrandingOrgHandlerResponse400, updateBrandingOrgHandlerResponse404 } from "./updateBrandingOrgHandler.ts";
export { updateBrandingThemeHandler, updateBrandingThemeHandlerResponse200, updateBrandingThemeHandlerResponse400, updateBrandingThemeHandlerResponse403, updateBrandingThemeHandlerResponse404 } from "./updateBrandingThemeHandler.ts";
export { updateOrgAuthProviderHandler, updateOrgAuthProviderHandlerResponse200, updateOrgAuthProviderHandlerResponse400, updateOrgAuthProviderHandlerResponse404 } from "./updateOrgAuthProviderHandler.ts";
export { upsertQuotaAssignmentHandler, upsertQuotaAssignmentHandlerResponse200, upsertQuotaAssignmentHandlerResponse400 } from "./upsertQuotaAssignmentHandler.ts";