/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { ListVmsQueryResponse } from "../types/ListVms.ts";
import { http } from "msw";

 export function listVmsHandler(data?: ListVmsQueryResponse) {
    return http.get("*/vms", function handler(info) {
        return new Response(JSON.stringify(data), {
            headers: {
                "Content-Type": "application/json",
            },
        });
    });
}