/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeCommandResultMutationResponse, NodeCommandResult400 } from "../types/NodeCommandResult.ts";
import { http } from "msw";

export function nodeCommandResultHandlerResponse200(data?: NodeCommandResultMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
        
      })
}

export function nodeCommandResultHandlerResponse400(data: NodeCommandResult400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function nodeCommandResultHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/nodes/:nodeId/commands/:commandId/result`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
        
      })
    })
}