/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeJoinMutationResponse, NodeJoin400 } from "../types/NodeJoin.ts";
import { http } from "msw";

export function nodeJoinHandlerResponse201(data: NodeJoinMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function nodeJoinHandlerResponse400(data: NodeJoin400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function nodeJoinHandler(data?: NodeJoinMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/nodes/join`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}