/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostOidcLogoutMutationResponse } from "../types/PostOidcLogout.ts";
import { http } from "msw";

export function postOidcLogoutHandlerResponse204(data?: PostOidcLogoutMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
}

export function postOidcLogoutHandler(data?: string | number | boolean | null | object | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/auth/oidc/logout`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 204,
        
      })
    })
}