/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProvisionVmMutationResponse, ProvisionVm422 } from "../types/ProvisionVm.ts";
import { http } from "msw";

export function provisionVmHandlerResponse201(data: ProvisionVmMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function provisionVmHandlerResponse422(data: ProvisionVm422) {

      return new Response(JSON.stringify(data), {
        status: 422,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function provisionVmHandler(data?: ProvisionVmMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/vms`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 201,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}