/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { StartVmMutationResponse } from "../types/StartVm.ts";
import { http } from "msw";

 export function startVmHandler(data?: StartVmMutationResponse) {
    return http.post("*/vms/:vmId/start", function handler(info) {
        return new Response(JSON.stringify(data), {
            headers: {
                "Content-Type": "application/json",
            },
        });
    });
}