/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StopVmMutationResponse } from "../types/StopVm.ts";
import { http } from "msw";

export function stopVmHandlerResponse200(data: StopVmMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function stopVmHandler(data?: StopVmMutationResponse | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.post(`/vms/:vmId/stop`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}