/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { StopVmMutationResponse } from "../types/StopVm.ts";
import { http } from "msw";

 export function stopVmHandler(data?: StopVmMutationResponse) {
    return http.post("*/vms/:vmId/stop", function handler(info) {
        return new Response(JSON.stringify(data), {
            headers: {
                "Content-Type": "application/json",
            },
        });
    });
}