/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandingThemeMutationResponse, UpdateBrandingTheme400, UpdateBrandingTheme403, UpdateBrandingTheme404 } from "../types/UpdateBrandingTheme.ts";
import { http } from "msw";

export function updateBrandingThemeHandlerResponse200(data: UpdateBrandingThemeMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function updateBrandingThemeHandlerResponse400(data: UpdateBrandingTheme400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function updateBrandingThemeHandlerResponse403(data: UpdateBrandingTheme403) {

      return new Response(JSON.stringify(data), {
        status: 403,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function updateBrandingThemeHandlerResponse404(data: UpdateBrandingTheme404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function updateBrandingThemeHandler(data?: UpdateBrandingThemeMutationResponse | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.put(`/branding/theme`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}