/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateOrgAuthProviderMutationResponse, UpdateOrgAuthProvider400, UpdateOrgAuthProvider404 } from "../types/UpdateOrgAuthProvider.ts";
import { http } from "msw";

export function updateOrgAuthProviderHandlerResponse200(data: UpdateOrgAuthProviderMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function updateOrgAuthProviderHandlerResponse400(data: UpdateOrgAuthProvider400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function updateOrgAuthProviderHandlerResponse404(data: UpdateOrgAuthProvider404) {

      return new Response(JSON.stringify(data), {
        status: 404,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function updateOrgAuthProviderHandler(data?: UpdateOrgAuthProviderMutationResponse | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.put(`/iam/orgs/:orgId/auth-provider`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}