/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandingGlobalMutationResponse, UpdateBrandingGlobal400 } from "../types/UpdateBrandingGlobal.ts";
import { http } from "msw";

export function updateBrandingGlobalHandlerResponse200(data: UpdateBrandingGlobalMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function updateBrandingGlobalHandlerResponse400(data: UpdateBrandingGlobal400) {

      return new Response(JSON.stringify(data), {
        status: 400,
          headers: {
          'Content-Type': 'application/problem+json'
        },
      })
}

export function updateBrandingGlobalHandler(data?: UpdateBrandingGlobalMutationResponse | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.put(`/branding/global`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}