/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: kubb 4.39.2 silently
// skipped /branding/theme in the MSW + faker pass. See the kz note in
// msw/getBrandingThemeHandler.ts.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandingThemeMutationResponse } from "../types/UpdateBrandingTheme.ts";
import { http } from "msw";

export function updateBrandingThemeHandlerResponse200(data: UpdateBrandingThemeMutationResponse) {

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
}

export function updateBrandingThemeHandler(data?: UpdateBrandingThemeMutationResponse | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Response | Promise<Response>)) {
  return http.put(`/branding/theme`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}
