/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostAuthLoginUser } from "./PostAuthLoginUser.ts";

/**
 * @description Successful sign-in. Returns the bearer access token (RS256 JWT the console stores as `Authorization: Bearer`), the opaque refresh token, the access-token lifetime in seconds, and the authenticated user record. The FE computes `expiresAt = Date.now() + expiresIn * 1000` and persists the triple to localStorage.\n
*/
export type AuthLoginResponse = {
    /**
     * @description RS256 JWT. Sent as `Authorization: Bearer ` followed by this token on subsequent requests.\n
     * @type string
    */
    accessToken: string;
    /**
     * @description Opaque refresh token. Rotated on every successful refresh.
     * @type string
    */
    refreshToken: string;
    /**
     * @description Access-token lifetime in seconds.
     * @minLength 1
     * @type integer
    */
    expiresIn: number;
    /**
     * @description The authenticated user record — used to seed the FE user cache after sign-in.
     * @type object
    */
    user: PostAuthLoginUser;
};