/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Resolved branding for the caller — merges global row + per-org override. Written server-side into window.__PLEXOR_CONFIG__ before first paint.
*/
export type BrandingBootConfig = {
    /**
     * @type string
    */
    brandName: string;
    /**
     * @type string, uri
    */
    brandLogoUrl: string | null;
    /**
     * @type string, uri
    */
    brandFaviconUrl: string | null;
    /**
     * @type string
    */
    defaultPresetId: string;
    /**
     * @type string
    */
    customAccent: string | null;
};