/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";
import type { VSphereCloneRequestBody } from "./VSphereCloneRequestBody.ts";
import type { VSphereCloneResponse } from "./VSphereCloneResponse.ts";

/**
 * @description Clone succeeded.
*/
export type CloneVSphereTemplate200 = VSphereCloneResponse;

/**
 * @description RFC 7807 error.
*/
export type CloneVSphereTemplate404 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type CloneVSphereTemplate502 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type CloneVSphereTemplate503 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type CloneVSphereTemplate504 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type CloneVSphereTemplateError = ProblemDetails;

export type CloneVSphereTemplateMutationRequest = VSphereCloneRequestBody;

export type CloneVSphereTemplateMutationResponse = CloneVSphereTemplate200;

export type CloneVSphereTemplateMutation = {
    Response: CloneVSphereTemplate200;
    Request: CloneVSphereTemplateMutationRequest;
    Errors: CloneVSphereTemplate404 | CloneVSphereTemplate502 | CloneVSphereTemplate503 | CloneVSphereTemplate504;
};