/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.


/**
 * @description Payload from the create-VM wizard.
*/
export type CreateVmRequest = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    project: string;
    /**
     * @type string, uuid
    */
    vpcId?: string | null;
    /**
     * @type string, uuid
    */
    subnetId: string;
    /**
     * @type string
    */
    machineType: string;
    /**
     * @type integer | undefined
    */
    vcpu?: number;
    /**
     * @type integer | undefined
    */
    ramGb?: number;
    /**
     * @type integer
    */
    diskGb: number;
    /**
     * @type string
    */
    image: string;
    /**
     * @default true
     * @type boolean | undefined
    */
    diskEncrypted?: boolean;
    /**
     * @type array | undefined
    */
    securityGroups?: string[];
    /**
     * @type string
    */
    label?: string | null;
    /**
     * @type string
    */
    description?: string | null;
    /**
     * @type array | undefined
    */
    tags?: string[];
};