/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { ProblemDetails } from "./ProblemDetails.ts";

 export type DeleteVmPathParams = {
    /**
     * @type string, uuid
    */
    vmId: string;
};

 /**
 * @description Deleted.
*/
export type DeleteVm204 = any;

 /**
 * @description RFC 7807 error.
*/
export type DeleteVm404 = ProblemDetails;

 /**
 * @description RFC 7807 error.
*/
export type DeleteVmError = ProblemDetails;

 export type DeleteVmMutationResponse = DeleteVm204;

 export type DeleteVmMutation = {
    Response: DeleteVm204;
    PathParams: DeleteVmPathParams;
    Errors: DeleteVm404;
};