/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";

/**
 * @description Reset (or already absent).
*/
export type DeleteBrandingTheme204 = any;

/**
 * @description RFC 7807 error.
*/
export type DeleteBrandingTheme403 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type DeleteBrandingThemeError = ProblemDetails;

export type DeleteBrandingThemeMutationResponse = DeleteBrandingTheme204;

export type DeleteBrandingThemeMutation = {
    Response: DeleteBrandingTheme204;
    Errors: DeleteBrandingTheme403;
};