/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const effectiveQuotaEntryScopeEnum = {
    org: "org",
    team: "team",
    folder: "folder"
} as const;

export type EffectiveQuotaEntryScopeEnumKey = (typeof effectiveQuotaEntryScopeEnum)[keyof typeof effectiveQuotaEntryScopeEnum];

/**
 * @description Effective rollup of a definition for a scope (what ceiling applies here, after merging).
*/
export type EffectiveQuotaEntry = {
    /**
     * @type string, uuid
    */
    definitionId: string;
    /**
     * @type string
    */
    metric: string;
    /**
     * @type string
    */
    scope: EffectiveQuotaEntryScopeEnumKey;
    /**
     * @type string, uuid
    */
    scopeId: string;
    /**
     * @minLength 0
     * @type integer, int64
    */
    effectiveCeiling: number;
    /**
     * @description The chain of assignment ids that contributed to the effective ceiling (folder → team → org → default).
     * @type array
    */
    appliedAssignmentIds: string[];
};