/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.


/**
 * @description OK
*/
export type Get200 = any;

 export type GetQueryResponse = Get200;

 export type GetQuery = {
    Response: Get200;
    Errors: any;
};