/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";
import type { ThemeInstallationResponse } from "./ThemeInstallationResponse.ts";

/**
 * @description The active marketplace installation.
*/
export type GetBrandingTheme200 = ThemeInstallationResponse;

/**
 * @description RFC 7807 error.
*/
export type GetBrandingTheme403 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type GetBrandingTheme404 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type GetBrandingThemeError = ProblemDetails;

export type GetBrandingThemeQueryResponse = GetBrandingTheme200;

export type GetBrandingThemeQuery = {
    Response: GetBrandingTheme200;
    Errors: GetBrandingTheme403 | GetBrandingTheme404;
};