/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BrandingBootConfig } from "./BrandingBootConfig.ts";
import type { ProblemDetails } from "./ProblemDetails.ts";

/**
 * @description Resolved branding for the caller.
*/
export type GetBrandingBoot200 = BrandingBootConfig;

/**
 * @description RFC 7807 error.
*/
export type GetBrandingBootError = ProblemDetails;

export type GetBrandingBootQueryResponse = GetBrandingBoot200;

export type GetBrandingBootQuery = {
    Response: GetBrandingBoot200;
    Errors: any;
};