/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";
import type { VSphereInventoryResponse } from "./VSphereInventoryResponse.ts";

/**
 * @description The latest cached inventory snapshot.
*/
export type GetVSphereInventory200 = VSphereInventoryResponse;

/**
 * @description RFC 7807 error.
*/
export type GetVSphereInventory503 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type GetVSphereInventoryError = ProblemDetails;

export type GetVSphereInventoryQueryResponse = GetVSphereInventory200;

export type GetVSphereInventoryQuery = {
    Response: GetVSphereInventory200;
    Errors: GetVSphereInventory503;
};