/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Operator-global branding row (Plexor.Modules.Branding).
*/
export type GlobalThemeConfigResponse = {
    /**
     * @type string
    */
    brandName: string;
    /**
     * @description URL or web-root-relative path. Null = default SVG mark.
     * @type string, uri
    */
    brandLogoUrl: string | null;
    /**
     * @description URL or web-root-relative path. Null = default favicon.
     * @type string, uri
    */
    brandFaviconUrl: string | null;
    /**
     * @type string
    */
    defaultPresetId: string;
    /**
     * @description OKLCH color. Null = preset default.
     * @type string
    */
    customAccent: string | null;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};