/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EffectiveQuotaEntry } from "./EffectiveQuotaEntry.ts";
import type { ProblemDetails } from "./ProblemDetails.ts";

export const listEffectiveQuotasQueryParamsScopeEnum = {
    org: "org",
    team: "team",
    folder: "folder"
} as const;

export type ListEffectiveQuotasQueryParamsScopeEnumKey = (typeof listEffectiveQuotasQueryParamsScopeEnum)[keyof typeof listEffectiveQuotasQueryParamsScopeEnum];

export type ListEffectiveQuotasQueryParams = {
    /**
     * @type string | undefined
    */
    scope?: ListEffectiveQuotasQueryParamsScopeEnumKey;
    /**
     * @type string | undefined, uuid
    */
    id?: string;
};

/**
 * @description Effective rollup rows.
*/
export type ListEffectiveQuotas200 = EffectiveQuotaEntry[];

/**
 * @description RFC 7807 error.
*/
export type ListEffectiveQuotasError = ProblemDetails;

export type ListEffectiveQuotasQueryResponse = ListEffectiveQuotas200;

export type ListEffectiveQuotasQuery = {
    Response: ListEffectiveQuotas200;
    QueryParams: ListEffectiveQuotasQueryParams;
    Errors: any;
};