/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";
import type { QuotaUsageEntry } from "./QuotaUsageEntry.ts";

export const listQuotaUsageQueryParamsScopeEnum = {
    org: "org",
    team: "team",
    folder: "folder"
} as const;

export type ListQuotaUsageQueryParamsScopeEnumKey = (typeof listQuotaUsageQueryParamsScopeEnum)[keyof typeof listQuotaUsageQueryParamsScopeEnum];

export type ListQuotaUsageQueryParams = {
    /**
     * @type string | undefined
    */
    scope?: ListQuotaUsageQueryParamsScopeEnumKey;
    /**
     * @type string | undefined, uuid
    */
    id?: string;
};

/**
 * @description Per-definition usage rows.
*/
export type ListQuotaUsage200 = QuotaUsageEntry[];

/**
 * @description RFC 7807 error.
*/
export type ListQuotaUsageError = ProblemDetails;

export type ListQuotaUsageQueryResponse = ListQuotaUsage200;

export type ListQuotaUsageQuery = {
    Response: ListQuotaUsage200;
    QueryParams: ListQuotaUsageQueryParams;
    Errors: any;
};