/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeHardware } from "./NodeHardware.ts";

/**
 * @description First message the agent sends. The join token is not yet verified.
*/
export type NodeJoinRequest = {
    /**
     * @minLength 1
     * @type string
    */
    joinToken: string;
    /**
     * @description Hardware snapshot reported by the agent on join and on every heartbeat.
     * @type object
    */
    hardware: NodeHardware;
};