/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const nodeCommandEnvelopeTypeEnum = {
    "workload.create": "workload.create",
    "workload.start": "workload.start",
    "workload.stop": "workload.stop",
    "workload.delete": "workload.delete"
} as const;

export type NodeCommandEnvelopeTypeEnumKey = (typeof nodeCommandEnvelopeTypeEnum)[keyof typeof nodeCommandEnvelopeTypeEnum];

/**
 * @description One command targeted at a node, dequeued by /commands/poll.
*/
export type NodeCommandEnvelope = {
    /**
     * @type string, uuid
    */
    commandId: string;
    /**
     * @type string, uuid
    */
    nodeId: string;
    /**
     * @type string
    */
    type: NodeCommandEnvelopeTypeEnumKey;
    /**
     * @description Kind-specific JSON payload
     * @type string
    */
    payloadJson: string;
    /**
     * @type string, date-time
    */
    issuedAt: string;
};