/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeCommandEnvelope } from "./NodeCommandEnvelope.ts";

/**
 * @description Long-poll output. Empty array + current cursor means \'no new commands\'.
*/
export type NodeCommandPollResponse = {
    /**
     * @type array
    */
    commands: NodeCommandEnvelope[];
    /**
     * @type integer, int64
    */
    nextCursor: number;
};