/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Hardware snapshot reported by the agent on join and on every heartbeat.
*/
export type NodeHardware = {
    /**
     * @minLength 1
     * @type integer
    */
    cpuCores: number;
    /**
     * @minLength 1
     * @type integer, int64
    */
    ramBytes: number;
    /**
     * @minLength 1
     * @type integer, int64
    */
    diskBytes: number;
    /**
     * @minLength 1
     * @type string
    */
    hostname: string;
    /**
     * @type string
    */
    kernelVersion: string;
};