/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Result of POST /iam/orgs/{orgId}/auth-provider/test. The test never persists side effects.
*/
export type OrgAuthProviderTestResult = {
    /**
     * @type boolean
    */
    ok: boolean;
    /**
     * @description Human-readable diagnostic. For OIDC: the discovery + token-exchange result. For LDAP: the bind result.
     * @type string
    */
    message: string;
    /**
     * @description Round-trip latency in milliseconds. Null when the test failed before a request was issued.
     * @minLength 0
     * @type integer
    */
    latencyMs?: number | null;
    /**
     * @description Provider-specific diagnostics (discovery URL, JWKS URL, bind subject, ...). Free-form.
     * @type object
    */
    details?: {
        [key: string]: any;
    } | null;
};