/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Per-org override row. Null fields inherit the operator-global default.
*/
export type OrgBrandingConfigResponse = {
    /**
     * @type string, uuid
    */
    orgId: string;
    /**
     * @description Per-org theme preset override. Null = inherit.
     * @type string
    */
    presetId: string | null;
    /**
     * @description OKLCH color. Null = inherit.
     * @type string
    */
    customAccent: string | null;
    /**
     * @description Per-org brand name. Null = inherit.
     * @type string
    */
    brandName: string | null;
    /**
     * @type string, uri
    */
    brandLogoUrl: string | null;
    /**
     * @type string, uri
    */
    brandFaviconUrl: string | null;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};