/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Local-credentials sign-in payload (sigill module). The FE trims + lowercases the email before sending so the backend can compare against the canonical address.
*/
export type PostAuthLoginRequest = {
    /**
     * @description Work email. The local-part is case-insensitive; the backend normalises to lowercase on persist.
     * @maxLength 254
     * @type string, email
    */
    email: string;
    /**
     * @description Plaintext password. TLS-only on the wire; never logged.
     * @minLength 1
     * @maxLength 128
     * @type string, password
    */
    password: string;
};