/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";

/**
 * @description Signed out.
*/
export type PostOidcLogout204 = any;

/**
 * @description RFC 7807 error.
*/
export type PostOidcLogoutError = ProblemDetails;

export type PostOidcLogoutMutationResponse = PostOidcLogout204;

export type PostOidcLogoutMutation = {
    Response: PostOidcLogout204;
    Errors: any;
};