/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description The authenticated user record — used to seed the FE user cache after sign-in.
*/
export type PostAuthLoginUser = {
    /**
     * @description Stable user id (sigill.users.id).
     * @type string, uuid
    */
    id: string;
    /**
     * @maxLength 254
     * @type string, email
    */
    email: string;
    /**
     * @maxLength 200
     * @type string
    */
    displayName: string;
    /**
     * @description Org-scoped role names (e.g. `admin`, `editor`, `viewer`). Empty in MVP; expanded in Phase 2 with team-scoped roles.
     * @type array
    */
    roles: string[];
};