/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthLoginResponse } from "./AuthLoginResponse.ts";
import type { PostAuthLoginRequest } from "./PostAuthLoginRequest.ts";
import type { ProblemDetails } from "./ProblemDetails.ts";

/**
 * @description Signed in. The `expiresIn` value is the access-token lifetime in seconds; the FE uses it to compute the absolute `expiresAt` (now + expiresIn * 1000).\n
*/
export type PostAuthLogin200 = AuthLoginResponse;

/**
 * @description RFC 7807 error.
*/
export type PostAuthLogin401 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type PostAuthLogin422 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type PostAuthLoginError = ProblemDetails;

export type PostAuthLoginMutationRequest = PostAuthLoginRequest;

export type PostAuthLoginMutationResponse = PostAuthLogin200;

export type PostAuthLoginMutation = {
    Response: PostAuthLogin200;
    Request: PostAuthLoginMutationRequest;
    Errors: PostAuthLogin401 | PostAuthLogin422;
};