/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: kubb 4.39.2 silently
// skipped /auth/login in the MSW + faker pass — the endpoint is documented
// in Phase 4.6 (sigil: local credentials login), but the FE needed it before
// kubb caught up. This file restores parity so the dev:mock worker covers
// the login endpoint the console FE actually hits. If a future regen
// starts emitting these, delete this file and the kubb output will take
// over.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";

export type PostAuthLogin200 = {
    /**
     * @description JWT (RS256) the console stores and sends as `Authorization: Bearer`.
     * @type string
    */
    accessToken: string;
    /**
     * @description Opaque refresh token (rotated on every refresh).
     * @type string
    */
    refreshToken: string;
    /**
     * @description Access-token lifetime in seconds.
     * @type integer
    */
    expiresIn: number;
    /**
     * @description The authenticated user — used to seed the FE user cache.
     * @type object
    */
    user: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        email: string;
        /**
         * @type string
        */
        displayName: string;
        /**
         * @type array
        */
        roles: Array<string>;
    };
};

/**
 * @description RFC 7807 error.
 */
export type PostAuthLogin401 = ProblemDetails;

/**
 * @description RFC 7807 error.
 */
export type PostAuthLoginError = ProblemDetails;

export type PostAuthLoginMutationRequest = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    password: string;
};

export type PostAuthLoginMutationResponse = PostAuthLogin200;

export type PostAuthLoginMutation = {
    Response: PostAuthLogin200;
    Request: PostAuthLoginMutationRequest;
    Errors: PostAuthLogin401 | PostAuthLoginError;
};
