/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description RFC 7807 problem details.
*/
export type ProblemDetails = {
    /**
     * @type string | undefined
    */
    type?: string;
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type integer | undefined
    */
    status?: number;
    /**
     * @type string | undefined
    */
    detail?: string;
    /**
     * @type string
    */
    instance?: string | null;
};