/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateVmRequest } from "./CreateVmRequest.ts";
import type { ProblemDetails } from "./ProblemDetails.ts";
import type { VmDetail } from "./VmDetail.ts";

/**
 * @description VM accepted for provisioning.
*/
export type ProvisionVm201 = VmDetail;

/**
 * @description RFC 7807 error.
*/
export type ProvisionVm422 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type ProvisionVmError = ProblemDetails;

export type ProvisionVmMutationRequest = CreateVmRequest;

export type ProvisionVmMutationResponse = ProvisionVm201;

export type ProvisionVmMutation = {
    Response: ProvisionVm201;
    Request: ProvisionVmMutationRequest;
    Errors: ProvisionVm422;
};