/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Live usage for one (definition, scope) pair.
*/
export type QuotaUsageEntry = {
    /**
     * @type string, uuid
    */
    definitionId: string;
    /**
     * @type string
    */
    metric: string;
    /**
     * @minLength 0
     * @type integer, int64
    */
    used: number;
    /**
     * @description Effective ceiling after merging parent overrides.
     * @minLength 0
     * @type integer, int64
    */
    limit: number;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};