/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description A registered quota definition (metric + unit + platform default ceiling).
*/
export type QuotaDefinitionSummary = {
    /**
     * @type string, uuid
    */
    id: string;
    /**
     * @description Stable identifier (e.g. `compute.vcpu`, `memory.ramGb`).
     * @type string
    */
    key: string;
    /**
     * @type string
    */
    displayName: string;
    /**
     * @description The field on the resource this quota measures (vCPUs, GB of RAM, ...).
     * @type string
    */
    metric: string;
    /**
     * @description Display unit (count, GB, GiB-hours, ...).
     * @type string
    */
    unit: string;
    /**
     * @description Platform default ceiling — applied when no assignment overrides it.
     * @minLength 0
     * @type integer, int64
    */
    defaultCeiling: number;
};