/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";
import type { VSphereInventoryRefreshResponse } from "./VSphereInventoryRefreshResponse.ts";

/**
 * @description Refresh succeeded — the new snapshot id is in the body.
*/
export type RefreshVSphereInventory202 = VSphereInventoryRefreshResponse;

/**
 * @description RFC 7807 error.
*/
export type RefreshVSphereInventory502 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type RefreshVSphereInventory503 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type RefreshVSphereInventoryError = ProblemDetails;

export type RefreshVSphereInventoryMutationResponse = RefreshVSphereInventory202;

export type RefreshVSphereInventoryMutation = {
    Response: RefreshVSphereInventory202;
    Errors: RefreshVSphereInventory502 | RefreshVSphereInventory503;
};