/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { ProblemDetails } from "./ProblemDetails.ts";
import type { VmDetail } from "./VmDetail.ts";

 export type StartVmPathParams = {
    /**
     * @type string, uuid
    */
    vmId: string;
};

 /**
 * @description Start requested.
*/
export type StartVm200 = VmDetail;

 /**
 * @description RFC 7807 error.
*/
export type StartVmError = ProblemDetails;

 export type StartVmMutationResponse = StartVm200;

 export type StartVmMutation = {
    Response: StartVm200;
    PathParams: StartVmPathParams;
    Errors: any;
};