/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { ProblemDetails } from "./ProblemDetails.ts";
import type { VmDetail } from "./VmDetail.ts";

 export type StopVmPathParams = {
    /**
     * @type string, uuid
    */
    vmId: string;
};

 /**
 * @description Stop requested.
*/
export type StopVm200 = VmDetail;

 /**
 * @description RFC 7807 error.
*/
export type StopVmError = ProblemDetails;

 export type StopVmMutationResponse = StopVm200;

 export type StopVmMutation = {
    Response: StopVm200;
    PathParams: StopVmPathParams;
    Errors: any;
};