/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";
import type { ThemeInstallationResponse } from "./ThemeInstallationResponse.ts";
import type { UpsertThemeInstallationRequest } from "./UpsertThemeInstallationRequest.ts";

/**
 * @description The upserted installation row.
*/
export type UpdateBrandingTheme200 = ThemeInstallationResponse;

/**
 * @description RFC 7807 error.
*/
export type UpdateBrandingTheme400 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type UpdateBrandingTheme403 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type UpdateBrandingTheme404 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type UpdateBrandingThemeError = ProblemDetails;

export type UpdateBrandingThemeMutationRequest = UpsertThemeInstallationRequest;

export type UpdateBrandingThemeMutationResponse = UpdateBrandingTheme200;

export type UpdateBrandingThemeMutation = {
    Response: UpdateBrandingTheme200;
    Request: UpdateBrandingThemeMutationRequest;
    Errors: UpdateBrandingTheme400 | UpdateBrandingTheme403 | UpdateBrandingTheme404;
};