/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GlobalThemeConfigResponse } from "./GlobalThemeConfigResponse.ts";
import type { ProblemDetails } from "./ProblemDetails.ts";
import type { UpsertGlobalThemeConfigRequest } from "./UpsertGlobalThemeConfigRequest.ts";

/**
 * @description The upserted global row.
*/
export type UpdateBrandingGlobal200 = GlobalThemeConfigResponse;

/**
 * @description RFC 7807 error.
*/
export type UpdateBrandingGlobal400 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type UpdateBrandingGlobalError = ProblemDetails;

export type UpdateBrandingGlobalMutationRequest = UpsertGlobalThemeConfigRequest;

export type UpdateBrandingGlobalMutationResponse = UpdateBrandingGlobal200;

export type UpdateBrandingGlobalMutation = {
    Response: UpdateBrandingGlobal200;
    Request: UpdateBrandingGlobalMutationRequest;
    Errors: UpdateBrandingGlobal400;
};