/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Wire shape for PUT /branding/org/{orgId}. Null fields mean \"inherit the operator global default\".
*/
export type UpsertOrgBrandingRequest = {
    /**
     * @type string
    */
    presetId?: string | null;
    /**
     * @type string
    */
    customAccent?: string | null;
    /**
     * @maxLength 128
     * @type string
    */
    brandName?: string | null;
    /**
     * @type string, uri
    */
    brandLogoUrl?: string | null;
    /**
     * @type string, uri
    */
    brandFaviconUrl?: string | null;
};