/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const upsertOrgAuthProviderRequestProviderEnum = {
    local: "local",
    oidc: "oidc",
    ldap: "ldap"
} as const;

export type UpsertOrgAuthProviderRequestProviderEnumKey = (typeof upsertOrgAuthProviderRequestProviderEnum)[keyof typeof upsertOrgAuthProviderRequestProviderEnum];

/**
 * @description Wire shape for PUT /iam/orgs/{orgId}/auth-provider. Omit a sensitive field to keep the stored value unchanged (write-only secrets).
*/
export type UpsertOrgAuthProviderRequest = {
    /**
     * @type string
    */
    provider: UpsertOrgAuthProviderRequestProviderEnumKey;
    /**
     * @type object
    */
    oidc?: {
        /**
         * @type string | undefined, uri
        */
        issuer?: string;
        /**
         * @minLength 1
         * @type string | undefined
        */
        clientId?: string;
        /**
         * @description Write-only. Omit (or send the sentinel `***`) to keep the existing value.
         * @type string
        */
        clientSecret?: string | null;
        /**
         * @type array | undefined
        */
        scopes?: string[];
        /**
         * @type string | undefined, uri
        */
        redirectUri?: string;
        /**
         * @type object | undefined
        */
        claimMappings?: {
            [key: string]: string;
        };
    } | null;
    /**
     * @type object
    */
    ldap?: {
        /**
         * @type string | undefined
        */
        server?: string;
        /**
         * @type string | undefined
        */
        baseDn?: string;
        /**
         * @type string | undefined
        */
        bindDn?: string;
        /**
         * @description Write-only. Omit (or send the sentinel `***`) to keep the existing value.
         * @type string
        */
        bindPassword?: string | null;
        /**
         * @type string | undefined
        */
        userFilter?: string;
        /**
         * @type string
        */
        roleAttribute?: string | null;
    } | null;
};