/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Wire shape for PUT /branding/theme. The host looks the theme up in its bundled CommunityThemeRegistry and signs the canonical manifest with the purpose-bound IThemeManifestVerifier before persisting.\n
*/
export type UpsertThemeInstallationRequest = {
    /**
     * @description Marketplace id from the host-side CommunityThemeRegistry.
     * @maxLength 64
     * @type string
    */
    themeId: string;
};