/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails.ts";
import type { QuotaAssignmentSummary } from "./QuotaAssignmentSummary.ts";
import type { UpsertQuotaAssignmentRequest } from "./UpsertQuotaAssignmentRequest.ts";

export const upsertQuotaAssignmentQueryParamsScopeEnum = {
    org: "org",
    team: "team",
    folder: "folder"
} as const;

export type UpsertQuotaAssignmentQueryParamsScopeEnumKey = (typeof upsertQuotaAssignmentQueryParamsScopeEnum)[keyof typeof upsertQuotaAssignmentQueryParamsScopeEnum];

export type UpsertQuotaAssignmentQueryParams = {
    /**
     * @description Filter to a single scope tier (\'org\', \'team\', or \'folder\').
     * @type string | undefined
    */
    scope?: UpsertQuotaAssignmentQueryParamsScopeEnumKey;
    /**
     * @description Filter to the resource with this id (orgId/teamId/folderId depending on scope).
     * @type string | undefined, uuid
    */
    id?: string;
};

/**
 * @description The upserted assignment.
*/
export type UpsertQuotaAssignment200 = QuotaAssignmentSummary;

/**
 * @description RFC 7807 error.
*/
export type UpsertQuotaAssignment400 = ProblemDetails;

/**
 * @description RFC 7807 error.
*/
export type UpsertQuotaAssignmentError = ProblemDetails;

export type UpsertQuotaAssignmentMutationRequest = UpsertQuotaAssignmentRequest;

export type UpsertQuotaAssignmentMutationResponse = UpsertQuotaAssignment200;

export type UpsertQuotaAssignmentMutation = {
    Response: UpsertQuotaAssignment200;
    Request: UpsertQuotaAssignmentMutationRequest;
    QueryParams: UpsertQuotaAssignmentQueryParams;
    Errors: UpsertQuotaAssignment400;
};