/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { VmStatus } from "./VmStatus.ts";

 /**
 * @description A virtual machine as shown in the list.
*/
export type Vm = {
    /**
     * @type string, uuid
    */
    id: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    status: VmStatus;
    /**
     * @type string
    */
    internalIp: string;
    /**
     * @type string
    */
    zone: string;
    /**
     * @type string
    */
    machineType: string;
    /**
     * @type integer
    */
    vcpu: number;
    /**
     * @type integer
    */
    ramGb: number;
    /**
     * @type integer
    */
    diskGb: number;
    /**
     * @type array | undefined
    */
    tags?: string[];
    /**
     * @type string, date-time
    */
    createdAt: string;
};