/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Vm } from "./Vm.ts";

export type VmDetail = (Vm & {
    /**
     * @type string
    */
    description?: string | null;
    /**
     * @type string
    */
    label?: string | null;
    /**
     * @type string
    */
    project: string;
    /**
     * @type string, uuid
    */
    vpcId: string;
    /**
     * @type string, uuid
    */
    subnetId: string;
    /**
     * @type array | undefined
    */
    securityGroups?: string[];
    /**
     * @type string
    */
    image: string;
    /**
     * @type boolean
    */
    diskEncrypted: boolean;
    /**
     * @type string
    */
    publicIp?: string | null;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
});