/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Vm } from "./Vm.ts";

export type VmList = {
    /**
     * @type array
    */
    items: Vm[];
    /**
     * @type integer
    */
    page: number;
    /**
     * @type integer
    */
    pageSize: number;
    /**
     * @type integer
    */
    total: number;
};