/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereInventoryClusterRow } from "./VSphereInventoryClusterRow.ts";
import type { VSphereInventoryHostRow } from "./VSphereInventoryHostRow.ts";
import type { VSphereInventorySnapshotHeader } from "./VSphereInventorySnapshotHeader.ts";
import type { VSphereInventoryVirtualMachineRow } from "./VSphereInventoryVirtualMachineRow.ts";

/**
 * @description Top-level response for GET /api/v1/vsphere/inventory. Bundles the snapshot header + the per-resource row lists so the caller can render the inventory in a single round trip.
*/
export type VSphereInventoryResponse = {
    /**
     * @description Snapshot header for GET /api/v1/vsphere/inventory. Carries the snapshot id + per-resource row counts + the refresh timestamp.
     * @type object
    */
    snapshot: VSphereInventorySnapshotHeader;
    /**
     * @type array
    */
    clusters: VSphereInventoryClusterRow[];
    /**
     * @type array
    */
    hosts: VSphereInventoryHostRow[];
    /**
     * @type array
    */
    virtualMachines: VSphereInventoryVirtualMachineRow[];
};