/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Body for POST /api/v1/vsphere/clone.
*/
export type VSphereCloneRequestBody = {
    /**
     * @description Display name of the source template. Resolved against the latest cached inventory; a missing template surfaces as 404.
     * @minLength 1
     * @type string
    */
    templateName: string;
    /**
     * @description Display name for the new VM.
     * @minLength 1
     * @type string
    */
    name: string;
    /**
     * @description Inventory folder path for the new VM; null when the caller does not care (vCenter default folder).
     * @type string
    */
    folderPath?: string | null;
};