/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Cluster row in the vSphere inventory snapshot.
*/
export type VSphereInventoryClusterRow = {
    /**
     * @description Cluster mo-ref.
     * @type string
    */
    moref: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @description Parent datacenter mo-ref.
     * @type string
    */
    datacenterMoref: string;
    /**
     * @description When true, vSphere DRS handles initial placement + load balancing.
     * @type boolean
    */
    drsEnabled: boolean;
};