/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const vSphereInventoryHostRowConnectionStateEnum = {
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    NOT_RESPONDING: "NOT_RESPONDING"
} as const;

export type VSphereInventoryHostRowConnectionStateEnumKey = (typeof vSphereInventoryHostRowConnectionStateEnum)[keyof typeof vSphereInventoryHostRowConnectionStateEnum];

/**
 * @description ESXi host row in the vSphere inventory snapshot.
*/
export type VSphereInventoryHostRow = {
    /**
     * @description Host mo-ref.
     * @type string
    */
    moref: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @description Parent cluster mo-ref.
     * @type string
    */
    clusterMoref: string;
    /**
     * @type string
    */
    connectionState: VSphereInventoryHostRowConnectionStateEnumKey;
    /**
     * @description Total logical CPU cores (sockets × cores).
     * @minLength 0
     * @type integer
    */
    cpuCores: number;
    /**
     * @description Total physical memory in MiB.
     * @minLength 0
     * @type integer, int64
    */
    memoryMib: number;
};