/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const vSphereInventoryVirtualMachineRowPowerStateEnum = {
    POWERED_ON: "POWERED_ON",
    POWERED_OFF: "POWERED_OFF",
    SUSPENDED: "SUSPENDED"
} as const;

export type VSphereInventoryVirtualMachineRowPowerStateEnumKey = (typeof vSphereInventoryVirtualMachineRowPowerStateEnum)[keyof typeof vSphereInventoryVirtualMachineRowPowerStateEnum];

/**
 * @description Virtual machine row in the vSphere inventory snapshot (non-template only).
*/
export type VSphereInventoryVirtualMachineRow = {
    /**
     * @description VM mo-ref.
     * @type string
    */
    moref: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @description Inventory folder path; null when at root.
     * @type string
    */
    folderPath?: string | null;
    /**
     * @type string
    */
    powerState: VSphereInventoryVirtualMachineRowPowerStateEnumKey;
    /**
     * @description CPU count allocated to the VM.
     * @minLength 0
     * @type integer
    */
    cpuCount: number;
    /**
     * @description Memory in MiB allocated to the VM.
     * @minLength 0
     * @type integer, int64
    */
    memoryMib: number;
    /**
     * @description Parent host mo-ref; null for templates (currently never returned — templates are out of scope for v1).
     * @type string
    */
    hostMoref?: string | null;
};