// Generates TypeScript source for per-entity fluent filter builders + fluent
// multi-field sort builders. The filter builder accumulates the same AST terms
// serializer.ts consumes, so the wire-format logic lives in exactly one place.

import {
    isDateClrType,
    isNullaryOperator,
    LIST_OPERATORS,
    resolveClrType,
    SCALAR_OPERATORS,
    type FilterOperatorName,
    type FilterableExtension,
} from './types';

/** Context for generating one entity's filter + sort builder file. */
export interface EntityBuildContext {
    readonly entityName: string;
    readonly filterable: FilterableExtension;
    readonly sortable: readonly string[];
}

/** Builds the `<entity>Filter()` factory + `<Entity>FilterBuilder` class source. */
export function generateFilterBuilderSource(ctx: EntityBuildContext): string {
    const { entityName, filterable } = ctx;
    const builderClass = `${entityName}FilterBuilder`;
    const factoryName = `${entityName[0].toLowerCase()}${entityName.slice(1)}Filter`;

    const fieldGetters = filterable.fields
        .map((field) => renderFieldGetter(field.name, field.type, field.operators, builderClass))
        .join('\n\n');

    // Emit addNullCheck only if at least one field on this entity uses a
    // null-check operator — otherwise it'd be declared-but-unused (TS6133).
    const hasAnyNullOps = filterable.fields.some((field) =>
        field.operators.some((op) => isNullaryOperator(op)),
    );
    const nullCheckMethod = hasAnyNullOps
        ? `\n\n    /** Adds a null-check term — no value. Only emitted for nullable fields. */\n    private addNullCheck(field: string, operator: 'isNull' | 'isNotNull', clrType: string): this {\n        this.pushTerm({ kind: 'comparison', field, operator, clrType });\n        return this;\n    }`
        : '';

    return `/**
 * Generated by @plexor/kubb-plugin-filter from the backend x-filterable extension.
 * Do not edit manually — regenerate via \`pnpm codegen\`.
 *
 * Fluent builder for the ${entityName} filter DSL. Each field getter returns
 * only the operators the backend allows for that field (compile-time enforced).
 * Chain with implicit AND, or explicit .and() / .or() / .group().
 *
 * @example
 *   ${factoryName}().name.eq('foo').and.status.in(['active']).build()
 *   // → 'Name=="foo";Status[]="active"'
 *
 *   ${factoryName}().name.isNull().build()
 *   // → 'Name?'
 *
 *   ${factoryName}().createdAt.gte(now('-7d')).build()
 *   // → 'CreatedAt>=now(-7d)'
 */
import { serializeFilter, type Term, type FilterOperatorName } from './_runtime';

interface StackedTerm {
    readonly term: Term;
    readonly combinator: 'and' | 'or';
}

export class ${builderClass} {
    private terms: StackedTerm[] = [];

${fieldGetters}

    and(): this {
        return this;
    }

    or(): this {
        if (this.terms.length > 0) {
            this.terms[this.terms.length - 1] = {
                ...this.terms[this.terms.length - 1]!,
                combinator: 'or',
            };
        }
        return this;
    }

    group(fn: (builder: ${builderClass}) => void): this {
        const child = new ${builderClass}();
        fn(child);
        const inner = child.buildTree();
        if (inner !== undefined) {
            this.pushTerm({ kind: 'group', inner });
        }
        return this;
    }

    /** Serializes the accumulated filter to the backend DSL string, or undefined if empty. */
    build(): string | undefined {
        return serializeFilter(this.buildTree());
    }

    private buildTree(): Term | undefined {
        if (this.terms.length === 0) return undefined;
        return this.foldTerms(this.terms.map((t) => t.term));
    }

    private foldTerms(children: Term[]): Term | undefined {
        if (children.length === 0) return undefined;
        // Split into AND-runs separated by OR edges; each run becomes a single
        // AND-combine (or a leaf if length 1); runs combine via OR. The wire
        // serializer honours precedence: andExpr ';' inside orExpr '|'.
        const runs: Term[][] = [[]];
        for (let i = 0; i < children.length; i++) {
            if (i > 0 && this.terms[i]!.combinator === 'or') {
                runs.push([]);
            }
            runs[runs.length - 1]!.push(children[i]!);
        }
        const andTerms: Term[] = runs.map((run) =>
            run.length === 1 ? run[0]! : { kind: 'combine', op: 'and', children: run },
        );
        return andTerms.length === 1
            ? andTerms[0]!
            : { kind: 'combine', op: 'or', children: andTerms };
    }

    private pushTerm(term: Term): void {
        this.terms.push({ term, combinator: 'and' });
    }

    /** Adds a comparison term (AND-joined by default; .or() flips the last edge). */
    private addComparison(field: string, operator: FilterOperatorName, value: unknown, clrType: string): this {
        this.pushTerm({ kind: 'comparison', field, operator, value, clrType });
        return this;
    }${nullCheckMethod}
}

/** Entry point — returns a fresh ${builderClass}. */
export const ${factoryName} = (): ${builderClass} => new ${builderClass}();
`;
}

/**
 * Generates the per-entity multi-field sort builder. Fluent API:
 *   sort(s => s.createdAt.desc().and(s.priority.asc()))
 * Backend wire: "CreatedAt,desc;Priority,asc"
 *
 * @see Hybrid.Shared.Filtering.QueryableFilterExtensions.ParseSortCriteria
 */
export function generateSortBuilderSource(ctx: EntityBuildContext): string {
    const { entityName, sortable } = ctx;
    const sortBuilderClass = `${entityName}SortBuilder`;
    const sortFactory = `${entityName[0].toLowerCase()}${entityName.slice(1)}Sort`;
    const typeName = `${entityName}SortableField`;
    const constName = `${entityName[0].toLowerCase()}${entityName.slice(1)}SortableFields`;

    if (sortable.length === 0) {
        return `// ${entityName}: no sortable fields declared (x-sortable absent or empty).
export type ${typeName} = never;
export const ${constName}: readonly never[] = [];
`;
    }

    const union = sortable.map((name) => `'${name}'`).join(' | ');
    const arrayLiteral = `[${sortable.map((name) => `'${name}'`).join(', ')}] as const`;
    const fieldGetters = sortable.map((name) => renderSortField(name, sortBuilderClass)).join('\n\n');

    return `/**
 * Generated by @plexor/kubb-plugin-filter from the backend x-sortable extension.
 * Do not edit manually — regenerate via \`pnpm codegen\`.
 *
 * Multi-field sort builder. Wire format: \`Field,dir;Field2,dir2\`.
 */
export type ${typeName} = ${union};

export const ${constName}: readonly ${typeName}[] = ${arrayLiteral};

export class ${sortBuilderClass} {
    private readonly criteria: Array<{ field: ${typeName}; dir: 'asc' | 'desc' }> = [];

${fieldGetters}

    and(): this {
        return this;
    }

    /** Serializes the accumulated sort criteria to the backend wire format. */
    build(): string {
        return this.criteria.map((c) => c.field + ',' + c.dir).join(';');
    }
}

export const ${sortFactory} = (): ${sortBuilderClass} => new ${sortBuilderClass}();
`;
}

function renderSortField(fieldName: string, sortBuilderClass: string): string {
    const camelName = `${fieldName[0].toLowerCase()}${fieldName.slice(1)}`;
    return `    get ${camelName}(): { asc(): ${sortBuilderClass}; desc(): ${sortBuilderClass} } {
        return {
            asc: () => {
                this.criteria.push({ field: '${fieldName}', dir: 'asc' });
                return this;
            },
            desc: () => {
                this.criteria.push({ field: '${fieldName}', dir: 'desc' });
                return this;
            },
        };
    }`;
}

function renderFieldGetter(
    fieldName: string,
    clrType: string,
    operators: readonly FilterOperatorName[],
    builderClass: string,
): string {
    const { tsType } = resolveClrType(clrType);
    const camelName = `${fieldName[0].toLowerCase()}${fieldName.slice(1)}`;
    const isDate = isDateClrType(clrType);

    const scalarOps = operators.filter((op) => (SCALAR_OPERATORS as readonly string[]).includes(op));
    const listOps = operators.filter((op) => (LIST_OPERATORS as readonly string[]).includes(op));
    const nullOps = operators.filter((op) => isNullaryOperator(op));

    // Type signature: { eq(v: string): Builder; ...; isNull(): Builder; isNotNull(): Builder }
    const typeEntries: string[] = scalarOps.map((op) => `${op}(value: ${valueTsType(op, tsType, isDate)}): ${builderClass}`);
    for (const listOp of listOps) {
        typeEntries.push(`${listOp}(values: readonly ${tsType}[]): ${builderClass}`);
    }
    for (const nullOp of nullOps) {
        const typedOp = nullOp as 'isNull' | 'isNotNull';
        typeEntries.push(`${typedOp}(): ${builderClass}`);
    }

    // Implementation object: { eq: (v) => this.addComparison(...), isNull: () => this.addNullCheck(...) }
    const implEntries: string[] = scalarOps.map(
        (op) => `${op}: (value: ${valueTsType(op, tsType, isDate)}) => this.addComparison('${fieldName}', '${op}', value, '${clrType}')`,
    );
    for (const listOp of listOps) {
        implEntries.push(
            `${listOp}: (values: readonly ${tsType}[]) => this.addComparison('${fieldName}', '${listOp}', [...values], '${clrType}')`,
        );
    }
    for (const nullOp of nullOps) {
        const typedOp = nullOp as 'isNull' | 'isNotNull';
        implEntries.push(`${typedOp}: () => this.addNullCheck('${fieldName}', '${typedOp}', '${clrType}')`);
    }

    return `    get ${camelName}(): { ${typeEntries.join('; ')} } {
        return { ${implEntries.join(', ')} };
    }`;
}

/**
 * TS parameter type for a scalar operator value. For date fields (DateTimeOffset/DateTime),
 * the value may be either an ISO string or a \`now(offset)\` token — both serialize
 * as bare values. We accept \`string\` to keep the type union simple; runtime
 * validation happens on the backend lexer (FilterFunctions.ParseDuration).
 */
function valueTsType(_op: FilterOperatorName, baseTsType: string, isDate: boolean): string {
    return isDate ? 'string' : baseTsType;
}