// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// ISigilMapper — entity → DTO mapping contract for the Sigil module.
// Handlers depend on this interface, not the concrete Mapperly-generated
// class, so tests can swap in NSubstitute mocks and the generator
// output stays an implementation detail.
// ==========================================================================

using Plexor.Modules.Sigil.Application.Users;
using Plexor.Modules.Sigil.Domain.Entities;

namespace Plexor.Modules.Sigil.Infrastructure.Mappers;

/// <summary>
///     Sigil module mapper contract. One method per public DTO
///     projection. Source-generated by Mapperly; see
///     <c>SigilMappers</c> for the concrete implementation.
/// </summary>
public interface ISigilMapper
{
    /// <summary>Map <see cref="User" /> to <see cref="UserSummary" />.</summary>
    /// <param name="source"></param>
    public UserSummary ToUserSummary(User source);

    /// <summary>Map <see cref="ApiKey" /> to <see cref="ApiKeySummary" />.</summary>
    /// <param name="source"></param>
    public ApiKeySummary ToApiKeySummary(ApiKey source);

    /// <summary>Map <see cref="SshKey" /> to <see cref="SshKeySummary" />.</summary>
    /// <param name="source"></param>
    public SshKeySummary ToSshKeySummary(SshKey source);

    /// <summary>Map <see cref="Role" /> to <see cref="RoleSummary" />.</summary>
    /// <param name="source"></param>
    public RoleSummary ToRoleSummary(Role source);

    /// <summary>Map <see cref="RoleBinding" /> to <see cref="RoleBindingSummary" />.</summary>
    /// <param name="source"></param>
    public RoleBindingSummary ToRoleBindingSummary(RoleBinding source);
}
