/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EffectiveQuotaEntry } from "../types/EffectiveQuotaEntry.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Effective rollup of a definition for a scope (what ceiling applies here, after merging).
 */
export function createEffectiveQuotaEntry(data?: Partial<EffectiveQuotaEntry>): EffectiveQuotaEntry {

  return {
    ...{"definitionId": faker.string.uuid(),"metric": faker.string.alpha(),"scope": faker.helpers.arrayElement<NonNullable<EffectiveQuotaEntry>["scope"]>(["org", "team", "folder"]),"scopeId": faker.string.uuid(),"effectiveCeiling": faker.number.int({ min: 0 }),"appliedAssignmentIds": faker.helpers.multiple(() => (faker.string.uuid()))},
    ...data || {}
  }
}