/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { GetVmPathParams, GetVmQueryResponse } from "../types/GetVm.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmDetail } from "./createVmDetail.ts";

 export function createGetVmPathParams(data?: Partial<GetVmPathParams>) {
    return {
        ...{ "vmId": faker.helpers.arrayElement<any>([faker.string.alpha(), faker.string.uuid()]) },
        ...data || {}
    };
}

 /**
 * @description Virtual machine detail.
 */
export function createGetVm200() {
    return createVmDetail();
}

 /**
 * @description RFC 7807 error.
 */
export function createGetVm404() {
    return createProblemDetails();
}

 /**
 * @description RFC 7807 error.
 */
export function createGetVmError() {
    return createProblemDetails();
}

 export function createGetVmQueryResponse(data?: Partial<GetVmQueryResponse>) {
    return faker.helpers.arrayElement<any>([createGetVm200()]) || data;
}