/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandingTheme200, UpdateBrandingTheme400, UpdateBrandingTheme403, UpdateBrandingTheme404, UpdateBrandingThemeError, UpdateBrandingThemeMutationRequest, UpdateBrandingThemeMutationResponse } from "../types/UpdateBrandingTheme.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createThemeInstallationResponse } from "./createThemeInstallationResponse.ts";
import { createUpsertThemeInstallationRequest } from "./createUpsertThemeInstallationRequest.ts";

/**
 * @description The upserted installation row.
 */
export function createUpdateBrandingTheme200(data?: Partial<UpdateBrandingTheme200>): UpdateBrandingTheme200 {

  return createThemeInstallationResponse(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingTheme400(data?: Partial<UpdateBrandingTheme400>): UpdateBrandingTheme400 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingTheme403(data?: Partial<UpdateBrandingTheme403>): UpdateBrandingTheme403 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingTheme404(data?: Partial<UpdateBrandingTheme404>): UpdateBrandingTheme404 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingThemeError(data?: Partial<UpdateBrandingThemeError>): UpdateBrandingThemeError {

  return createProblemDetails(data)
}

export function createUpdateBrandingThemeMutationRequest(data?: Partial<UpdateBrandingThemeMutationRequest>): UpdateBrandingThemeMutationRequest {

  return createUpsertThemeInstallationRequest(data)
}

export function createUpdateBrandingThemeMutationResponse(data?: Partial<UpdateBrandingThemeMutationResponse>): UpdateBrandingThemeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateBrandingTheme200()])
}