/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpsertThemeInstallationRequest } from "../types/UpsertThemeInstallationRequest.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Wire shape for PUT /branding/theme. The host looks the theme up in its bundled CommunityThemeRegistry and signs the canonical manifest with the purpose-bound IThemeManifestVerifier before persisting.\n
 */
export function createUpsertThemeInstallationRequest(data?: Partial<UpsertThemeInstallationRequest>): UpsertThemeInstallationRequest {

  return {
    ...{"themeId": faker.string.alpha({ length: 64 })},
    ...data || {}
  }
}