/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpsertOrgBrandingRequest } from "../types/UpsertOrgBrandingRequest.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Wire shape for PUT /branding/org/{orgId}. Null fields mean \"inherit the operator global default\".
 */
export function createUpsertOrgBrandingRequest(data?: Partial<UpsertOrgBrandingRequest>): UpsertOrgBrandingRequest {

  return {
    ...{"presetId": faker.string.alpha(),"customAccent": faker.string.alpha(),"brandName": faker.string.alpha({ length: 128 }),"brandLogoUrl": faker.internet.url(),"brandFaviconUrl": faker.internet.url()},
    ...data || {}
  }
}