/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: see kz note in
// msw/postAuthLoginHandler.ts.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type {
  PostAuthLogin200,
  PostAuthLogin401,
  PostAuthLoginError,
  PostAuthLoginMutationRequest,
  PostAuthLoginMutationResponse,
} from "../types/PostAuthLogin.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";

/**
 * @description Successful login — tokens + user record.
 */
export function createPostAuthLogin200(data?: Partial<PostAuthLogin200>): PostAuthLogin200 {
  return {
    ...{
      accessToken: `mock-jwt.${faker.string.alphanumeric(32)}.${faker.string.alphanumeric(8)}`,
      refreshToken: `mock-refresh.${faker.string.alphanumeric(40)}`,
      expiresIn: 3600,
      user: {
        id: faker.string.uuid(),
        email: faker.internet.email().toLowerCase(),
        displayName: faker.person.fullName(),
        roles: faker.helpers.arrayElements(['admin', 'editor', 'viewer'], { min: 1, max: 2 }),
      },
    },
    ...(data || {}),
  }
}

/**
 * @description Invalid credentials.
 */
export function createPostAuthLogin401(data?: Partial<PostAuthLogin401>): PostAuthLogin401 {
  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createPostAuthLoginError(data?: Partial<PostAuthLoginError>): PostAuthLoginError {
  return createProblemDetails(data)
}

export function createPostAuthLoginMutationRequest(data?: Partial<PostAuthLoginMutationRequest>): PostAuthLoginMutationRequest {
  return {
    ...{
      email: faker.internet.email().toLowerCase(),
      password: faker.internet.password({ length: 16 }),
    },
    ...(data || {}),
  }
}

export function createPostAuthLoginMutationResponse(data?: Partial<PostAuthLoginMutationResponse>): PostAuthLoginMutationResponse {
  return data ?? createPostAuthLogin200()
}
