/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereInventoryVirtualMachineRow } from "../types/VSphereInventoryVirtualMachineRow.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Virtual machine row in the vSphere inventory snapshot (non-template only).
 */
export function createVSphereInventoryVirtualMachineRow(data?: Partial<VSphereInventoryVirtualMachineRow>): VSphereInventoryVirtualMachineRow {

  return {
    ...{"moref": faker.string.alpha(),"name": faker.string.alpha(),"folderPath": faker.string.alpha(),"powerState": faker.helpers.arrayElement<NonNullable<VSphereInventoryVirtualMachineRow>["powerState"]>(["POWERED_ON", "POWERED_OFF", "SUSPENDED"]),"cpuCount": faker.number.int({ min: 0 }),"memoryMib": faker.number.int({ min: 0 }),"hostMoref": faker.string.alpha()},
    ...data || {}
  }
}