/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeHeartbeat400, NodeHeartbeatMutationRequest, NodeHeartbeatMutationResponse, NodeHeartbeatPathParams } from "../types/NodeHeartbeat.ts";
import { faker } from "@faker-js/faker";
import { createNodeHeartbeatRequest } from "./createNodeHeartbeatRequest.ts";
import { createProblemDetails } from "./createProblemDetails.ts";

export function createNodeHeartbeatPathParams(data?: Partial<NodeHeartbeatPathParams>): NodeHeartbeatPathParams {

  return {
    ...{"nodeId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Recorded. No body.
 */
export function createNodeHeartbeat200() {

  return undefined
}

/**
 * @description RFC 7807 error.
 */
export function createNodeHeartbeat400(data?: Partial<NodeHeartbeat400>): NodeHeartbeat400 {

  return createProblemDetails(data)
}

export function createNodeHeartbeatMutationRequest(data?: Partial<NodeHeartbeatMutationRequest>): NodeHeartbeatMutationRequest {

  return createNodeHeartbeatRequest(data)
}

export function createNodeHeartbeatMutationResponse(data?: Partial<NodeHeartbeatMutationResponse>): NodeHeartbeatMutationResponse {

  return data || faker.helpers.arrayElement<any>([createNodeHeartbeat200()])
}