/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereInventoryClusterRow } from "../types/VSphereInventoryClusterRow.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Cluster row in the vSphere inventory snapshot.
 */
export function createVSphereInventoryClusterRow(data?: Partial<VSphereInventoryClusterRow>): VSphereInventoryClusterRow {

  return {
    ...{"moref": faker.string.alpha(),"name": faker.string.alpha(),"datacenterMoref": faker.string.alpha(),"drsEnabled": faker.datatype.boolean()},
    ...data || {}
  }
}