/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpsertQuotaAssignmentRequest } from "../types/UpsertQuotaAssignmentRequest.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Wire shape for PUT /quotas/assignments. The (definitionId, scope, scopeId) tuple is the natural key.
 */
export function createUpsertQuotaAssignmentRequest(data?: Partial<UpsertQuotaAssignmentRequest>): UpsertQuotaAssignmentRequest {

  return {
    ...{"definitionId": faker.string.uuid(),"scope": faker.helpers.arrayElement<NonNullable<UpsertQuotaAssignmentRequest>["scope"]>(["org", "team", "folder"]),"scopeId": faker.string.uuid(),"ceiling": faker.number.int({ min: 0 })},
    ...data || {}
  }
}