/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpsertOrgAuthProviderRequest } from "../types/UpsertOrgAuthProviderRequest.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Wire shape for PUT /iam/orgs/{orgId}/auth-provider. Omit a sensitive field to keep the stored value unchanged (write-only secrets).
 */
export function createUpsertOrgAuthProviderRequest(data?: Partial<UpsertOrgAuthProviderRequest>): UpsertOrgAuthProviderRequest {

  return {
    ...{"provider": faker.helpers.arrayElement<NonNullable<UpsertOrgAuthProviderRequest>["provider"]>(["local", "oidc", "ldap"]),"oidc": {"issuer": faker.internet.url(),"clientId": faker.string.alpha({ length: 1 }),"clientSecret": faker.string.alpha(),"scopes": faker.helpers.multiple(() => (faker.string.alpha())),"redirectUri": faker.internet.url(),"claimMappings": {}},"ldap": {"server": faker.string.alpha(),"baseDn": faker.string.alpha(),"bindDn": faker.string.alpha(),"bindPassword": faker.string.alpha(),"userFilter": faker.string.alpha(),"roleAttribute": faker.string.alpha()}},
    ...data || {}
  }
}