/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteVm404, DeleteVmError, DeleteVmMutationResponse, DeleteVmPathParams } from "../types/DeleteVm.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";

export function createDeleteVmPathParams(data?: Partial<DeleteVmPathParams>): DeleteVmPathParams {

  return {
    ...{"vmId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Deleted.
 */
export function createDeleteVm204() {

  return undefined
}

/**
 * @description RFC 7807 error.
 */
export function createDeleteVm404(data?: Partial<DeleteVm404>): DeleteVm404 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createDeleteVmError(data?: Partial<DeleteVmError>): DeleteVmError {

  return createProblemDetails(data)
}

export function createDeleteVmMutationResponse(data?: Partial<DeleteVmMutationResponse>): DeleteVmMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteVm204()])
}