/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateVmRequest } from "../types/CreateVmRequest.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Payload from the create-VM wizard.
 */
export function createCreateVmRequest(data?: Partial<CreateVmRequest>): CreateVmRequest {

  return {
    ...{"name": faker.string.alpha({ length: 1 }),"project": faker.string.alpha(),"vpcId": faker.string.uuid(),"subnetId": faker.string.uuid(),"machineType": faker.string.alpha(),"vcpu": faker.number.int({ min: 1 }),"ramGb": faker.number.int({ min: 1 }),"diskGb": faker.number.int({ min: 10 }),"image": faker.string.alpha(),"diskEncrypted": faker.datatype.boolean(),"securityGroups": faker.helpers.multiple(() => (faker.string.alpha())),"label": faker.string.alpha(),"description": faker.string.alpha(),"tags": faker.helpers.multiple(() => (faker.string.alpha()))},
    ...data || {}
  }
}