/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeJoin201, NodeJoin400, NodeJoinMutationRequest, NodeJoinMutationResponse } from "../types/NodeJoin.ts";
import { faker } from "@faker-js/faker";
import { createNodeJoinRequest } from "./createNodeJoinRequest.ts";
import { createNodeJoinResponse } from "./createNodeJoinResponse.ts";
import { createProblemDetails } from "./createProblemDetails.ts";

/**
 * @description Registered. Body carries the NodeId and URL.
 */
export function createNodeJoin201(data?: Partial<NodeJoin201>): NodeJoin201 {

  return createNodeJoinResponse(data)
}

/**
 * @description RFC 7807 error.
 */
export function createNodeJoin400(data?: Partial<NodeJoin400>): NodeJoin400 {

  return createProblemDetails(data)
}

export function createNodeJoinMutationRequest(data?: Partial<NodeJoinMutationRequest>): NodeJoinMutationRequest {

  return createNodeJoinRequest(data)
}

export function createNodeJoinMutationResponse(data?: Partial<NodeJoinMutationResponse>): NodeJoinMutationResponse {

  return data || faker.helpers.arrayElement<any>([createNodeJoin201()])
}