/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereInventoryRefreshResponse } from "../types/VSphereInventoryRefreshResponse.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Body for the 202 response on POST /api/v1/vsphere/inventory/refresh.
 */
export function createVSphereInventoryRefreshResponse(data?: Partial<VSphereInventoryRefreshResponse>): VSphereInventoryRefreshResponse {

  return {
    ...{"snapshotId": faker.string.uuid(),"status": faker.helpers.arrayElement<NonNullable<VSphereInventoryRefreshResponse>["status"]>(["SUCCESS"])},
    ...data || {}
  }
}