/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OrgAuthProviderConfigResponse } from "../types/OrgAuthProviderConfigResponse.ts";
import { faker } from "@faker-js/faker";

/**
 * @description The org\'s identity-provider configuration. Sensitive fields (client secrets, bind passwords) are write-only; the GET response carries a sentinel (`***`) instead of the real value.
 */
export function createOrgAuthProviderConfigResponse(data?: Partial<OrgAuthProviderConfigResponse>): OrgAuthProviderConfigResponse {

  return {
    ...{"orgId": faker.string.uuid(),"provider": faker.helpers.arrayElement<NonNullable<OrgAuthProviderConfigResponse>["provider"]>(["local", "oidc", "ldap"]),"updatedAt": faker.date.anytime().toISOString(),"oidc": {"issuer": faker.internet.url(),"clientId": faker.string.alpha(),"clientSecretSentinel": faker.string.alpha(),"scopes": faker.helpers.multiple(() => (faker.string.alpha())),"redirectUri": faker.internet.url(),"claimMappings": {}},"ldap": {"server": faker.string.alpha(),"baseDn": faker.string.alpha(),"bindDn": faker.string.alpha(),"bindPasswordSentinel": faker.string.alpha(),"userFilter": faker.string.alpha(),"roleAttribute": faker.string.alpha()}},
    ...data || {}
  }
}