/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteBrandingTheme403, DeleteBrandingThemeError, DeleteBrandingThemeMutationResponse } from "../types/DeleteBrandingTheme.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";

/**
 * @description Reset (or already absent).
 */
export function createDeleteBrandingTheme204() {

  return undefined
}

/**
 * @description RFC 7807 error.
 */
export function createDeleteBrandingTheme403(data?: Partial<DeleteBrandingTheme403>): DeleteBrandingTheme403 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createDeleteBrandingThemeError(data?: Partial<DeleteBrandingThemeError>): DeleteBrandingThemeError {

  return createProblemDetails(data)
}

export function createDeleteBrandingThemeMutationResponse(data?: Partial<DeleteBrandingThemeMutationResponse>): DeleteBrandingThemeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteBrandingTheme204()])
}