/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VmStatus } from "../types/VmStatus.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Lifecycle state of a VM.
 */
export function createVmStatus(data?: Partial<VmStatus>): VmStatus {

  return data || faker.helpers.arrayElement<VmStatus>(["provisioning", "running", "stopped", "error", "idle"])
}