/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereInventorySnapshotHeader } from "../types/VSphereInventorySnapshotHeader.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Snapshot header for GET /api/v1/vsphere/inventory. Carries the snapshot id + per-resource row counts + the refresh timestamp.
 */
export function createVSphereInventorySnapshotHeader(data?: Partial<VSphereInventorySnapshotHeader>): VSphereInventorySnapshotHeader {

  return {
    ...{"id": faker.string.uuid(),"vcenterMoref": faker.string.alpha(),"datacenterCount": faker.number.int({ min: 0 }),"clusterCount": faker.number.int({ min: 0 }),"hostCount": faker.number.int({ min: 0 }),"virtualMachineCount": faker.number.int({ min: 0 }),"refreshedAt": faker.date.anytime().toISOString()},
    ...data || {}
  }
}