/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { ListVmsQueryParams, ListVmsQueryResponse } from "../types/ListVms.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmList } from "./createVmList.ts";
import { createVmStatus } from "./createVmStatus.ts";

 export function createListVmsQueryParams(data?: Partial<ListVmsQueryParams>) {
    return {
        ...{ "zone": faker.string.alpha(), "status": createVmStatus(), "q": faker.string.alpha(), "page": faker.number.int(), "pageSize": faker.number.int() },
        ...data || {}
    };
}

 /**
 * @description Paginated list of virtual machines.
 */
export function createListVms200() {
    return createVmList();
}

 /**
 * @description RFC 7807 error.
 */
export function createListVmsError() {
    return createProblemDetails();
}

 export function createListVmsQueryResponse(data?: Partial<ListVmsQueryResponse>) {
    return faker.helpers.arrayElement<any>([createListVms200()]) || data;
}