/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListQuotaUsage200, ListQuotaUsageError, ListQuotaUsageQueryParams, ListQuotaUsageQueryResponse } from "../types/ListQuotaUsage.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createQuotaUsageEntry } from "./createQuotaUsageEntry.ts";

export function createListQuotaUsageQueryParams(data?: Partial<ListQuotaUsageQueryParams>): ListQuotaUsageQueryParams {

  return {
    ...{"scope": faker.helpers.arrayElement<NonNullable<ListQuotaUsageQueryParams>["scope"]>(["org", "team", "folder"]),"id": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Per-definition usage rows.
 */
export function createListQuotaUsage200(data?: ListQuotaUsage200): ListQuotaUsage200 {

  return [
        ...faker.helpers.multiple(() => (createQuotaUsageEntry())),
        ...data || []
      ]
}

/**
 * @description RFC 7807 error.
 */
export function createListQuotaUsageError(data?: Partial<ListQuotaUsageError>): ListQuotaUsageError {

  return createProblemDetails(data)
}

export function createListQuotaUsageQueryResponse(data?: Partial<ListQuotaUsageQueryResponse>): ListQuotaUsageQueryResponse {

  return data || faker.helpers.arrayElement<any>([createListQuotaUsage200()])
}