/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteBrandingOrg404, DeleteBrandingOrgError, DeleteBrandingOrgMutationResponse, DeleteBrandingOrgPathParams } from "../types/DeleteBrandingOrg.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";

export function createDeleteBrandingOrgPathParams(data?: Partial<DeleteBrandingOrgPathParams>): DeleteBrandingOrgPathParams {

  return {
    ...{"orgId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Reset (or already absent).
 */
export function createDeleteBrandingOrg204() {

  return undefined
}

/**
 * @description RFC 7807 error.
 */
export function createDeleteBrandingOrg404(data?: Partial<DeleteBrandingOrg404>): DeleteBrandingOrg404 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createDeleteBrandingOrgError(data?: Partial<DeleteBrandingOrgError>): DeleteBrandingOrgError {

  return createProblemDetails(data)
}

export function createDeleteBrandingOrgMutationResponse(data?: Partial<DeleteBrandingOrgMutationResponse>): DeleteBrandingOrgMutationResponse {

  return data || faker.helpers.arrayElement<any>([createDeleteBrandingOrg204()])
}