/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { Problem } from "../types/Problem.ts";
import { createProblemDetails } from "./createProblemDetails.ts";

 export function createProblem() {
    return createProblemDetails();
}