/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { QuotaAssignmentSummary } from "../types/QuotaAssignmentSummary.ts";
import { faker } from "@faker-js/faker";

/**
 * @description One (definition, scope, scopeId, ceiling) tuple.
 */
export function createQuotaAssignmentSummary(data?: Partial<QuotaAssignmentSummary>): QuotaAssignmentSummary {

  return {
    ...{"id": faker.string.uuid(),"definitionId": faker.string.uuid(),"scope": faker.helpers.arrayElement<NonNullable<QuotaAssignmentSummary>["scope"]>(["org", "team", "folder"]),"scopeId": faker.string.uuid(),"ceiling": faker.number.int({ min: 0 }),"updatedAt": faker.date.anytime().toISOString()},
    ...data || {}
  }
}