/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { StartVmPathParams, StartVmMutationResponse } from "../types/StartVm.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmDetail } from "./createVmDetail.ts";

 export function createStartVmPathParams(data?: Partial<StartVmPathParams>) {
    return {
        ...{ "vmId": faker.helpers.arrayElement<any>([faker.string.alpha(), faker.string.uuid()]) },
        ...data || {}
    };
}

 /**
 * @description Start requested.
 */
export function createStartVm200() {
    return createVmDetail();
}

 /**
 * @description RFC 7807 error.
 */
export function createStartVmError() {
    return createProblemDetails();
}

 export function createStartVmMutationResponse(data?: Partial<StartVmMutationResponse>) {
    return faker.helpers.arrayElement<any>([createStartVm200()]) || data;
}