/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { ProvisionVmMutationResponse } from "../types/ProvisionVm.ts";
import { faker } from "@faker-js/faker";
import { createCreateVmRequest } from "./createCreateVmRequest.ts";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmDetail } from "./createVmDetail.ts";

 /**
 * @description VM accepted for provisioning.
 */
export function createProvisionVm201() {
    return createVmDetail();
}

 /**
 * @description RFC 7807 error.
 */
export function createProvisionVm422() {
    return createProblemDetails();
}

 /**
 * @description RFC 7807 error.
 */
export function createProvisionVmError() {
    return createProblemDetails();
}

 export function createProvisionVmMutationRequest() {
    return createCreateVmRequest();
}

 export function createProvisionVmMutationResponse(data?: Partial<ProvisionVmMutationResponse>) {
    return faker.helpers.arrayElement<any>([createProvisionVm201()]) || data;
}