/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeCommandEnvelope } from "../types/NodeCommandEnvelope.ts";
import { faker } from "@faker-js/faker";

/**
 * @description One command targeted at a node, dequeued by /commands/poll.
 */
export function createNodeCommandEnvelope(data?: Partial<NodeCommandEnvelope>): NodeCommandEnvelope {

  return {
    ...{"commandId": faker.string.uuid(),"nodeId": faker.string.uuid(),"type": faker.helpers.arrayElement<NonNullable<NodeCommandEnvelope>["type"]>(["workload.create", "workload.start", "workload.stop", "workload.delete"]),"payloadJson": faker.string.alpha(),"issuedAt": faker.date.anytime().toISOString()},
    ...data || {}
  }
}