/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: kubb skipped /branding/theme
// (see kz note in msw/getBrandingThemeHandler.ts); the FE still needs a typed
// faker fixture to drive the smoke test and the dev:mock worker.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteBrandingThemeMutationResponse, DeleteBrandingTheme403 } from "../types/DeleteBrandingTheme.ts";
import { createProblemDetails } from "./createProblemDetails.ts";

export function createDeleteBrandingTheme204() {

}

export function createDeleteBrandingTheme403(data?: Partial<DeleteBrandingTheme403>): DeleteBrandingTheme403 {

  return createProblemDetails(data)
}

export function createDeleteBrandingThemeMutationResponse(data?: Partial<DeleteBrandingThemeMutationResponse>): DeleteBrandingThemeMutationResponse {

  return data || createDeleteBrandingTheme204()
}
