/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { DeleteVmPathParams, DeleteVmMutationResponse } from "../types/DeleteVm.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";

 export function createDeleteVmPathParams(data?: Partial<DeleteVmPathParams>) {
    return {
        ...{ "vmId": faker.helpers.arrayElement<any>([faker.string.alpha(), faker.string.uuid()]) },
        ...data || {}
    };
}

 /**
 * @description Deleted.
 */
export function createDeleteVm204() {
    return undefined;
}

 /**
 * @description RFC 7807 error.
 */
export function createDeleteVm404() {
    return createProblemDetails();
}

 /**
 * @description RFC 7807 error.
 */
export function createDeleteVmError() {
    return createProblemDetails();
}

 export function createDeleteVmMutationResponse(data?: Partial<DeleteVmMutationResponse>) {
    return faker.helpers.arrayElement<any>([createDeleteVm204()]) || data;
}