/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RefreshVSphereInventory202, RefreshVSphereInventory502, RefreshVSphereInventory503, RefreshVSphereInventoryError, RefreshVSphereInventoryMutationResponse } from "../types/RefreshVSphereInventory.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVSphereInventoryRefreshResponse } from "./createVSphereInventoryRefreshResponse.ts";

/**
 * @description Refresh succeeded — the new snapshot id is in the body.
 */
export function createRefreshVSphereInventory202(data?: Partial<RefreshVSphereInventory202>): RefreshVSphereInventory202 {

  return createVSphereInventoryRefreshResponse(data)
}

/**
 * @description RFC 7807 error.
 */
export function createRefreshVSphereInventory502(data?: Partial<RefreshVSphereInventory502>): RefreshVSphereInventory502 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createRefreshVSphereInventory503(data?: Partial<RefreshVSphereInventory503>): RefreshVSphereInventory503 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createRefreshVSphereInventoryError(data?: Partial<RefreshVSphereInventoryError>): RefreshVSphereInventoryError {

  return createProblemDetails(data)
}

export function createRefreshVSphereInventoryMutationResponse(data?: Partial<RefreshVSphereInventoryMutationResponse>): RefreshVSphereInventoryMutationResponse {

  return data || faker.helpers.arrayElement<any>([createRefreshVSphereInventory202()])
}