/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VmList } from "../types/VmList.ts";
import { faker } from "@faker-js/faker";
import { createVm } from "./createVm.ts";

export function createVmList(data?: Partial<VmList>): VmList {

  return { ...{get "items"() { return faker.helpers.multiple(() => (createVm())) },"page": faker.number.int(),"pageSize": faker.number.int(),"total": faker.number.int(),...(data || {})} }
}