/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import type { StopVmPathParams, StopVmMutationResponse } from "../types/StopVm.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmDetail } from "./createVmDetail.ts";

 export function createStopVmPathParams(data?: Partial<StopVmPathParams>) {
    return {
        ...{ "vmId": faker.helpers.arrayElement<any>([faker.string.alpha(), faker.string.uuid()]) },
        ...data || {}
    };
}

 /**
 * @description Stop requested.
 */
export function createStopVm200() {
    return createVmDetail();
}

 /**
 * @description RFC 7807 error.
 */
export function createStopVmError() {
    return createProblemDetails();
}

 export function createStopVmMutationResponse(data?: Partial<StopVmMutationResponse>) {
    return faker.helpers.arrayElement<any>([createStopVm200()]) || data;
}