/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeCommandPoll200, NodeCommandPollMutationRequest, NodeCommandPollMutationResponse, NodeCommandPollPathParams } from "../types/NodeCommandPoll.ts";
import { faker } from "@faker-js/faker";
import { createNodeCommandPollRequest } from "./createNodeCommandPollRequest.ts";
import { createNodeCommandPollResponse } from "./createNodeCommandPollResponse.ts";

export function createNodeCommandPollPathParams(data?: Partial<NodeCommandPollPathParams>): NodeCommandPollPathParams {

  return {
    ...{"nodeId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Any pending commands plus the new cursor.
 */
export function createNodeCommandPoll200(data?: Partial<NodeCommandPoll200>): NodeCommandPoll200 {

  return createNodeCommandPollResponse(data)
}

export function createNodeCommandPollMutationRequest(data?: Partial<NodeCommandPollMutationRequest>): NodeCommandPollMutationRequest {

  return createNodeCommandPollRequest(data)
}

export function createNodeCommandPollMutationResponse(data?: Partial<NodeCommandPollMutationResponse>): NodeCommandPollMutationResponse {

  return data || faker.helpers.arrayElement<any>([createNodeCommandPoll200()])
}