/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListVms200, ListVmsError, ListVmsQueryParams, ListVmsQueryResponse } from "../types/ListVms.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmList } from "./createVmList.ts";
import { createVmStatus } from "./createVmStatus.ts";

export function createListVmsQueryParams(data?: Partial<ListVmsQueryParams>): ListVmsQueryParams {

  return { ...{"zone": faker.string.alpha(),get "status"() { return createVmStatus() },"q": faker.string.alpha(),"page": faker.number.int({ min: 1 }),"pageSize": faker.number.int({ min: 1, max: 100 }),...(data || {})} }
}

/**
 * @description Paginated list of virtual machines.
 */
export function createListVms200(data?: Partial<ListVms200>): ListVms200 {

  return createVmList(data)
}

/**
 * @description RFC 7807 error.
 */
export function createListVmsError(data?: Partial<ListVmsError>): ListVmsError {

  return createProblemDetails(data)
}

export function createListVmsQueryResponse(data?: Partial<ListVmsQueryResponse>): ListVmsQueryResponse {

  return data || faker.helpers.arrayElement<any>([createListVms200()])
}