/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereCloneRequestBody } from "../types/VSphereCloneRequestBody.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Body for POST /api/v1/vsphere/clone.
 */
export function createVSphereCloneRequestBody(data?: Partial<VSphereCloneRequestBody>): VSphereCloneRequestBody {

  return {
    ...{"templateName": faker.string.alpha({ length: 1 }),"name": faker.string.alpha({ length: 1 }),"folderPath": faker.string.alpha()},
    ...data || {}
  }
}