/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetQuotaDefinitions200, GetQuotaDefinitionsError, GetQuotaDefinitionsQueryResponse } from "../types/GetQuotaDefinitions.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createQuotaDefinitionSummary } from "./createQuotaDefinitionSummary.ts";

/**
 * @description List of quota definitions.
 */
export function createGetQuotaDefinitions200(data?: GetQuotaDefinitions200): GetQuotaDefinitions200 {

  return [
        ...faker.helpers.multiple(() => (createQuotaDefinitionSummary())),
        ...data || []
      ]
}

/**
 * @description RFC 7807 error.
 */
export function createGetQuotaDefinitionsError(data?: Partial<GetQuotaDefinitionsError>): GetQuotaDefinitionsError {

  return createProblemDetails(data)
}

export function createGetQuotaDefinitionsQueryResponse(data?: Partial<GetQuotaDefinitionsQueryResponse>): GetQuotaDefinitionsQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetQuotaDefinitions200()])
}