/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereInventoryResponse } from "../types/VSphereInventoryResponse.ts";
import { faker } from "@faker-js/faker";
import { createVSphereInventoryClusterRow } from "./createVSphereInventoryClusterRow.ts";
import { createVSphereInventoryHostRow } from "./createVSphereInventoryHostRow.ts";
import { createVSphereInventorySnapshotHeader } from "./createVSphereInventorySnapshotHeader.ts";
import { createVSphereInventoryVirtualMachineRow } from "./createVSphereInventoryVirtualMachineRow.ts";

/**
 * @description Top-level response for GET /api/v1/vsphere/inventory. Bundles the snapshot header + the per-resource row lists so the caller can render the inventory in a single round trip.
 */
export function createVSphereInventoryResponse(data?: Partial<VSphereInventoryResponse>): VSphereInventoryResponse {

  return { ...{get "snapshot"() { return createVSphereInventorySnapshotHeader() },get "clusters"() { return faker.helpers.multiple(() => (createVSphereInventoryClusterRow())) },get "hosts"() { return faker.helpers.multiple(() => (createVSphereInventoryHostRow())) },get "virtualMachines"() { return faker.helpers.multiple(() => (createVSphereInventoryVirtualMachineRow())) },...(data || {})} }
}