/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ThemeInstallationResponse } from "../types/ThemeInstallationResponse.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Active marketplace theme + the signature the FE boot script re-verifies.
 */
export function createThemeInstallationResponse(data?: Partial<ThemeInstallationResponse>): ThemeInstallationResponse {

  return {
    ...{"orgId": faker.string.uuid(),"themeId": faker.string.alpha({ length: 64 }),"name": faker.string.alpha({ length: 128 }),"version": faker.string.alpha({ length: 64 }),"author": faker.string.alpha({ length: 128 }),"manifestSignature": faker.helpers.fromRegExp("^[0-9a-fA-F]{64}$"),"activatedAt": faker.date.anytime().toISOString(),"activatedBy": faker.string.uuid()},
    ...data || {}
  }
}