/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VmDetail } from "../types/VmDetail.ts";
import { faker } from "@faker-js/faker";
import { createVm } from "./createVm.ts";

export function createVmDetail(data?: Partial<VmDetail>): VmDetail {

  return {
    ...{...createVm(), ...{"description": faker.string.alpha(),"label": faker.string.alpha(),"project": faker.string.alpha(),"vpcId": faker.string.uuid(),"subnetId": faker.string.uuid(),"securityGroups": faker.helpers.multiple(() => (faker.string.alpha())),"image": faker.string.alpha(),"diskEncrypted": faker.datatype.boolean(),"publicIp": faker.string.alpha(),"updatedAt": faker.date.anytime().toISOString()}},
    ...data || {}
  }
}