/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateOrgAuthProvider200, UpdateOrgAuthProvider400, UpdateOrgAuthProvider404, UpdateOrgAuthProviderError, UpdateOrgAuthProviderMutationRequest, UpdateOrgAuthProviderMutationResponse, UpdateOrgAuthProviderPathParams } from "../types/UpdateOrgAuthProvider.ts";
import { faker } from "@faker-js/faker";
import { createOrgAuthProviderConfigResponse } from "./createOrgAuthProviderConfigResponse.ts";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createUpsertOrgAuthProviderRequest } from "./createUpsertOrgAuthProviderRequest.ts";

export function createUpdateOrgAuthProviderPathParams(data?: Partial<UpdateOrgAuthProviderPathParams>): UpdateOrgAuthProviderPathParams {

  return {
    ...{"orgId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description The upserted config (secrets returned as sentinels).
 */
export function createUpdateOrgAuthProvider200(data?: Partial<UpdateOrgAuthProvider200>): UpdateOrgAuthProvider200 {

  return createOrgAuthProviderConfigResponse(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateOrgAuthProvider400(data?: Partial<UpdateOrgAuthProvider400>): UpdateOrgAuthProvider400 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateOrgAuthProvider404(data?: Partial<UpdateOrgAuthProvider404>): UpdateOrgAuthProvider404 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateOrgAuthProviderError(data?: Partial<UpdateOrgAuthProviderError>): UpdateOrgAuthProviderError {

  return createProblemDetails(data)
}

export function createUpdateOrgAuthProviderMutationRequest(data?: Partial<UpdateOrgAuthProviderMutationRequest>): UpdateOrgAuthProviderMutationRequest {

  return createUpsertOrgAuthProviderRequest(data)
}

export function createUpdateOrgAuthProviderMutationResponse(data?: Partial<UpdateOrgAuthProviderMutationResponse>): UpdateOrgAuthProviderMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateOrgAuthProvider200()])
}