/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: kubb skipped /branding/theme
// (see kz note in msw/getBrandingThemeHandler.ts); the FE still needs a typed
// faker fixture to drive the smoke test and the dev:mock worker.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandingTheme200, UpdateBrandingTheme400, UpdateBrandingTheme403, UpdateBrandingTheme404, UpdateBrandingThemeMutationRequest, UpdateBrandingThemeMutationResponse } from "../types/UpdateBrandingTheme.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createUpsertThemeInstallationRequest } from "./createUpsertThemeInstallationRequest.ts";
import { createGetBrandingTheme200 } from "./createGetBrandingTheme.ts";

/**
 * @description The upserted installation row.
 */
export function createUpdateBrandingTheme200(data?: Partial<UpdateBrandingTheme200>): UpdateBrandingTheme200 {

  return createGetBrandingTheme200(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingTheme400(data?: Partial<UpdateBrandingTheme400>): UpdateBrandingTheme400 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingTheme403(data?: Partial<UpdateBrandingTheme403>): UpdateBrandingTheme403 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingTheme404(data?: Partial<UpdateBrandingTheme404>): UpdateBrandingTheme404 {

  return createProblemDetails(data)
}

export function createUpdateBrandingThemeMutationRequest(data?: Partial<UpdateBrandingThemeMutationRequest>): UpdateBrandingThemeMutationRequest {

  return createUpsertThemeInstallationRequest(data)
}

export function createUpdateBrandingThemeMutationResponse(data?: Partial<UpdateBrandingThemeMutationResponse>): UpdateBrandingThemeMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateBrandingTheme200()])
}
