/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandingGlobal200, UpdateBrandingGlobal400, UpdateBrandingGlobalError, UpdateBrandingGlobalMutationRequest, UpdateBrandingGlobalMutationResponse } from "../types/UpdateBrandingGlobal.ts";
import { faker } from "@faker-js/faker";
import { createGlobalThemeConfigResponse } from "./createGlobalThemeConfigResponse.ts";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createUpsertGlobalThemeConfigRequest } from "./createUpsertGlobalThemeConfigRequest.ts";

/**
 * @description The upserted global row.
 */
export function createUpdateBrandingGlobal200(data?: Partial<UpdateBrandingGlobal200>): UpdateBrandingGlobal200 {

  return createGlobalThemeConfigResponse(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingGlobal400(data?: Partial<UpdateBrandingGlobal400>): UpdateBrandingGlobal400 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingGlobalError(data?: Partial<UpdateBrandingGlobalError>): UpdateBrandingGlobalError {

  return createProblemDetails(data)
}

export function createUpdateBrandingGlobalMutationRequest(data?: Partial<UpdateBrandingGlobalMutationRequest>): UpdateBrandingGlobalMutationRequest {

  return createUpsertGlobalThemeConfigRequest(data)
}

export function createUpdateBrandingGlobalMutationResponse(data?: Partial<UpdateBrandingGlobalMutationResponse>): UpdateBrandingGlobalMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateBrandingGlobal200()])
}