/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeCommandResult, NodeCommandResult400, NodeCommandResultMutationRequest, NodeCommandResultMutationResponse, NodeCommandResultPathParams } from "../types/NodeCommandResult.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";

/**
 * @description Reply to a previously-dequeued command.
 */
export function createNodeCommandResult(data?: Partial<NodeCommandResult>): NodeCommandResult {

  return {
    ...{"commandId": faker.string.uuid(),"nodeId": faker.string.uuid(),"status": faker.helpers.arrayElement<NonNullable<NodeCommandResult>["status"]>(["succeeded", "failed"]),"errorMessage": faker.string.alpha(),"completedAt": faker.date.anytime().toISOString()},
    ...data || {}
  }
}

export function createNodeCommandResultPathParams(data?: Partial<NodeCommandResultPathParams>): NodeCommandResultPathParams {

  return {
    ...{"nodeId": faker.string.uuid(),"commandId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Recorded. No body.
 */
export function createNodeCommandResult200() {

  return undefined
}

/**
 * @description RFC 7807 error.
 */
export function createNodeCommandResult400(data?: Partial<NodeCommandResult400>): NodeCommandResult400 {

  return createProblemDetails(data)
}

export function createNodeCommandResultMutationRequest(data?: Partial<NodeCommandResultMutationRequest>): NodeCommandResultMutationRequest {

  return createNodeCommandResult(data)
}

export function createNodeCommandResultMutationResponse(data?: Partial<NodeCommandResultMutationResponse>): NodeCommandResultMutationResponse {

  return data || faker.helpers.arrayElement<any>([createNodeCommandResult200()])
}