/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeJoinRequest } from "../types/NodeJoinRequest.ts";
import { faker } from "@faker-js/faker";
import { createNodeHardware } from "./createNodeHardware.ts";

/**
 * @description First message the agent sends. The join token is not yet verified.
 */
export function createNodeJoinRequest(data?: Partial<NodeJoinRequest>): NodeJoinRequest {

  return { ...{"joinToken": faker.string.alpha({ length: 1 }),get "hardware"() { return createNodeHardware() },...(data || {})} }
}