/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateBrandingOrg200, UpdateBrandingOrg400, UpdateBrandingOrg404, UpdateBrandingOrgError, UpdateBrandingOrgMutationRequest, UpdateBrandingOrgMutationResponse, UpdateBrandingOrgPathParams } from "../types/UpdateBrandingOrg.ts";
import { faker } from "@faker-js/faker";
import { createOrgBrandingConfigResponse } from "./createOrgBrandingConfigResponse.ts";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createUpsertOrgBrandingRequest } from "./createUpsertOrgBrandingRequest.ts";

export function createUpdateBrandingOrgPathParams(data?: Partial<UpdateBrandingOrgPathParams>): UpdateBrandingOrgPathParams {

  return {
    ...{"orgId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description The upserted override row.
 */
export function createUpdateBrandingOrg200(data?: Partial<UpdateBrandingOrg200>): UpdateBrandingOrg200 {

  return createOrgBrandingConfigResponse(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingOrg400(data?: Partial<UpdateBrandingOrg400>): UpdateBrandingOrg400 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingOrg404(data?: Partial<UpdateBrandingOrg404>): UpdateBrandingOrg404 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createUpdateBrandingOrgError(data?: Partial<UpdateBrandingOrgError>): UpdateBrandingOrgError {

  return createProblemDetails(data)
}

export function createUpdateBrandingOrgMutationRequest(data?: Partial<UpdateBrandingOrgMutationRequest>): UpdateBrandingOrgMutationRequest {

  return createUpsertOrgBrandingRequest(data)
}

export function createUpdateBrandingOrgMutationResponse(data?: Partial<UpdateBrandingOrgMutationResponse>): UpdateBrandingOrgMutationResponse {

  return data || faker.helpers.arrayElement<any>([createUpdateBrandingOrg200()])
}