/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostAuthLoginRequest } from "../types/PostAuthLoginRequest.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Local-credentials sign-in payload (sigill module). The FE trims + lowercases the email before sending so the backend can compare against the canonical address.
 */
export function createPostAuthLoginRequest(data?: Partial<PostAuthLoginRequest>): PostAuthLoginRequest {

  return {
    ...{"email": faker.internet.email(),"password": faker.string.alpha({ length: { min: 1, max: 128 } })},
    ...data || {}
  }
}