/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NodeJoinResponse } from "../types/NodeJoinResponse.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Reply to a join. The agent stores both fields and uses controlPlaneUrl for further calls.
 */
export function createNodeJoinResponse(data?: Partial<NodeJoinResponse>): NodeJoinResponse {

  return {
    ...{"nodeId": faker.string.uuid(),"controlPlaneUrl": faker.internet.url()},
    ...data || {}
  }
}