/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StartVm200, StartVmError, StartVmMutationResponse, StartVmPathParams } from "../types/StartVm.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmDetail } from "./createVmDetail.ts";

export function createStartVmPathParams(data?: Partial<StartVmPathParams>): StartVmPathParams {

  return {
    ...{"vmId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Start requested.
 */
export function createStartVm200(data?: Partial<StartVm200>): StartVm200 {

  return createVmDetail(data)
}

/**
 * @description RFC 7807 error.
 */
export function createStartVmError(data?: Partial<StartVmError>): StartVmError {

  return createProblemDetails(data)
}

export function createStartVmMutationResponse(data?: Partial<StartVmMutationResponse>): StartVmMutationResponse {

  return data || faker.helpers.arrayElement<any>([createStartVm200()])
}