/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OrgAuthProviderTestResult } from "../types/OrgAuthProviderTestResult.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Result of POST /iam/orgs/{orgId}/auth-provider/test. The test never persists side effects.
 */
export function createOrgAuthProviderTestResult(data?: Partial<OrgAuthProviderTestResult>): OrgAuthProviderTestResult {

  return {
    ...{"ok": faker.datatype.boolean(),"message": faker.string.alpha(),"latencyMs": faker.number.int({ min: 0 }),"details": {}},
    ...data || {}
  }
}