/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VSphereCloneResponse } from "../types/VSphereCloneResponse.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Body for the 200 response on POST /api/v1/vsphere/clone.
 */
export function createVSphereCloneResponse(data?: Partial<VSphereCloneResponse>): VSphereCloneResponse {

  return {
    ...{"runId": faker.string.uuid(),"vmMoref": faker.string.alpha(),"status": faker.helpers.arrayElement<NonNullable<VSphereCloneResponse>["status"]>(["SUCCESS"])},
    ...data || {}
  }
}