/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ListQuotaAssignments200, ListQuotaAssignmentsError, ListQuotaAssignmentsQueryParams, ListQuotaAssignmentsQueryResponse } from "../types/ListQuotaAssignments.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createQuotaAssignmentSummary } from "./createQuotaAssignmentSummary.ts";

export function createListQuotaAssignmentsQueryParams(data?: Partial<ListQuotaAssignmentsQueryParams>): ListQuotaAssignmentsQueryParams {

  return {
    ...{"scope": faker.helpers.arrayElement<NonNullable<ListQuotaAssignmentsQueryParams>["scope"]>(["org", "team", "folder"]),"id": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description List of quota assignments.
 */
export function createListQuotaAssignments200(data?: ListQuotaAssignments200): ListQuotaAssignments200 {

  return [
        ...faker.helpers.multiple(() => (createQuotaAssignmentSummary())),
        ...data || []
      ]
}

/**
 * @description RFC 7807 error.
 */
export function createListQuotaAssignmentsError(data?: Partial<ListQuotaAssignmentsError>): ListQuotaAssignmentsError {

  return createProblemDetails(data)
}

export function createListQuotaAssignmentsQueryResponse(data?: Partial<ListQuotaAssignmentsQueryResponse>): ListQuotaAssignmentsQueryResponse {

  return data || faker.helpers.arrayElement<any>([createListQuotaAssignments200()])
}