/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetVm200, GetVm404, GetVmError, GetVmPathParams, GetVmQueryResponse } from "../types/GetVm.ts";
import { faker } from "@faker-js/faker";
import { createProblemDetails } from "./createProblemDetails.ts";
import { createVmDetail } from "./createVmDetail.ts";

export function createGetVmPathParams(data?: Partial<GetVmPathParams>): GetVmPathParams {

  return {
    ...{"vmId": faker.string.uuid()},
    ...data || {}
  }
}

/**
 * @description Virtual machine detail.
 */
export function createGetVm200(data?: Partial<GetVm200>): GetVm200 {

  return createVmDetail(data)
}

/**
 * @description RFC 7807 error.
 */
export function createGetVm404(data?: Partial<GetVm404>): GetVm404 {

  return createProblemDetails(data)
}

/**
 * @description RFC 7807 error.
 */
export function createGetVmError(data?: Partial<GetVmError>): GetVmError {

  return createProblemDetails(data)
}

export function createGetVmQueryResponse(data?: Partial<GetVmQueryResponse>): GetVmQueryResponse {

  return data || faker.helpers.arrayElement<any>([createGetVm200()])
}