#!/usr/bin/env bun
/**
 * capture — captures REAL console UI screenshots (mock data) for the
 * landing page. Starts the console's own mock dev server on a scratch
 * port, drives 3 scripted flows through Chromium to each flow's end
 * state in both themes, and writes exactly one `<id>.<theme>.webp` per
 * (flow, theme) — the only stills the landing actually uses (see
 * `src/content/media-manifest.ts`, a small hand-written list, not
 * regenerated by this script).
 *
 * No video any more (product owner feedback: screenshots only) — this
 * used to also record `.mp4`/`.webm` clips via Playwright's
 * `recordVideo` + ffmpeg and rewrite `media-manifest.ts` wholesale on
 * every run. Both are gone: `CAPTURE_ONLY` used to overwrite the whole
 * manifest with just the filtered subset (a real bug — a partial re-run
 * would silently drop every screenshot not in `CAPTURE_ONLY` from the
 * file the landing imports); the fix is that this script no longer
 * writes the manifest at all, so there's nothing left to overwrite.
 *
 * Run: `bun run capture` (from web/apps/www). Everything this script
 * starts, it kills in `finally` / on SIGINT: the console mock server
 * (by PID) and the Chromium browser.
 */

import { chromium, type Browser } from 'playwright';
import { mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { findFreePort } from './lib/ports';
import { startConsoleMockServer, type RunningServer } from './lib/console-server';
import { seedSession, type Theme } from './lib/session';
import { waitSkeletonsGone, waitNetworkIdle } from './lib/wait-ready';
import { FLOWS } from './lib/flows';
import { encodeStill } from './lib/screenshot';
import { MEDIA_OUT_DIR, TMP_DIR } from './lib/paths';

const VIEWPORT = { width: 1280, height: 800 };

type Cleanup = () => Promise<void> | void;
const cleanupFns: Cleanup[] = [];
async function cleanupAll(): Promise<void> {
  for (const fn of cleanupFns.splice(0).reverse()) {
    try {
      await fn();
    } catch (err) {
      console.error('[capture] cleanup step failed:', (err as Error).message);
    }
  }
}
process.on('SIGINT', () => {
  void cleanupAll().finally(() => process.exit(130));
});

async function captureOne(
  browser: Browser,
  serverUrl: string,
  pngDir: string,
  flow: (typeof FLOWS)[number],
  theme: Theme,
): Promise<string> {
  const context = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: 2,
    colorScheme: theme,
    // The audit screenshot's "Since" date input exposed a real bug: with
    // no explicit locale, Chromium renders <input type="date">'s
    // placeholder in the OS/CI's default locale (dd.mm.yyyy) instead of
    // the en-US the rest of the console assumes.
    locale: 'en-US',
  });
  const page = await context.newPage();
  await seedSession(page, theme);

  try {
    await page.goto(`${serverUrl}${flow.startPath}`, { waitUntil: 'load', timeout: 90_000 });
    await waitSkeletonsGone(page);
    await waitNetworkIdle(page);
    await page.waitForTimeout(300);

    await flow.run(page);
    await page.waitForTimeout(500); // settle on the final frame

    const pngPath = join(pngDir, `${flow.id}.${theme}.png`);
    await page.screenshot({ path: pngPath });
    await context.close();
    return pngPath;
  } catch (err) {
    await context.close().catch(() => undefined);
    throw new Error(`flow "${flow.id}" (${theme}) failed: ${(err as Error).message}`);
  }
}

async function main(): Promise<void> {
  mkdirSync(MEDIA_OUT_DIR, { recursive: true });
  const pngDir = join(TMP_DIR, 'png');
  mkdirSync(pngDir, { recursive: true });

  const port = await findFreePort();
  console.log(`[capture] starting console mock server on :${port}`);
  const server: RunningServer = await startConsoleMockServer(port);
  cleanupFns.push(() => server.stop());

  // `--lang`, not just the context `locale` below: Chromium's native
  // `<input type="date">` placeholder format follows the BROWSER
  // PROCESS locale (this launch flag), not `navigator.language` — the
  // context option alone left the audit screenshot's "Since" filter
  // showing `dd.mm.yyyy` even with `locale: 'en-US'` set per-context.
  const browser = await chromium.launch({ args: ['--lang=en-US'] });
  cleanupFns.push(() => browser.close());

  const onlyIds = (process.env.CAPTURE_ONLY ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  const activeFlows = onlyIds.length > 0 ? FLOWS.filter((f) => onlyIds.includes(f.id)) : FLOWS;

  let totalBytes = 0;
  for (const flow of activeFlows) {
    console.log(`[capture] flow "${flow.id}" (${flow.title})`);
    console.log('  - light');
    const lightPng = await captureOne(browser, server.url, pngDir, flow, 'light');
    console.log('  - dark');
    const darkPng = await captureOne(browser, server.url, pngDir, flow, 'dark');

    console.log('  - encoding webp');
    const light = await encodeStill({ pngPath: lightPng, outDir: MEDIA_OUT_DIR, id: flow.id, theme: 'light' });
    const dark = await encodeStill({ pngPath: darkPng, outDir: MEDIA_OUT_DIR, id: flow.id, theme: 'dark' });
    totalBytes += light.sizeBytes + dark.sizeBytes;
    console.log(
      `  - done: ${(light.sizeBytes / 1024).toFixed(0)}KB (light), ${(dark.sizeBytes / 1024).toFixed(0)}KB (dark)`,
    );
  }

  await cleanupAll();
  rmSync(pngDir, { recursive: true, force: true });

  console.log(
    `[capture] done. ${activeFlows.length} screenshot(s) × 2 themes. total size ${(totalBytes / 1024 / 1024).toFixed(2)}MB`,
  );
}

main()
  .then(() => process.exit(0))
  .catch(async (err) => {
    console.error('[capture] fatal:', (err as Error).message);
    await cleanupAll();
    process.exit(1);
  });
