export type { DeleteBrandingOrgMutationKey } from "./useDeleteBrandingOrg.ts";
export type { DeleteBrandingThemeMutationKey } from "./useDeleteBrandingTheme.ts";
export type { DeleteQuotaAssignmentMutationKey } from "./useDeleteQuotaAssignment.ts";
export type { DeleteVmMutationKey } from "./useDeleteVm.ts";
export type { GetAuditQueryKey } from "./useGetAudit.ts";
export type { GetAuditSuspenseQueryKey } from "./useGetAuditSuspense.ts";
export type { GetBrandingBootQueryKey } from "./useGetBrandingBoot.ts";
export type { GetBrandingBootSuspenseQueryKey } from "./useGetBrandingBootSuspense.ts";
export type { GetBrandingGlobalQueryKey } from "./useGetBrandingGlobal.ts";
export type { GetBrandingGlobalSuspenseQueryKey } from "./useGetBrandingGlobalSuspense.ts";
export type { GetBrandingOrgQueryKey } from "./useGetBrandingOrg.ts";
export type { GetBrandingOrgSuspenseQueryKey } from "./useGetBrandingOrgSuspense.ts";
export type { GetBrandingThemeQueryKey } from "./useGetBrandingTheme.ts";
export type { GetOidcAuthorizeQueryKey } from "./useGetOidcAuthorize.ts";
export type { GetOidcAuthorizeSuspenseQueryKey } from "./useGetOidcAuthorizeSuspense.ts";
export type { GetOidcCallbackQueryKey } from "./useGetOidcCallback.ts";
export type { GetOidcCallbackSuspenseQueryKey } from "./useGetOidcCallbackSuspense.ts";
export type { GetOrgAuthProviderQueryKey } from "./useGetOrgAuthProvider.ts";
export type { GetOrgAuthProviderSuspenseQueryKey } from "./useGetOrgAuthProviderSuspense.ts";
export type { GetQuotaDefinitionsQueryKey } from "./useGetQuotaDefinitions.ts";
export type { GetQuotaDefinitionsSuspenseQueryKey } from "./useGetQuotaDefinitionsSuspense.ts";
export type { GetVmQueryKey } from "./useGetVm.ts";
export type { GetVmSuspenseQueryKey } from "./useGetVmSuspense.ts";
export type { ListEffectiveQuotasQueryKey } from "./useListEffectiveQuotas.ts";
export type { ListEffectiveQuotasSuspenseQueryKey } from "./useListEffectiveQuotasSuspense.ts";
export type { ListQuotaAssignmentsQueryKey } from "./useListQuotaAssignments.ts";
export type { ListQuotaAssignmentsSuspenseQueryKey } from "./useListQuotaAssignmentsSuspense.ts";
export type { ListQuotaUsageQueryKey } from "./useListQuotaUsage.ts";
export type { ListQuotaUsageSuspenseQueryKey } from "./useListQuotaUsageSuspense.ts";
export type { ListVmsQueryKey } from "./useListVms.ts";
export type { ListVmsSuspenseQueryKey } from "./useListVmsSuspense.ts";
export type { NodeCommandPollMutationKey } from "./useNodeCommandPoll.ts";
export type { NodeCommandResultMutationKey } from "./useNodeCommandResult.ts";
export type { NodeHeartbeatMutationKey } from "./useNodeHeartbeat.ts";
export type { NodeJoinMutationKey } from "./useNodeJoin.ts";
export type { PostAuthLoginMutationKey } from "./usePostAuthLogin.ts";
export type { PostOidcLogoutMutationKey } from "./usePostOidcLogout.ts";
export type { ProvisionVmMutationKey } from "./useProvisionVm.ts";
export type { StartVmMutationKey } from "./useStartVm.ts";
export type { StopVmMutationKey } from "./useStopVm.ts";
export type { TestOrgAuthProviderMutationKey } from "./useTestOrgAuthProvider.ts";
export type { UpdateBrandingGlobalMutationKey } from "./useUpdateBrandingGlobal.ts";
export type { UpdateBrandingOrgMutationKey } from "./useUpdateBrandingOrg.ts";
export type { UpdateBrandingThemeMutationKey } from "./useUpdateBrandingTheme.ts";
export type { UpdateOrgAuthProviderMutationKey } from "./useUpdateOrgAuthProvider.ts";
export type { UpsertQuotaAssignmentMutationKey } from "./useUpsertQuotaAssignment.ts";
export { deleteBrandingOrgMutationKey } from "./useDeleteBrandingOrg.ts";
export { deleteBrandingOrgMutationOptions } from "./useDeleteBrandingOrg.ts";
export { useDeleteBrandingOrg } from "./useDeleteBrandingOrg.ts";
export { deleteBrandingThemeMutationKey } from "./useDeleteBrandingTheme.ts";
export { deleteBrandingThemeMutationOptions } from "./useDeleteBrandingTheme.ts";
export { useDeleteBrandingTheme } from "./useDeleteBrandingTheme.ts";
export { deleteQuotaAssignmentMutationKey } from "./useDeleteQuotaAssignment.ts";
export { deleteQuotaAssignmentMutationOptions } from "./useDeleteQuotaAssignment.ts";
export { useDeleteQuotaAssignment } from "./useDeleteQuotaAssignment.ts";
export { deleteVmMutationKey } from "./useDeleteVm.ts";
export { deleteVmMutationOptions } from "./useDeleteVm.ts";
export { useDeleteVm } from "./useDeleteVm.ts";
export { getAuditQueryKey } from "./useGetAudit.ts";
export { getAuditQueryOptions } from "./useGetAudit.ts";
export { useGetAudit } from "./useGetAudit.ts";
export { getAuditSuspenseQueryKey } from "./useGetAuditSuspense.ts";
export { getAuditSuspenseQueryOptions } from "./useGetAuditSuspense.ts";
export { useGetAuditSuspense } from "./useGetAuditSuspense.ts";
export { getBrandingBootQueryKey } from "./useGetBrandingBoot.ts";
export { getBrandingBootQueryOptions } from "./useGetBrandingBoot.ts";
export { useGetBrandingBoot } from "./useGetBrandingBoot.ts";
export { getBrandingBootSuspenseQueryKey } from "./useGetBrandingBootSuspense.ts";
export { getBrandingBootSuspenseQueryOptions } from "./useGetBrandingBootSuspense.ts";
export { useGetBrandingBootSuspense } from "./useGetBrandingBootSuspense.ts";
export { getBrandingGlobalQueryKey } from "./useGetBrandingGlobal.ts";
export { getBrandingGlobalQueryOptions } from "./useGetBrandingGlobal.ts";
export { useGetBrandingGlobal } from "./useGetBrandingGlobal.ts";
export { getBrandingGlobalSuspenseQueryKey } from "./useGetBrandingGlobalSuspense.ts";
export { getBrandingGlobalSuspenseQueryOptions } from "./useGetBrandingGlobalSuspense.ts";
export { useGetBrandingGlobalSuspense } from "./useGetBrandingGlobalSuspense.ts";
export { getBrandingOrgQueryKey } from "./useGetBrandingOrg.ts";
export { getBrandingOrgQueryOptions } from "./useGetBrandingOrg.ts";
export { useGetBrandingOrg } from "./useGetBrandingOrg.ts";
export { getBrandingOrgSuspenseQueryKey } from "./useGetBrandingOrgSuspense.ts";
export { getBrandingOrgSuspenseQueryOptions } from "./useGetBrandingOrgSuspense.ts";
export { useGetBrandingOrgSuspense } from "./useGetBrandingOrgSuspense.ts";
export { getBrandingThemeQueryKey } from "./useGetBrandingTheme.ts";
export { getBrandingThemeQueryOptions } from "./useGetBrandingTheme.ts";
export { useGetBrandingTheme } from "./useGetBrandingTheme.ts";
export { getOidcAuthorizeQueryKey } from "./useGetOidcAuthorize.ts";
export { getOidcAuthorizeQueryOptions } from "./useGetOidcAuthorize.ts";
export { useGetOidcAuthorize } from "./useGetOidcAuthorize.ts";
export { getOidcAuthorizeSuspenseQueryKey } from "./useGetOidcAuthorizeSuspense.ts";
export { getOidcAuthorizeSuspenseQueryOptions } from "./useGetOidcAuthorizeSuspense.ts";
export { useGetOidcAuthorizeSuspense } from "./useGetOidcAuthorizeSuspense.ts";
export { getOidcCallbackQueryKey } from "./useGetOidcCallback.ts";
export { getOidcCallbackQueryOptions } from "./useGetOidcCallback.ts";
export { useGetOidcCallback } from "./useGetOidcCallback.ts";
export { getOidcCallbackSuspenseQueryKey } from "./useGetOidcCallbackSuspense.ts";
export { getOidcCallbackSuspenseQueryOptions } from "./useGetOidcCallbackSuspense.ts";
export { useGetOidcCallbackSuspense } from "./useGetOidcCallbackSuspense.ts";
export { getOrgAuthProviderQueryKey } from "./useGetOrgAuthProvider.ts";
export { getOrgAuthProviderQueryOptions } from "./useGetOrgAuthProvider.ts";
export { useGetOrgAuthProvider } from "./useGetOrgAuthProvider.ts";
export { getOrgAuthProviderSuspenseQueryKey } from "./useGetOrgAuthProviderSuspense.ts";
export { getOrgAuthProviderSuspenseQueryOptions } from "./useGetOrgAuthProviderSuspense.ts";
export { useGetOrgAuthProviderSuspense } from "./useGetOrgAuthProviderSuspense.ts";
export { getQuotaDefinitionsQueryKey } from "./useGetQuotaDefinitions.ts";
export { getQuotaDefinitionsQueryOptions } from "./useGetQuotaDefinitions.ts";
export { useGetQuotaDefinitions } from "./useGetQuotaDefinitions.ts";
export { getQuotaDefinitionsSuspenseQueryKey } from "./useGetQuotaDefinitionsSuspense.ts";
export { getQuotaDefinitionsSuspenseQueryOptions } from "./useGetQuotaDefinitionsSuspense.ts";
export { useGetQuotaDefinitionsSuspense } from "./useGetQuotaDefinitionsSuspense.ts";
export { getVmQueryKey } from "./useGetVm.ts";
export { getVmQueryOptions } from "./useGetVm.ts";
export { useGetVm } from "./useGetVm.ts";
export { getVmSuspenseQueryKey } from "./useGetVmSuspense.ts";
export { getVmSuspenseQueryOptions } from "./useGetVmSuspense.ts";
export { useGetVmSuspense } from "./useGetVmSuspense.ts";
export { listEffectiveQuotasQueryKey } from "./useListEffectiveQuotas.ts";
export { listEffectiveQuotasQueryOptions } from "./useListEffectiveQuotas.ts";
export { useListEffectiveQuotas } from "./useListEffectiveQuotas.ts";
export { listEffectiveQuotasSuspenseQueryKey } from "./useListEffectiveQuotasSuspense.ts";
export { listEffectiveQuotasSuspenseQueryOptions } from "./useListEffectiveQuotasSuspense.ts";
export { useListEffectiveQuotasSuspense } from "./useListEffectiveQuotasSuspense.ts";
export { listQuotaAssignmentsQueryKey } from "./useListQuotaAssignments.ts";
export { listQuotaAssignmentsQueryOptions } from "./useListQuotaAssignments.ts";
export { useListQuotaAssignments } from "./useListQuotaAssignments.ts";
export { listQuotaAssignmentsSuspenseQueryKey } from "./useListQuotaAssignmentsSuspense.ts";
export { listQuotaAssignmentsSuspenseQueryOptions } from "./useListQuotaAssignmentsSuspense.ts";
export { useListQuotaAssignmentsSuspense } from "./useListQuotaAssignmentsSuspense.ts";
export { listQuotaUsageQueryKey } from "./useListQuotaUsage.ts";
export { listQuotaUsageQueryOptions } from "./useListQuotaUsage.ts";
export { useListQuotaUsage } from "./useListQuotaUsage.ts";
export { listQuotaUsageSuspenseQueryKey } from "./useListQuotaUsageSuspense.ts";
export { listQuotaUsageSuspenseQueryOptions } from "./useListQuotaUsageSuspense.ts";
export { useListQuotaUsageSuspense } from "./useListQuotaUsageSuspense.ts";
export { listVmsQueryKey } from "./useListVms.ts";
export { listVmsQueryOptions } from "./useListVms.ts";
export { useListVms } from "./useListVms.ts";
export { listVmsSuspenseQueryKey } from "./useListVmsSuspense.ts";
export { listVmsSuspenseQueryOptions } from "./useListVmsSuspense.ts";
export { useListVmsSuspense } from "./useListVmsSuspense.ts";
export { nodeCommandPollMutationKey } from "./useNodeCommandPoll.ts";
export { nodeCommandPollMutationOptions } from "./useNodeCommandPoll.ts";
export { useNodeCommandPoll } from "./useNodeCommandPoll.ts";
export { nodeCommandResultMutationKey } from "./useNodeCommandResult.ts";
export { nodeCommandResultMutationOptions } from "./useNodeCommandResult.ts";
export { useNodeCommandResult } from "./useNodeCommandResult.ts";
export { nodeHeartbeatMutationKey } from "./useNodeHeartbeat.ts";
export { nodeHeartbeatMutationOptions } from "./useNodeHeartbeat.ts";
export { useNodeHeartbeat } from "./useNodeHeartbeat.ts";
export { nodeJoinMutationKey } from "./useNodeJoin.ts";
export { nodeJoinMutationOptions } from "./useNodeJoin.ts";
export { useNodeJoin } from "./useNodeJoin.ts";
export { postAuthLoginMutationKey } from "./usePostAuthLogin.ts";
export { postAuthLoginMutationOptions } from "./usePostAuthLogin.ts";
export { usePostAuthLogin } from "./usePostAuthLogin.ts";
export { postOidcLogoutMutationKey } from "./usePostOidcLogout.ts";
export { postOidcLogoutMutationOptions } from "./usePostOidcLogout.ts";
export { usePostOidcLogout } from "./usePostOidcLogout.ts";
export { provisionVmMutationKey } from "./useProvisionVm.ts";
export { provisionVmMutationOptions } from "./useProvisionVm.ts";
export { useProvisionVm } from "./useProvisionVm.ts";
export { startVmMutationKey } from "./useStartVm.ts";
export { startVmMutationOptions } from "./useStartVm.ts";
export { useStartVm } from "./useStartVm.ts";
export { stopVmMutationKey } from "./useStopVm.ts";
export { stopVmMutationOptions } from "./useStopVm.ts";
export { useStopVm } from "./useStopVm.ts";
export { testOrgAuthProviderMutationKey } from "./useTestOrgAuthProvider.ts";
export { testOrgAuthProviderMutationOptions } from "./useTestOrgAuthProvider.ts";
export { useTestOrgAuthProvider } from "./useTestOrgAuthProvider.ts";
export { updateBrandingGlobalMutationKey } from "./useUpdateBrandingGlobal.ts";
export { updateBrandingGlobalMutationOptions } from "./useUpdateBrandingGlobal.ts";
export { useUpdateBrandingGlobal } from "./useUpdateBrandingGlobal.ts";
export { updateBrandingOrgMutationKey } from "./useUpdateBrandingOrg.ts";
export { updateBrandingOrgMutationOptions } from "./useUpdateBrandingOrg.ts";
export { useUpdateBrandingOrg } from "./useUpdateBrandingOrg.ts";
export { updateBrandingThemeMutationKey } from "./useUpdateBrandingTheme.ts";
export { updateBrandingThemeMutationOptions } from "./useUpdateBrandingTheme.ts";
export { useUpdateBrandingTheme } from "./useUpdateBrandingTheme.ts";
export { updateOrgAuthProviderMutationKey } from "./useUpdateOrgAuthProvider.ts";
export { updateOrgAuthProviderMutationOptions } from "./useUpdateOrgAuthProvider.ts";
export { useUpdateOrgAuthProvider } from "./useUpdateOrgAuthProvider.ts";
export { upsertQuotaAssignmentMutationKey } from "./useUpsertQuotaAssignment.ts";
export { upsertQuotaAssignmentMutationOptions } from "./useUpsertQuotaAssignment.ts";
export { useUpsertQuotaAssignment } from "./useUpsertQuotaAssignment.ts";