/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import client from "@kubb/plugin-client/client";
import type { RequestConfig } from "@kubb/plugin-client/client";
import type { UseMutationOptions } from "@tanstack/react-query";
import type { DeleteVmMutationResponse, DeleteVmPathParams, DeleteVm404 } from "../types/DeleteVm.ts";
import { useMutation } from "@tanstack/react-query";

 export const deleteVmMutationKey = () => [{ "url": "/vms/{vmId}" }] as const;

 export type DeleteVmMutationKey = ReturnType<typeof deleteVmMutationKey>;

 /**
 * @summary Delete a virtual machine
 * @link /vms/:vmId
 */
async function deleteVm(vmId: DeleteVmPathParams["vmId"], config: Partial<RequestConfig> = {}) {
    const res = await client<DeleteVmMutationResponse, DeleteVm404, unknown>({ method: "DELETE", url: `/vms/${vmId}`, ...config });
    return res.data;
}

 /**
 * @summary Delete a virtual machine
 * @link /vms/:vmId
 */
export function useDeleteVm(options: {
    mutation?: UseMutationOptions<DeleteVmMutationResponse, DeleteVm404, {
        vmId: DeleteVmPathParams["vmId"];
    }>;
    client?: Partial<RequestConfig>;
} = {}) {
    const { mutation: mutationOptions, client: config = {} } = options ?? {};
    const mutationKey = mutationOptions?.mutationKey ?? deleteVmMutationKey();
    return useMutation<DeleteVmMutationResponse, DeleteVm404, {
        vmId: DeleteVmPathParams["vmId"];
    }>({
        mutationFn: async ({ vmId }) => {
            return deleteVm(vmId, config);
        },
        mutationKey,
        ...mutationOptions
    });
}