/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetVmQueryResponse, GetVmPathParams, GetVm404 } from "../types/GetVm.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getVm } from "../client/getVm.ts";

export const getVmQueryKey = (vmId: GetVmPathParams["vmId"] | undefined) => [{ url: '/vms/:vmId', params: {vmId:vmId} }] as const

export type GetVmQueryKey = ReturnType<typeof getVmQueryKey>

export function getVmQueryOptions(vmId: GetVmPathParams["vmId"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getVmQueryKey(vmId)
        return queryOptions<GetVmQueryResponse, ResponseErrorConfig<GetVm404>, GetVmQueryResponse, typeof queryKey>({
         enabled: !!(vmId),
         queryKey,
         queryFn: async ({ signal }) => {
            return getVm(vmId!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary Get a virtual machine
 * {@link /vms/:vmId}
 */
export function useGetVm<TData = GetVmQueryResponse, TQueryData = GetVmQueryResponse, TQueryKey extends QueryKey = GetVmQueryKey>(vmId: GetVmPathParams["vmId"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<GetVmQueryResponse, ResponseErrorConfig<GetVm404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getVmQueryKey(vmId)
         

         const query = useQuery({
          ...getVmQueryOptions(vmId, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetVm404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}