/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetOrgAuthProviderQueryResponse, GetOrgAuthProviderPathParams, GetOrgAuthProvider404 } from "../types/GetOrgAuthProvider.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getOrgAuthProvider } from "../client/getOrgAuthProvider.ts";

export const getOrgAuthProviderQueryKey = (orgId: GetOrgAuthProviderPathParams["orgId"] | undefined) => [{ url: '/iam/orgs/:orgId/auth-provider', params: {orgId:orgId} }] as const

export type GetOrgAuthProviderQueryKey = ReturnType<typeof getOrgAuthProviderQueryKey>

export function getOrgAuthProviderQueryOptions(orgId: GetOrgAuthProviderPathParams["orgId"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getOrgAuthProviderQueryKey(orgId)
        return queryOptions<GetOrgAuthProviderQueryResponse, ResponseErrorConfig<GetOrgAuthProvider404>, GetOrgAuthProviderQueryResponse, typeof queryKey>({
         enabled: !!(orgId),
         queryKey,
         queryFn: async ({ signal }) => {
            return getOrgAuthProvider(orgId!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the active provider (OIDC, LDAP, or local-only) + the operator-controlled knobs. 404 when the org hasn't picked a provider yet — the platform default (local) is implied until then. Sensitive fields (client secrets, bind passwords) are write-only; the GET response carries a sentinel (`"***"`) instead of the real value.
 * @summary Read the org's identity-provider configuration
 * {@link /iam/orgs/:orgId/auth-provider}
 */
export function useGetOrgAuthProvider<TData = GetOrgAuthProviderQueryResponse, TQueryData = GetOrgAuthProviderQueryResponse, TQueryKey extends QueryKey = GetOrgAuthProviderQueryKey>(orgId: GetOrgAuthProviderPathParams["orgId"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<GetOrgAuthProviderQueryResponse, ResponseErrorConfig<GetOrgAuthProvider404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getOrgAuthProviderQueryKey(orgId)
         

         const query = useQuery({
          ...getOrgAuthProviderQueryOptions(orgId, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetOrgAuthProvider404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}