/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetBrandingGlobalQueryResponse } from "../types/GetBrandingGlobal.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBrandingGlobal } from "../client/getBrandingGlobal.ts";

export const getBrandingGlobalQueryKey = () => [{ url: '/branding/global' }] as const

export type GetBrandingGlobalQueryKey = ReturnType<typeof getBrandingGlobalQueryKey>

export function getBrandingGlobalQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBrandingGlobalQueryKey()
        return queryOptions<GetBrandingGlobalQueryResponse, ResponseErrorConfig<Error>, GetBrandingGlobalQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBrandingGlobal({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description The seeder inserts a default row on first boot; the API returns 200 with the defaults even before the seeder runs (defensive). `branding.read` permission.
 * @summary Read the operator-global branding row
 * {@link /branding/global}
 */
export function useGetBrandingGlobal<TData = GetBrandingGlobalQueryResponse, TQueryData = GetBrandingGlobalQueryResponse, TQueryKey extends QueryKey = GetBrandingGlobalQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetBrandingGlobalQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBrandingGlobalQueryKey()
         

         const query = useQuery({
          ...getBrandingGlobalQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}