/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import client from "@kubb/plugin-client/client";
import type { RequestConfig } from "@kubb/plugin-client/client";
import type { QueryKey, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetVmQueryResponse, GetVmPathParams, GetVm404 } from "../types/GetVm.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

 export const getVmQueryKey = (vmId: GetVmPathParams["vmId"]) => [{ url: "/vms/:vmId", params: { vmId: vmId } }] as const;

 export type GetVmQueryKey = ReturnType<typeof getVmQueryKey>;

 /**
 * @summary Get a virtual machine
 * @link /vms/:vmId
 */
async function getVm(vmId: GetVmPathParams["vmId"], config: Partial<RequestConfig> = {}) {
    const res = await client<GetVmQueryResponse, GetVm404, unknown>({ method: "GET", url: `/vms/${vmId}`, ...config });
    return res.data;
}

 export function getVmQueryOptions(vmId: GetVmPathParams["vmId"], config: Partial<RequestConfig> = {}) {
    const queryKey = getVmQueryKey(vmId);
    return queryOptions({
        enabled: !!(vmId),
        queryKey,
        queryFn: async ({ signal }) => {
            config.signal = signal;
            return getVm(vmId, config);
        },
    });
}

 /**
 * @summary Get a virtual machine
 * @link /vms/:vmId
 */
export function useGetVm<TData = GetVmQueryResponse, TQueryData = GetVmQueryResponse, TQueryKey extends QueryKey = GetVmQueryKey>(vmId: GetVmPathParams["vmId"], options: {
    query?: Partial<QueryObserverOptions<GetVmQueryResponse, GetVm404, TData, TQueryData, TQueryKey>>;
    client?: Partial<RequestConfig>;
} = {}) {
    const { query: queryOptions, client: config = {} } = options ?? {};
    const queryKey = queryOptions?.queryKey ?? getVmQueryKey(vmId);
    const query = useQuery({
        ...getVmQueryOptions(vmId, config) as unknown as QueryObserverOptions,
        queryKey,
        ...queryOptions as unknown as Omit<QueryObserverOptions, "queryKey">
    }) as UseQueryResult<TData, GetVm404> & {
        queryKey: TQueryKey;
    };
    query.queryKey = queryKey as TQueryKey;
    return query;
}