/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetOidcAuthorizeQueryResponse, GetOidcAuthorizeQueryParams } from "../types/GetOidcAuthorize.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getOidcAuthorize } from "../client/getOidcAuthorize.ts";

export const getOidcAuthorizeQueryKey = (params: GetOidcAuthorizeQueryParams) => [{ url: '/auth/oidc/authorize' }, ...(params ? [params] : [])] as const

export type GetOidcAuthorizeQueryKey = ReturnType<typeof getOidcAuthorizeQueryKey>

export function getOidcAuthorizeQueryOptions(params: GetOidcAuthorizeQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getOidcAuthorizeQueryKey(params)
        return queryOptions<GetOidcAuthorizeQueryResponse, ResponseErrorConfig<Error>, GetOidcAuthorizeQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getOidcAuthorize(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Anonymous. Browser-driven — the server returns a 302 to the configured IdP's authorization endpoint. The generated hook is here for completeness; in practice the browser navigates directly via `<a href>` or `window.location.assign`.
 * @summary Begin the OIDC sign-in flow
 * {@link /auth/oidc/authorize}
 */
export function useGetOidcAuthorize<TData = GetOidcAuthorizeQueryResponse, TQueryData = GetOidcAuthorizeQueryResponse, TQueryKey extends QueryKey = GetOidcAuthorizeQueryKey>(params: GetOidcAuthorizeQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetOidcAuthorizeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getOidcAuthorizeQueryKey(params)
         

         const query = useQuery({
          ...getOidcAuthorizeQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}