/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetBrandingBootQueryResponse } from "../types/GetBrandingBoot.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBrandingBoot } from "../client/getBrandingBoot.ts";

export const getBrandingBootQueryKey = () => [{ url: '/branding/boot' }] as const

export type GetBrandingBootQueryKey = ReturnType<typeof getBrandingBootQueryKey>

export function getBrandingBootQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBrandingBootQueryKey()
        return queryOptions<GetBrandingBootQueryResponse, ResponseErrorConfig<Error>, GetBrandingBootQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getBrandingBoot({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Merges the operator-global row + the caller's per-org override into a single flat object suitable for the boot script (writes to `window.__PLEXOR_CONFIG__` server-side). Null fields in the org override fall back to the global value; missing fields in the global row fall back to the preset defaults.
 * @summary Resolved boot config for the caller
 * {@link /branding/boot}
 */
export function useGetBrandingBoot<TData = GetBrandingBootQueryResponse, TQueryData = GetBrandingBootQueryResponse, TQueryKey extends QueryKey = GetBrandingBootQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetBrandingBootQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBrandingBootQueryKey()
         

         const query = useQuery({
          ...getBrandingBootQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}