/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetBrandingOrgQueryResponse, GetBrandingOrgPathParams, GetBrandingOrg404 } from "../types/GetBrandingOrg.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBrandingOrg } from "../client/getBrandingOrg.ts";

export const getBrandingOrgQueryKey = (orgId: GetBrandingOrgPathParams["orgId"] | undefined) => [{ url: '/branding/org/:orgId', params: {orgId:orgId} }] as const

export type GetBrandingOrgQueryKey = ReturnType<typeof getBrandingOrgQueryKey>

export function getBrandingOrgQueryOptions(orgId: GetBrandingOrgPathParams["orgId"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getBrandingOrgQueryKey(orgId)
        return queryOptions<GetBrandingOrgQueryResponse, ResponseErrorConfig<GetBrandingOrg404>, GetBrandingOrgQueryResponse, typeof queryKey>({
         enabled: !!(orgId),
         queryKey,
         queryFn: async ({ signal }) => {
            return getBrandingOrg(orgId!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns 404 when no override exists for the org (the org inherits the operator-global row). The override is the per-tenant view; null fields inherit.
 * @summary Read the per-org branding override
 * {@link /branding/org/:orgId}
 */
export function useGetBrandingOrg<TData = GetBrandingOrgQueryResponse, TQueryData = GetBrandingOrgQueryResponse, TQueryKey extends QueryKey = GetBrandingOrgQueryKey>(orgId: GetBrandingOrgPathParams["orgId"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<GetBrandingOrgQueryResponse, ResponseErrorConfig<GetBrandingOrg404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getBrandingOrgQueryKey(orgId)
         

         const query = useQuery({
          ...getBrandingOrgQueryOptions(orgId, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetBrandingOrg404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}