/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetOidcCallbackQueryResponse, GetOidcCallbackQueryParams } from "../types/GetOidcCallback.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getOidcCallback } from "../client/getOidcCallback.ts";

export const getOidcCallbackQueryKey = (params: GetOidcCallbackQueryParams) => [{ url: '/auth/oidc/callback' }, ...(params ? [params] : [])] as const

export type GetOidcCallbackQueryKey = ReturnType<typeof getOidcCallbackQueryKey>

export function getOidcCallbackQueryOptions(params: GetOidcCallbackQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getOidcCallbackQueryKey(params)
        return queryOptions<GetOidcCallbackQueryResponse, ResponseErrorConfig<Error>, GetOidcCallbackQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getOidcCallback(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Anonymous. Exchanges the authorization code for tokens, sets the session cookie, and 302s to the original `redirect` target (or `/` if none).
 * @summary Handle the OIDC callback from the IdP
 * {@link /auth/oidc/callback}
 */
export function useGetOidcCallback<TData = GetOidcCallbackQueryResponse, TQueryData = GetOidcCallbackQueryResponse, TQueryKey extends QueryKey = GetOidcCallbackQueryKey>(params: GetOidcCallbackQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetOidcCallbackQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getOidcCallbackQueryKey(params)
         

         const query = useQuery({
          ...getOidcCallbackQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}