/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetVSphereInventoryQueryResponse, GetVSphereInventory503 } from "../types/GetVSphereInventory.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getVSphereInventory } from "../client/getVSphereInventory.ts";

export const getVSphereInventoryQueryKey = () => [{ url: '/vsphere/inventory' }] as const

export type GetVSphereInventoryQueryKey = ReturnType<typeof getVSphereInventoryQueryKey>

export function getVSphereInventoryQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getVSphereInventoryQueryKey()
        return queryOptions<GetVSphereInventoryQueryResponse, ResponseErrorConfig<GetVSphereInventory503>, GetVSphereInventoryQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getVSphereInventory({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns the latest vSphere inventory snapshot — header metadata + per-cluster / per-host / per-VM rows. 503 when the vSphere provider is not configured OR no snapshot has ever been written (caller should POST /vsphere/inventory/refresh first). 502 when vCenter is unreachable.
 * @summary Read the cached vSphere inventory
 * {@link /vsphere/inventory}
 */
export function useGetVSphereInventory<TData = GetVSphereInventoryQueryResponse, TQueryData = GetVSphereInventoryQueryResponse, TQueryKey extends QueryKey = GetVSphereInventoryQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetVSphereInventoryQueryResponse, ResponseErrorConfig<GetVSphereInventory503>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getVSphereInventoryQueryKey()
         

         const query = useQuery({
          ...getVSphereInventoryQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetVSphereInventory503>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}