/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios';
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  GetBrandingThemeQueryResponse,
  GetBrandingTheme403,
  GetBrandingTheme404,
} from '../types/GetBrandingTheme.ts';
import { queryOptions, useQuery } from '@tanstack/react-query';
import { getBrandingTheme } from '../client/getBrandingTheme.ts';

export const getBrandingThemeQueryKey = () =>
  [{ url: '/branding/theme' }] as const;

export type GetBrandingThemeQueryKey = ReturnType<typeof getBrandingThemeQueryKey>;

export function getBrandingThemeQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getBrandingThemeQueryKey();
  return queryOptions<
    GetBrandingThemeQueryResponse,
    ResponseErrorConfig<GetBrandingTheme403 | GetBrandingTheme404>,
    GetBrandingThemeQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getBrandingTheme({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Tenant-scoped (OrgId comes from the caller's bearer token). 404 when no marketplace theme has been activated yet. `branding.read` permission.
 * @summary Read the active marketplace theme
 * {@link /branding/theme}
 */
export function useGetBrandingTheme<
  TData = GetBrandingThemeQueryResponse,
  TQueryData = GetBrandingThemeQueryResponse,
  TQueryKey extends QueryKey = GetBrandingThemeQueryKey,
>(options: {
  query?: Partial<
    QueryObserverOptions<
      GetBrandingThemeQueryResponse,
      ResponseErrorConfig<GetBrandingTheme403 | GetBrandingTheme404>,
      TData,
      TQueryData,
      TQueryKey
    >
  > & { client?: QueryClient };
  client?: Partial<RequestConfig> & { client?: Client };
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getBrandingThemeQueryKey();

  const query = useQuery({
    ...getBrandingThemeQueryOptions(config),
    ...resolvedOptions,
    queryKey,
  } as unknown as QueryObserverOptions) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetBrandingTheme403 | GetBrandingTheme404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
