/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { ListEffectiveQuotasQueryResponse, ListEffectiveQuotasQueryParams } from "../types/ListEffectiveQuotas.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { listEffectiveQuotas } from "../client/listEffectiveQuotas.ts";

export const listEffectiveQuotasSuspenseQueryKey = (params?: ListEffectiveQuotasQueryParams) => [{ url: '/quotas/effective' }, ...(params ? [params] : [])] as const

export type ListEffectiveQuotasSuspenseQueryKey = ReturnType<typeof listEffectiveQuotasSuspenseQueryKey>

export function listEffectiveQuotasSuspenseQueryOptions(params?: ListEffectiveQuotasQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listEffectiveQuotasSuspenseQueryKey(params)
        return queryOptions<ListEffectiveQuotasQueryResponse, ResponseErrorConfig<Error>, ListEffectiveQuotasQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listEffectiveQuotas(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Same shape as `usage`, but `limit` is the merged ceiling after walking up the scope tree (folder → team → org → platform default). Useful for the admin UI's "what limits apply to this scope?" pane.
 * @summary Effective quotas after scope merging
 * {@link /quotas/effective}
 */
export function useListEffectiveQuotasSuspense<TData = ListEffectiveQuotasQueryResponse, TQueryKey extends QueryKey = ListEffectiveQuotasSuspenseQueryKey>(params?: ListEffectiveQuotasQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ListEffectiveQuotasQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listEffectiveQuotasSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...listEffectiveQuotasSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}