/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListVmsQueryResponse, ListVmsQueryParams } from "../types/ListVms.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { listVms } from "../client/listVms.ts";

export const listVmsQueryKey = (params?: ListVmsQueryParams) => [{ url: '/vms' }, ...(params ? [params] : [])] as const

export type ListVmsQueryKey = ReturnType<typeof listVmsQueryKey>

export function listVmsQueryOptions(params?: ListVmsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listVmsQueryKey(params)
        return queryOptions<ListVmsQueryResponse, ResponseErrorConfig<Error>, ListVmsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listVms(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @summary List virtual machines
 * {@link /vms}
 */
export function useListVms<TData = ListVmsQueryResponse, TQueryData = ListVmsQueryResponse, TQueryKey extends QueryKey = ListVmsQueryKey>(params?: ListVmsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListVmsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listVmsQueryKey(params)
         

         const query = useQuery({
          ...listVmsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}