/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { ListQuotaAssignmentsQueryResponse, ListQuotaAssignmentsQueryParams } from "../types/ListQuotaAssignments.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { listQuotaAssignments } from "../client/listQuotaAssignments.ts";

export const listQuotaAssignmentsQueryKey = (params?: ListQuotaAssignmentsQueryParams) => [{ url: '/quotas/assignments' }, ...(params ? [params] : [])] as const

export type ListQuotaAssignmentsQueryKey = ReturnType<typeof listQuotaAssignmentsQueryKey>

export function listQuotaAssignmentsQueryOptions(params?: ListQuotaAssignmentsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = listQuotaAssignmentsQueryKey(params)
        return queryOptions<ListQuotaAssignmentsQueryResponse, ResponseErrorConfig<Error>, ListQuotaAssignmentsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return listQuotaAssignments(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Returns every quota assignment that targets the given scope (or the caller's org when no filter is supplied). An assignment binds one definition to one scope (org, team, or folder) with an explicit ceiling; the effective rollup (GET /quotas/effective) merges assignments with parent scopes.
 * @summary List quota assignments
 * {@link /quotas/assignments}
 */
export function useListQuotaAssignments<TData = ListQuotaAssignmentsQueryResponse, TQueryData = ListQuotaAssignmentsQueryResponse, TQueryKey extends QueryKey = ListQuotaAssignmentsQueryKey>(params?: ListQuotaAssignmentsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListQuotaAssignmentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? listQuotaAssignmentsQueryKey(params)
         

         const query = useQuery({
          ...listQuotaAssignmentsQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}