/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { NodeHeartbeatMutationRequest, NodeHeartbeatMutationResponse, NodeHeartbeatPathParams, NodeHeartbeat400 } from "../types/NodeHeartbeat.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { nodeHeartbeat } from "../client/nodeHeartbeat.ts";

export const nodeHeartbeatMutationKey = () => [{ url: '/nodes/:nodeId/heartbeat' }] as const

export type NodeHeartbeatMutationKey = ReturnType<typeof nodeHeartbeatMutationKey>

export function nodeHeartbeatMutationOptions<TContext = unknown>(config: Partial<RequestConfig<NodeHeartbeatMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = nodeHeartbeatMutationKey()
        return mutationOptions<NodeHeartbeatMutationResponse, ResponseErrorConfig<NodeHeartbeat400>, {nodeId: NodeHeartbeatPathParams["nodeId"], data: NodeHeartbeatMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ nodeId, data }) => {
            return nodeHeartbeat(nodeId, data, config)
          },
        })

}

/**
 * @description Called by the agent on a fixed interval (default 30s). The control plane flips the node to Offline if it doesn't see a heartbeat in three intervals. Idempotent and silently ignored for unknown NodeIds in v0.1.
 * @summary Record liveness from a registered node
 * {@link /nodes/:nodeId/heartbeat}
 */
export function useNodeHeartbeat<TContext>(options: 
{
  mutation?: UseMutationOptions<NodeHeartbeatMutationResponse, ResponseErrorConfig<NodeHeartbeat400>, {nodeId: NodeHeartbeatPathParams["nodeId"], data: NodeHeartbeatMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<NodeHeartbeatMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? nodeHeartbeatMutationKey()

          const baseOptions = nodeHeartbeatMutationOptions(config) as UseMutationOptions<NodeHeartbeatMutationResponse, ResponseErrorConfig<NodeHeartbeat400>, {nodeId: NodeHeartbeatPathParams["nodeId"], data: NodeHeartbeatMutationRequest}, TContext>
          

          return useMutation<NodeHeartbeatMutationResponse, ResponseErrorConfig<NodeHeartbeat400>, {nodeId: NodeHeartbeatPathParams["nodeId"], data: NodeHeartbeatMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<NodeHeartbeatMutationResponse, ResponseErrorConfig<NodeHeartbeat400>, {nodeId: NodeHeartbeatPathParams["nodeId"], data: NodeHeartbeatMutationRequest}, TContext>
      
}