/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: see kz note in
// msw/postAuthLoginHandler.ts.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type {
  PostAuthLoginMutationRequest,
  PostAuthLoginMutationResponse,
} from "../types/PostAuthLogin.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postAuthLogin } from "../client/postAuthLogin.ts";

export const postAuthLoginMutationKey = () => [{ url: '/auth/login' }] as const

export type PostAuthLoginMutationKey = ReturnType<typeof postAuthLoginMutationKey>

export function postAuthLoginMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postAuthLoginMutationKey()
  return mutationOptions<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<Error>,
    PostAuthLoginMutationRequest,
    TContext
  >({
    mutationKey,
    mutationFn: async (data) => {
      return postAuthLogin(data, config)
    },
  })
}

/**
 * @description Local credentials login. Returns JWT + refresh token + user record on success; 401 (with problem+json) on bad credentials.
 * @summary Sign in with email + password
 * {@link /auth/login}
 */
export function usePostAuthLogin<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostAuthLoginMutationResponse,
      ResponseErrorConfig<Error>,
      PostAuthLoginMutationRequest,
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postAuthLoginMutationKey()

  const baseOptions = postAuthLoginMutationOptions(config) as UseMutationOptions<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<Error>,
    PostAuthLoginMutationRequest,
    TContext
  >

  return useMutation<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<Error>,
    PostAuthLoginMutationRequest,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostAuthLoginMutationResponse,
    ResponseErrorConfig<Error>,
    PostAuthLoginMutationRequest,
    TContext
  >
}
