/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import client from "@kubb/plugin-client/client";
import type { RequestConfig } from "@kubb/plugin-client/client";
import type { UseMutationOptions } from "@tanstack/react-query";
import type { ProvisionVmMutationRequest, ProvisionVmMutationResponse, ProvisionVm422 } from "../types/ProvisionVm.ts";
import { useMutation } from "@tanstack/react-query";

 export const provisionVmMutationKey = () => [{ "url": "/vms" }] as const;

 export type ProvisionVmMutationKey = ReturnType<typeof provisionVmMutationKey>;

 /**
 * @summary Provision a virtual machine
 * @link /vms
 */
async function provisionVm(data: ProvisionVmMutationRequest, config: Partial<RequestConfig<ProvisionVmMutationRequest>> = {}) {
    const res = await client<ProvisionVmMutationResponse, ProvisionVm422, ProvisionVmMutationRequest>({ method: "POST", url: `/vms`, data, ...config });
    return res.data;
}

 /**
 * @summary Provision a virtual machine
 * @link /vms
 */
export function useProvisionVm(options: {
    mutation?: UseMutationOptions<ProvisionVmMutationResponse, ProvisionVm422, {
        data: ProvisionVmMutationRequest;
    }>;
    client?: Partial<RequestConfig<ProvisionVmMutationRequest>>;
} = {}) {
    const { mutation: mutationOptions, client: config = {} } = options ?? {};
    const mutationKey = mutationOptions?.mutationKey ?? provisionVmMutationKey();
    return useMutation<ProvisionVmMutationResponse, ProvisionVm422, {
        data: ProvisionVmMutationRequest;
    }>({
        mutationFn: async ({ data }) => {
            return provisionVm(data, config);
        },
        mutationKey,
        ...mutationOptions
    });
}