/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { RefreshVSphereInventoryMutationResponse, RefreshVSphereInventory502, RefreshVSphereInventory503 } from "../types/RefreshVSphereInventory.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { refreshVSphereInventory } from "../client/refreshVSphereInventory.ts";

export const refreshVSphereInventoryMutationKey = () => [{ url: '/vsphere/inventory/refresh' }] as const

export type RefreshVSphereInventoryMutationKey = ReturnType<typeof refreshVSphereInventoryMutationKey>

export function refreshVSphereInventoryMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = refreshVSphereInventoryMutationKey()
        return mutationOptions<RefreshVSphereInventoryMutationResponse, ResponseErrorConfig<RefreshVSphereInventory502 | RefreshVSphereInventory503>, void, TContext>({
          mutationKey,
          mutationFn: async() => {
            return refreshVSphereInventory(config)
          },
        })

}

/**
 * @description Triggers a synchronous refresh — the call blocks until the new snapshot has been written. Returns 202 with the snapshot id. 503 when the provider is unconfigured, 502 when vCenter is unreachable.
 * @summary Force a fresh vSphere inventory pull
 * {@link /vsphere/inventory/refresh}
 */
export function useRefreshVSphereInventory<TContext>(options: 
{
  mutation?: UseMutationOptions<RefreshVSphereInventoryMutationResponse, ResponseErrorConfig<RefreshVSphereInventory502 | RefreshVSphereInventory503>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? refreshVSphereInventoryMutationKey()

          const baseOptions = refreshVSphereInventoryMutationOptions(config) as UseMutationOptions<RefreshVSphereInventoryMutationResponse, ResponseErrorConfig<RefreshVSphereInventory502 | RefreshVSphereInventory503>, void, TContext>
          

          return useMutation<RefreshVSphereInventoryMutationResponse, ResponseErrorConfig<RefreshVSphereInventory502 | RefreshVSphereInventory503>, void, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<RefreshVSphereInventoryMutationResponse, ResponseErrorConfig<RefreshVSphereInventory502 | RefreshVSphereInventory503>, void, TContext>
      
}