/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { StartVmMutationResponse, StartVmPathParams } from "../types/StartVm.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { startVm } from "../client/startVm.ts";

export const startVmMutationKey = () => [{ url: '/vms/:vmId/start' }] as const

export type StartVmMutationKey = ReturnType<typeof startVmMutationKey>

export function startVmMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = startVmMutationKey()
        return mutationOptions<StartVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StartVmPathParams["vmId"]}, TContext>({
          mutationKey,
          mutationFn: async({ vmId }) => {
            return startVm(vmId, config)
          },
        })

}

/**
 * @summary Start a virtual machine
 * {@link /vms/:vmId/start}
 */
export function useStartVm<TContext>(options: 
{
  mutation?: UseMutationOptions<StartVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StartVmPathParams["vmId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? startVmMutationKey()

          const baseOptions = startVmMutationOptions(config) as UseMutationOptions<StartVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StartVmPathParams["vmId"]}, TContext>
          

          return useMutation<StartVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StartVmPathParams["vmId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<StartVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StartVmPathParams["vmId"]}, TContext>
      
}