/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import client from "@kubb/plugin-client/client";
import type { RequestConfig } from "@kubb/plugin-client/client";
import type { UseMutationOptions } from "@tanstack/react-query";
import type { StopVmMutationResponse, StopVmPathParams } from "../types/StopVm.ts";
import { useMutation } from "@tanstack/react-query";

 export const stopVmMutationKey = () => [{ "url": "/vms/{vmId}/stop" }] as const;

 export type StopVmMutationKey = ReturnType<typeof stopVmMutationKey>;

 /**
 * @summary Stop a virtual machine
 * @link /vms/:vmId/stop
 */
async function stopVm(vmId: StopVmPathParams["vmId"], config: Partial<RequestConfig> = {}) {
    const res = await client<StopVmMutationResponse, Error, unknown>({ method: "POST", url: `/vms/${vmId}/stop`, ...config });
    return res.data;
}

 /**
 * @summary Stop a virtual machine
 * @link /vms/:vmId/stop
 */
export function useStopVm(options: {
    mutation?: UseMutationOptions<StopVmMutationResponse, Error, {
        vmId: StopVmPathParams["vmId"];
    }>;
    client?: Partial<RequestConfig>;
} = {}) {
    const { mutation: mutationOptions, client: config = {} } = options ?? {};
    const mutationKey = mutationOptions?.mutationKey ?? stopVmMutationKey();
    return useMutation<StopVmMutationResponse, Error, {
        vmId: StopVmPathParams["vmId"];
    }>({
        mutationFn: async ({ vmId }) => {
            return stopVm(vmId, config);
        },
        mutationKey,
        ...mutationOptions
    });
}