/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { StopVmMutationResponse, StopVmPathParams } from "../types/StopVm.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { stopVm } from "../client/stopVm.ts";

export const stopVmMutationKey = () => [{ url: '/vms/:vmId/stop' }] as const

export type StopVmMutationKey = ReturnType<typeof stopVmMutationKey>

export function stopVmMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = stopVmMutationKey()
        return mutationOptions<StopVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StopVmPathParams["vmId"]}, TContext>({
          mutationKey,
          mutationFn: async({ vmId }) => {
            return stopVm(vmId, config)
          },
        })

}

/**
 * @summary Stop a virtual machine
 * {@link /vms/:vmId/stop}
 */
export function useStopVm<TContext>(options: 
{
  mutation?: UseMutationOptions<StopVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StopVmPathParams["vmId"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? stopVmMutationKey()

          const baseOptions = stopVmMutationOptions(config) as UseMutationOptions<StopVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StopVmPathParams["vmId"]}, TContext>
          

          return useMutation<StopVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StopVmPathParams["vmId"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<StopVmMutationResponse, ResponseErrorConfig<Error>, {vmId: StopVmPathParams["vmId"]}, TContext>
      
}