/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateOrgAuthProviderMutationRequest, UpdateOrgAuthProviderMutationResponse, UpdateOrgAuthProviderPathParams, UpdateOrgAuthProvider400, UpdateOrgAuthProvider404 } from "../types/UpdateOrgAuthProvider.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateOrgAuthProvider } from "../client/updateOrgAuthProvider.ts";

export const updateOrgAuthProviderMutationKey = () => [{ url: '/iam/orgs/:orgId/auth-provider' }] as const

export type UpdateOrgAuthProviderMutationKey = ReturnType<typeof updateOrgAuthProviderMutationKey>

export function updateOrgAuthProviderMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateOrgAuthProviderMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateOrgAuthProviderMutationKey()
        return mutationOptions<UpdateOrgAuthProviderMutationResponse, ResponseErrorConfig<UpdateOrgAuthProvider400 | UpdateOrgAuthProvider404>, {orgId: UpdateOrgAuthProviderPathParams["orgId"], data: UpdateOrgAuthProviderMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ orgId, data }) => {
            return updateOrgAuthProvider(orgId, data, config)
          },
        })

}

/**
 * @description Replaces the provider config atomically. To rotate a secret without changing other fields, read the existing row, copy the unchanged fields, and re-PUT — secrets are write-only and a missing secret field preserves the stored value. The /test endpoint exists to validate the new config without committing to it.
 * @summary Upsert the org's identity-provider configuration
 * {@link /iam/orgs/:orgId/auth-provider}
 */
export function useUpdateOrgAuthProvider<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateOrgAuthProviderMutationResponse, ResponseErrorConfig<UpdateOrgAuthProvider400 | UpdateOrgAuthProvider404>, {orgId: UpdateOrgAuthProviderPathParams["orgId"], data: UpdateOrgAuthProviderMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateOrgAuthProviderMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateOrgAuthProviderMutationKey()

          const baseOptions = updateOrgAuthProviderMutationOptions(config) as UseMutationOptions<UpdateOrgAuthProviderMutationResponse, ResponseErrorConfig<UpdateOrgAuthProvider400 | UpdateOrgAuthProvider404>, {orgId: UpdateOrgAuthProviderPathParams["orgId"], data: UpdateOrgAuthProviderMutationRequest}, TContext>
          

          return useMutation<UpdateOrgAuthProviderMutationResponse, ResponseErrorConfig<UpdateOrgAuthProvider400 | UpdateOrgAuthProvider404>, {orgId: UpdateOrgAuthProviderPathParams["orgId"], data: UpdateOrgAuthProviderMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateOrgAuthProviderMutationResponse, ResponseErrorConfig<UpdateOrgAuthProvider400 | UpdateOrgAuthProvider404>, {orgId: UpdateOrgAuthProviderPathParams["orgId"], data: UpdateOrgAuthProviderMutationRequest}, TContext>
      
}