/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { UpdateBrandingOrgMutationRequest, UpdateBrandingOrgMutationResponse, UpdateBrandingOrgPathParams, UpdateBrandingOrg400, UpdateBrandingOrg404 } from "../types/UpdateBrandingOrg.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { updateBrandingOrg } from "../client/updateBrandingOrg.ts";

export const updateBrandingOrgMutationKey = () => [{ url: '/branding/org/:orgId' }] as const

export type UpdateBrandingOrgMutationKey = ReturnType<typeof updateBrandingOrgMutationKey>

export function updateBrandingOrgMutationOptions<TContext = unknown>(config: Partial<RequestConfig<UpdateBrandingOrgMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = updateBrandingOrgMutationKey()
        return mutationOptions<UpdateBrandingOrgMutationResponse, ResponseErrorConfig<UpdateBrandingOrg400 | UpdateBrandingOrg404>, {orgId: UpdateBrandingOrgPathParams["orgId"], data: UpdateBrandingOrgMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ orgId, data }) => {
            return updateBrandingOrg(orgId, data, config)
          },
        })

}

/**
 * @description Null fields mean "inherit the operator-global default". The first write creates the override row; subsequent writes update in place.
 * @summary Upsert the per-org branding override
 * {@link /branding/org/:orgId}
 */
export function useUpdateBrandingOrg<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateBrandingOrgMutationResponse, ResponseErrorConfig<UpdateBrandingOrg400 | UpdateBrandingOrg404>, {orgId: UpdateBrandingOrgPathParams["orgId"], data: UpdateBrandingOrgMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateBrandingOrgMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? updateBrandingOrgMutationKey()

          const baseOptions = updateBrandingOrgMutationOptions(config) as UseMutationOptions<UpdateBrandingOrgMutationResponse, ResponseErrorConfig<UpdateBrandingOrg400 | UpdateBrandingOrg404>, {orgId: UpdateBrandingOrgPathParams["orgId"], data: UpdateBrandingOrgMutationRequest}, TContext>
          

          return useMutation<UpdateBrandingOrgMutationResponse, ResponseErrorConfig<UpdateBrandingOrg400 | UpdateBrandingOrg404>, {orgId: UpdateBrandingOrgPathParams["orgId"], data: UpdateBrandingOrgMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<UpdateBrandingOrgMutationResponse, ResponseErrorConfig<UpdateBrandingOrg400 | UpdateBrandingOrg404>, {orgId: UpdateBrandingOrgPathParams["orgId"], data: UpdateBrandingOrgMutationRequest}, TContext>
      
}