// GENERATED by @tanstack/router-plugin — do not edit manually.
// This file will be regenerated on `bun run dev` / `bun run build`.

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';

const IndexRouteWithChildren = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

export const routeTree = rootRoute.addChildren({
  IndexRoute: IndexRouteWithChildren,
} as any);
