/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VmsRouteImport } from './routes/vms'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const VmsRoute = VmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/components': typeof ComponentsRoute
  '/networks': typeof NetworksRoute
  '/vms': typeof VmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/components': typeof ComponentsRoute
  '/networks': typeof NetworksRoute
  '/vms': typeof VmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/components': typeof ComponentsRoute
  '/networks': typeof NetworksRoute
  '/vms': typeof VmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audit' | '/billing' | '/components' | '/networks' | '/vms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit' | '/billing' | '/components' | '/networks' | '/vms'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/billing'
    | '/components'
    | '/networks'
    | '/vms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BillingRoute: typeof BillingRoute
  ComponentsRoute: typeof ComponentsRoute
  NetworksRoute: typeof NetworksRoute
  VmsRoute: typeof VmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vms': {
      id: '/vms'
      path: '/vms'
      fullPath: '/vms'
      preLoaderRoute: typeof VmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BillingRoute: BillingRoute,
  ComponentsRoute: ComponentsRoute,
  NetworksRoute: NetworksRoute,
  VmsRoute: VmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
