// kubb config — generates the console API layer from the Plexor.Host OpenAPI spec.
// Run: cd web/tooling/codegen && bun run generate
// Reads:  ../../../artifacts/openapi.json (built by `dotnet build` of Plexor.Host)
// Writes:  ../../apps/console/src/shared/api/src/{types,client,hooks,schemas,fixtures,msw,filters}

import { defineConfig } from '@kubb/core';
import { pluginOas } from '@kubb/plugin-oas';
import { pluginTs } from '@kubb/plugin-ts';
import { pluginClient } from '@kubb/plugin-client';
import { pluginReactQuery } from '@kubb/plugin-react-query';
import { pluginZod } from '@kubb/plugin-zod';
import { pluginMsw } from '@kubb/plugin-msw';
import { pluginFaker } from '@kubb/plugin-faker';
import { pluginFilter } from './kubb-plugin-filter/dist';

const banner =
  '/* eslint-disable */\n// @ts-nocheck\n// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.\n';

export default defineConfig({
  root: '.',
  input: {
    // Design-first: hand-authored contract is the source of truth while the
    // backend is not yet available. When Plexor.Host emits real endpoints,
    // switch back to '../../../artifacts/openapi.json' (or diff the two to
    // verify the backend matches this contract).
    path: '../../../contracts/plexor.openapi.yaml',
  },
  output: {
    path: '../../apps/console/src/shared/api/src',
    clean: true,
  },
  plugins: [
    pluginOas({ validate: true }),
    pluginTs({ output: { path: 'types', banner } }),
    pluginClient({ output: { path: 'client', banner } }),
    pluginZod({ output: { path: 'schemas', banner } }),
    pluginReactQuery({ output: { path: 'hooks', banner } }),
    pluginFaker({ output: { path: 'fixtures', banner } }),
    pluginMsw({ output: { path: 'msw', banner } }),
    pluginFilter({ output: { path: 'filters' } }),
  ],
});
