<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plexor.Modules.Quotas.Application\Plexor.Modules.Quotas.Application.csproj" />
    <ProjectReference Include="..\Plexor.Modules.Quotas.Domain\Plexor.Modules.Quotas.Domain.csproj" />
    <ProjectReference Include="..\..\..\shared\security\Plexor.Shared.Authorization\Plexor.Shared.Authorization.csproj" />
    <ProjectReference Include="..\..\..\shared\kernel\Plexor.Shared.Contracts\Plexor.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\kernel\Plexor.Shared.Kernel\Plexor.Shared.Kernel.csproj" />
    <ProjectReference Include="..\Plexor.Modules.Quotas.Infrastructure\Plexor.Modules.Quotas.Infrastructure.csproj" />
    <PackageReference Remove="Meziantou.Analyzer" />
  </ItemGroup>

</Project>
