// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plexor.Modules.Clusters.Infrastructure.Persistence;

#nullable disable

namespace Plexor.Modules.Clusters.Infrastructure.Migrations.Clusters
{
    [DbContext(typeof(ClusterDbContext))]
    [Migration("20260715233425_Identifiers_Varchar64")]
    partial class Identifiers_Varchar64
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("forge")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plexor.Modules.Clusters.Domain.Entities.Cluster", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("endpoint");

                    b.Property<string>("HostVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("host_version");

                    b.Property<string>("InstallProviders")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("install_providers");

                    b.Property<DateTimeOffset?>("JoinTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_token_expires_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("region");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Uptime")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime");

                    b.Property<string>("WireguardPublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("wireguard_public_key");

                    b.HasKey("Id");

                    b.HasIndex("OrgId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_clusters_org_id_name");

                    b.HasIndex("OrgId", "Status")
                        .HasDatabaseName("ix_clusters_org_id_status");

                    b.ToTable("clusters", "forge");
                });

            modelBuilder.Entity("Plexor.Modules.Clusters.Domain.Entities.JoinToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cluster_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("IntendedRole")
                        .HasColumnType("integer")
                        .HasColumnName("intended_role");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<string>("MinIsoVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("min_iso_version");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("RedeemedByNodeId")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("redeemed_by_node_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_join_tokens_expires_at");

                    b.HasIndex("ClusterId", "Status")
                        .HasDatabaseName("ix_join_tokens_cluster_id_status");

                    b.ToTable("join_tokens", "forge");
                });

            modelBuilder.Entity("Plexor.Modules.Clusters.Domain.Entities.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("cluster_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<string>("IsoVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("iso_version");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spec");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VmCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vm_count");

                    b.Property<string>("WireguardPublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("wireguard_public_key");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_nodes_cluster_id_hostname");

                    b.HasIndex("ClusterId", "Status")
                        .HasDatabaseName("ix_nodes_cluster_id_status");

                    b.ToTable("nodes", "forge");
                });

            modelBuilder.Entity("Plexor.Modules.Clusters.Domain.Entities.JoinToken", b =>
                {
                    b.HasOne("Plexor.Modules.Clusters.Domain.Entities.Cluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Plexor.Modules.Clusters.Domain.Entities.Node", b =>
                {
                    b.HasOne("Plexor.Modules.Clusters.Domain.Entities.Cluster", null)
                        .WithMany()
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
