/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { CloneVSphereTemplateMutationRequest, CloneVSphereTemplateMutationResponse, CloneVSphereTemplate404, CloneVSphereTemplate502, CloneVSphereTemplate503, CloneVSphereTemplate504 } from "../types/CloneVSphereTemplate.ts";

function getCloneVSphereTemplateUrl() {
  const res = { method: 'POST', url: `/vsphere/clone` as const }
  return res
}

/**
 * @description Clones a template (resolved by display name against the latest inventory) into the target folder path, then powers the new VM on. 200 on success, 404 when the template name isn't in the latest snapshot, 503 when unconfigured or the inventory is empty, 502 when vCenter rejects the clone, 504 when vCenter times out.
 * @summary Clone a vSphere template into a target VM folder
 * {@link /vsphere/clone}
 */
export async function cloneVSphereTemplate(data: CloneVSphereTemplateMutationRequest, config: Partial<RequestConfig<CloneVSphereTemplateMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<CloneVSphereTemplateMutationResponse, ResponseErrorConfig<CloneVSphereTemplate404 | CloneVSphereTemplate502 | CloneVSphereTemplate503 | CloneVSphereTemplate504>, CloneVSphereTemplateMutationRequest>({ method : "POST", url : getCloneVSphereTemplateUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}