/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { DeleteBrandingThemeMutationResponse, DeleteBrandingTheme403 } from "../types/DeleteBrandingTheme.ts";

function getDeleteBrandingThemeUrl() {
  const res = { method: 'DELETE', url: `/branding/theme` as const }
  return res
}

/**
 * @description Idempotent — a missing row is a no-op. After the delete the tenant reverts to the operator defaults. `branding.theme.update` permission.
 * @summary Reset the marketplace theme installation
 * {@link /branding/theme}
 */
export async function deleteBrandingTheme(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteBrandingThemeMutationResponse, ResponseErrorConfig<DeleteBrandingTheme403>, unknown>({ method : "DELETE", url : getDeleteBrandingThemeUrl().url.toString(), ... requestConfig })
  return res.data
}