/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { DeleteVmMutationResponse, DeleteVmPathParams, DeleteVm404 } from "../types/DeleteVm.ts";

function getDeleteVmUrl(vmId: DeleteVmPathParams["vmId"]) {
  const res = { method: 'DELETE', url: `/vms/${vmId}` as const }
  return res
}

/**
 * @summary Delete a virtual machine
 * {@link /vms/:vmId}
 */
export async function deleteVm(vmId: DeleteVmPathParams["vmId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteVmMutationResponse, ResponseErrorConfig<DeleteVm404>, unknown>({ method : "DELETE", url : getDeleteVmUrl(vmId).url.toString(), ... requestConfig })
  return res.data
}