/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios';
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios';
import type {
  GetBrandingThemeQueryResponse,
  GetBrandingTheme403,
  GetBrandingTheme404,
} from '../types/GetBrandingTheme.ts';

function getGetBrandingThemeUrl() {
  const res = { method: 'GET', url: '/branding/theme' as const };
  return res;
}

/**
 * @description Tenant-scoped (OrgId comes from the caller's bearer token). 404 when no marketplace theme has been activated yet. `branding.read` permission.
 * @summary Read the active marketplace theme
 * {@link /branding/theme}
 */
export async function getBrandingTheme(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetBrandingThemeQueryResponse,
    ResponseErrorConfig<GetBrandingTheme403 | GetBrandingTheme404>,
    unknown
  >({
    method: 'GET',
    url: getGetBrandingThemeUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
