/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetBrandingOrgQueryResponse, GetBrandingOrgPathParams, GetBrandingOrg404 } from "../types/GetBrandingOrg.ts";

function getGetBrandingOrgUrl(orgId: GetBrandingOrgPathParams["orgId"]) {
  const res = { method: 'GET', url: `/branding/org/${orgId}` as const }
  return res
}

/**
 * @description Returns 404 when no override exists for the org (the org inherits the operator-global row). The override is the per-tenant view; null fields inherit.
 * @summary Read the per-org branding override
 * {@link /branding/org/:orgId}
 */
export async function getBrandingOrg(orgId: GetBrandingOrgPathParams["orgId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetBrandingOrgQueryResponse, ResponseErrorConfig<GetBrandingOrg404>, unknown>({ method : "GET", url : getGetBrandingOrgUrl(orgId).url.toString(), ... requestConfig })
  return res.data
}