/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetBrandingBootQueryResponse } from "../types/GetBrandingBoot.ts";

function getGetBrandingBootUrl() {
  const res = { method: 'GET', url: `/branding/boot` as const }
  return res
}

/**
 * @description Merges the operator-global row + the caller's per-org override into a single flat object suitable for the boot script (writes to `window.__PLEXOR_CONFIG__` server-side). Null fields in the org override fall back to the global value; missing fields in the global row fall back to the preset defaults.
 * @summary Resolved boot config for the caller
 * {@link /branding/boot}
 */
export async function getBrandingBoot(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetBrandingBootQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetBrandingBootUrl().url.toString(), ... requestConfig })
  return res.data
}