/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { GetVmQueryResponse, GetVmPathParams, GetVm404 } from "../types/GetVm.ts";

function getGetVmUrl(vmId: GetVmPathParams["vmId"]) {
  const res = { method: 'GET', url: `/vms/${vmId}` as const }
  return res
}

/**
 * @summary Get a virtual machine
 * {@link /vms/:vmId}
 */
export async function getVm(vmId: GetVmPathParams["vmId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetVmQueryResponse, ResponseErrorConfig<GetVm404>, unknown>({ method : "GET", url : getGetVmUrl(vmId).url.toString(), ... requestConfig })
  return res.data
}