/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import client from "@kubb/plugin-client/client";
import type { RequestConfig } from "@kubb/plugin-client/client";
import type { GetVmQueryResponse, GetVmPathParams, GetVm404 } from "../types/GetVm.ts";

 /**
 * @summary Get a virtual machine
 * @link /vms/:vmId
 */
export async function getVm(vmId: GetVmPathParams["vmId"], config: Partial<RequestConfig> = {}) {
    const res = await client<GetVmQueryResponse, GetVm404, unknown>({ method: "GET", url: `/vms/${vmId}`, ...config });
    return res.data;
}