/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import client from "@kubb/plugin-client/client";
import type { RequestConfig } from "@kubb/plugin-client/client";
import type { ListVmsQueryResponse, ListVmsQueryParams } from "../types/ListVms.ts";

 /**
 * @summary List virtual machines
 * @link /vms
 */
export async function listVms(params?: ListVmsQueryParams, config: Partial<RequestConfig> = {}) {
    const res = await client<ListVmsQueryResponse, Error, unknown>({ method: "GET", url: `/vms`, params, ...config });
    return res.data;
}