/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ListEffectiveQuotasQueryResponse, ListEffectiveQuotasQueryParams } from "../types/ListEffectiveQuotas.ts";

function getListEffectiveQuotasUrl() {
  const res = { method: 'GET', url: `/quotas/effective` as const }
  return res
}

/**
 * @description Same shape as `usage`, but `limit` is the merged ceiling after walking up the scope tree (folder → team → org → platform default). Useful for the admin UI's "what limits apply to this scope?" pane.
 * @summary Effective quotas after scope merging
 * {@link /quotas/effective}
 */
export async function listEffectiveQuotas(params?: ListEffectiveQuotasQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<ListEffectiveQuotasQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getListEffectiveQuotasUrl().url.toString(), params, ... requestConfig })
  return res.data
}