/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { NodeHeartbeatMutationRequest, NodeHeartbeatMutationResponse, NodeHeartbeatPathParams, NodeHeartbeat400 } from "../types/NodeHeartbeat.ts";

function getNodeHeartbeatUrl(nodeId: NodeHeartbeatPathParams["nodeId"]) {
  const res = { method: 'POST', url: `/nodes/${nodeId}/heartbeat` as const }
  return res
}

/**
 * @description Called by the agent on a fixed interval (default 30s). The control plane flips the node to Offline if it doesn't see a heartbeat in three intervals. Idempotent and silently ignored for unknown NodeIds in v0.1.
 * @summary Record liveness from a registered node
 * {@link /nodes/:nodeId/heartbeat}
 */
export async function nodeHeartbeat(nodeId: NodeHeartbeatPathParams["nodeId"], data: NodeHeartbeatMutationRequest, config: Partial<RequestConfig<NodeHeartbeatMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<NodeHeartbeatMutationResponse, ResponseErrorConfig<NodeHeartbeat400>, NodeHeartbeatMutationRequest>({ method : "POST", url : getNodeHeartbeatUrl(nodeId).url.toString(), data : requestData, ... requestConfig })
  return res.data
}