/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { NodeCommandResultMutationRequest, NodeCommandResultMutationResponse, NodeCommandResultPathParams, NodeCommandResult400 } from "../types/NodeCommandResult.ts";

function getNodeCommandResultUrl(nodeId: NodeCommandResultPathParams["nodeId"], commandId: NodeCommandResultPathParams["commandId"]) {
  const res = { method: 'POST', url: `/nodes/${nodeId}/commands/${commandId}/result` as const }
  return res
}

/**
 * @description Called by the agent after it executes a command. The control plane logs the result in v0.1; future iterations route it to the audit module for persistence.
 * @summary Report completion status for a previously-dequeued command
 * {@link /nodes/:nodeId/commands/:commandId/result}
 */
export async function nodeCommandResult(nodeId: NodeCommandResultPathParams["nodeId"], commandId: NodeCommandResultPathParams["commandId"], data: NodeCommandResultMutationRequest, config: Partial<RequestConfig<NodeCommandResultMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<NodeCommandResultMutationResponse, ResponseErrorConfig<NodeCommandResult400>, NodeCommandResultMutationRequest>({ method : "POST", url : getNodeCommandResultUrl(nodeId, commandId).url.toString(), data : requestData, ... requestConfig })
  return res.data
}