/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.
//
// Hand-mirrored from contracts/plexor.openapi.yaml: see kz note in
// msw/postAuthLoginHandler.ts.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { PostAuthLoginMutationRequest, PostAuthLoginMutationResponse } from "../types/PostAuthLogin.ts";

function getPostAuthLoginUrl() {
  const res = { method: 'POST', url: `/auth/login` as const }
  return res
}

/**
 * @description Local credentials login. Returns JWT + refresh token + user record on success; 401 (with problem+json) on bad credentials.
 * @summary Sign in with email + password
 * {@link /auth/login}
 */
export async function postAuthLogin(
  data: PostAuthLoginMutationRequest,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<PostAuthLoginMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'POST',
    url: getPostAuthLoginUrl().url.toString(),
    data,
    ...requestConfig,
  })
  return res.data
}
