/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { PostOidcLogoutMutationResponse } from "../types/PostOidcLogout.ts";

function getPostOidcLogoutUrl() {
  const res = { method: 'POST', url: `/auth/oidc/logout` as const }
  return res
}

/**
 * @description Anonymous. Clears the session cookie and 302s to the IdP's end-session endpoint (if configured), otherwise to `/`.
 * @summary Sign out and clear the session
 * {@link /auth/oidc/logout}
 */
export async function postOidcLogout(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostOidcLogoutMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostOidcLogoutUrl().url.toString(), ... requestConfig })
  return res.data
}