/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { PostAuthLoginMutationRequest, PostAuthLoginMutationResponse, PostAuthLogin401, PostAuthLogin422 } from "../types/PostAuthLogin.ts";

function getPostAuthLoginUrl() {
  const res = { method: 'POST', url: `/auth/login` as const }
  return res
}

/**
 * @description Anonymous. Verifies the local-credentials pair (sigill module, `email` + `password`) and, on success, returns the bearer access token (RS256 JWT the console stores as `Authorization: Bearer`) plus the opaque refresh token used to mint a new access token. The `user` block seeds the FE user cache — `id`, `email`, `displayName`, and the org-scoped `roles` array.
 * @summary Sign in with email + password
 * {@link /auth/login}
 */
export async function postAuthLogin(data: PostAuthLoginMutationRequest, config: Partial<RequestConfig<PostAuthLoginMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PostAuthLoginMutationResponse, ResponseErrorConfig<PostAuthLogin401 | PostAuthLogin422>, PostAuthLoginMutationRequest>({ method : "POST", url : getPostAuthLoginUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}