/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { ProvisionVmMutationRequest, ProvisionVmMutationResponse, ProvisionVm422 } from "../types/ProvisionVm.ts";

function getProvisionVmUrl() {
  const res = { method: 'POST', url: `/vms` as const }
  return res
}

/**
 * @summary Provision a virtual machine
 * {@link /vms}
 */
export async function provisionVm(data: ProvisionVmMutationRequest, config: Partial<RequestConfig<ProvisionVmMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<ProvisionVmMutationResponse, ResponseErrorConfig<ProvisionVm422>, ProvisionVmMutationRequest>({ method : "POST", url : getProvisionVmUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}