/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { StartVmMutationResponse, StartVmPathParams } from "../types/StartVm.ts";

function getStartVmUrl(vmId: StartVmPathParams["vmId"]) {
  const res = { method: 'POST', url: `/vms/${vmId}/start` as const }
  return res
}

/**
 * @summary Start a virtual machine
 * {@link /vms/:vmId/start}
 */
export async function startVm(vmId: StartVmPathParams["vmId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<StartVmMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getStartVmUrl(vmId).url.toString(), ... requestConfig })
  return res.data
}