/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { StopVmMutationResponse, StopVmPathParams } from "../types/StopVm.ts";

function getStopVmUrl(vmId: StopVmPathParams["vmId"]) {
  const res = { method: 'POST', url: `/vms/${vmId}/stop` as const }
  return res
}

/**
 * @summary Stop a virtual machine
 * {@link /vms/:vmId/stop}
 */
export async function stopVm(vmId: StopVmPathParams["vmId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<StopVmMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getStopVmUrl(vmId).url.toString(), ... requestConfig })
  return res.data
}