/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { TestOrgAuthProviderMutationRequest, TestOrgAuthProviderMutationResponse, TestOrgAuthProviderPathParams, TestOrgAuthProvider404 } from "../types/TestOrgAuthProvider.ts";

function getTestOrgAuthProviderUrl(orgId: TestOrgAuthProviderPathParams["orgId"]) {
  const res = { method: 'POST', url: `/iam/orgs/${orgId}/auth-provider/test` as const }
  return res
}

/**
 * @description Round-trips against the configured provider without touching the session. Returns the result plus a diagnostic message; the test never persists side effects. Useful for the "Test connection" button on the auth admin page.
 * @summary Validate the org's identity-provider configuration
 * {@link /iam/orgs/:orgId/auth-provider/test}
 */
export async function testOrgAuthProvider(orgId: TestOrgAuthProviderPathParams["orgId"], data: TestOrgAuthProviderMutationRequest, config: Partial<RequestConfig<TestOrgAuthProviderMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<TestOrgAuthProviderMutationResponse, ResponseErrorConfig<TestOrgAuthProvider404>, TestOrgAuthProviderMutationRequest>({ method : "POST", url : getTestOrgAuthProviderUrl(orgId).url.toString(), data : requestData, ... requestConfig })
  return res.data
}