/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdateBrandingOrgMutationRequest, UpdateBrandingOrgMutationResponse, UpdateBrandingOrgPathParams, UpdateBrandingOrg400, UpdateBrandingOrg404 } from "../types/UpdateBrandingOrg.ts";

function getUpdateBrandingOrgUrl(orgId: UpdateBrandingOrgPathParams["orgId"]) {
  const res = { method: 'PUT', url: `/branding/org/${orgId}` as const }
  return res
}

/**
 * @description Null fields mean "inherit the operator-global default". The first write creates the override row; subsequent writes update in place.
 * @summary Upsert the per-org branding override
 * {@link /branding/org/:orgId}
 */
export async function updateBrandingOrg(orgId: UpdateBrandingOrgPathParams["orgId"], data: UpdateBrandingOrgMutationRequest, config: Partial<RequestConfig<UpdateBrandingOrgMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UpdateBrandingOrgMutationResponse, ResponseErrorConfig<UpdateBrandingOrg400 | UpdateBrandingOrg404>, UpdateBrandingOrgMutationRequest>({ method : "PUT", url : getUpdateBrandingOrgUrl(orgId).url.toString(), data : requestData, ... requestConfig })
  return res.data
}