/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpdateBrandingThemeMutationRequest, UpdateBrandingThemeMutationResponse, UpdateBrandingTheme400, UpdateBrandingTheme403, UpdateBrandingTheme404 } from "../types/UpdateBrandingTheme.ts";

function getUpdateBrandingThemeUrl() {
  const res = { method: 'PUT', url: `/branding/theme` as const }
  return res
}

/**
 * @description Body is `{ themeId }` only — the host looks up the canonical manifest in its bundled CommunityThemeRegistry and signs it with the purpose-bound IThemeManifestVerifier before persisting. Tenant-scoped. `branding.theme.update` permission. A real publisher feed (Phase 5+) would extend the request to carry a signed manifest body.
 * @summary Upsert the marketplace theme installation
 * {@link /branding/theme}
 */
export async function updateBrandingTheme(data: UpdateBrandingThemeMutationRequest, config: Partial<RequestConfig<UpdateBrandingThemeMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UpdateBrandingThemeMutationResponse, ResponseErrorConfig<UpdateBrandingTheme400 | UpdateBrandingTheme403 | UpdateBrandingTheme404>, UpdateBrandingThemeMutationRequest>({ method : "PUT", url : getUpdateBrandingThemeUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}