/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UpsertQuotaAssignmentMutationRequest, UpsertQuotaAssignmentMutationResponse, UpsertQuotaAssignmentQueryParams, UpsertQuotaAssignment400 } from "../types/UpsertQuotaAssignment.ts";

function getUpsertQuotaAssignmentUrl() {
  const res = { method: 'PUT', url: `/quotas/assignments` as const }
  return res
}

/**
 * @description Creates or updates a quota assignment. The (definitionId, scope, scopeId) tuple is the natural key — replays against the same triple overwrite the existing row's ceiling. The audit log records both the create and the update events.
 * @summary Upsert a quota assignment
 * {@link /quotas/assignments}
 */
export async function upsertQuotaAssignment(data: UpsertQuotaAssignmentMutationRequest, params?: UpsertQuotaAssignmentQueryParams, config: Partial<RequestConfig<UpsertQuotaAssignmentMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<UpsertQuotaAssignmentMutationResponse, ResponseErrorConfig<UpsertQuotaAssignment400>, UpsertQuotaAssignmentMutationRequest>({ method : "PUT", url : getUpsertQuotaAssignmentUrl().url.toString(), params, data : requestData, ... requestConfig })
  return res.data
}