using Plexor.Modules.Identity.Domain.Errors;
using Plexor.Modules.Identity.Domain.ValueObjects;
using Plexor.Shared.Filtering;

using Plexor.Shared.Kernel.Common;

namespace Plexor.Modules.Identity.Domain.Entities;

/// <summary>
///     Long-lived bearer credential for service-to-service auth. The
///     <see cref="Id" /> is the key_id (e.g. <c>kid_a8sdf8g2</c>); the
///     raw secret lives only on creation, never in the entity itself.
///     See <see cref="SecretHash" /> for the storage form.
/// </summary>
/// <remarks>
///     <para><b>Secret handling.</b> The raw secret is generated by the
///     Application layer when the key is issued (32 random bytes →
///     base64url → 43 chars). Only <see cref="SecretHash" /> (SHA-256 of
///     the secret) is persisted. Constant-time comparison happens in
///     <c>IAuthenticationService</c>.</para>
///     <para><b>Permissions scope.</b> <see cref="Permissions" /> is a
///     subset of the owner's effective permissions — issuing a key
///     grants only the permissions listed. Authorization code rejects
///     key creation when the requested permissions exceed the owner's
///     set (see <see cref="IdentityExceptions.ApiKeyPermissionsExceedOwner" />).</para>
///     <para><b>Service-to-service auth.</b> The NodeAgent ↔ Host
///     control loop uses API keys (replaces the placeholder
///     <c>JoinToken</c> in <c>Plexor.Shared.NodeApi/NodeContracts.cs</c>;
///     see <c>architecture/identity.md</c> §NodeAgent migration).</para>
/// </remarks>
public sealed class ApiKey : IFilterableEntity, ICreatedAt
{
    /// <summary>Unique identifier (UUID v7). Becomes the
    /// <c>kid_xxx</c> prefix in the bearer token.</summary>
    public Guid Id { get; init; }

    /// <summary>Tenant the key is scoped to.</summary>
    public Guid TenantId { get; init; }

    /// <summary>Owner user (the admin who issued the key).</summary>
    public Guid UserId { get; init; }

    /// <summary>Human-readable label (<c>"nodeagent-pool-eu-1"</c>,
    /// <c>"ci-deploy"</c>, ...). Not unique.</summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>SHA-256 hash of the raw secret, base64url-encoded.
    /// Never the raw secret.</summary>
    public string SecretHash { get; init; } = string.Empty;

    /// <summary>Permissions granted to this key — subset of the owner's
    /// effective permissions.</summary>
    public IReadOnlyList<PermissionScope> Permissions { get; init; } = [];

    /// <summary>Optional expiry (UTC). <c>null</c> = no expiry. Once
    /// expired, requests with this key return 401.</summary>
    public DateTimeOffset? ExpiresAt { get; init; }

    /// <summary>Last successful auth time (UTC), debounced to once per
    /// 60 s in the Application layer to avoid DB write per request.</summary>
    public DateTimeOffset? LastUsedAt { get; init; }

    /// <summary>When the key was revoked (UTC), or <c>null</c> if active.</summary>
    public DateTimeOffset? RevokedAt { get; init; }

    /// <summary>Creation time (UTC).</summary>
    public DateTimeOffset CreatedAt { get; init; }
}