const fs = require('fs');
const path = require('path');
const ms = require(path.resolve('node_modules/@iconify-json/material-symbols/icons.json'));
const lg = require(path.resolve('node_modules/@iconify-json/logos/icons.json'));

function getIcon(coll, name) {
  let ic = coll.icons[name];
  if (!ic && coll.aliases && coll.aliases[name]) ic = coll.icons[coll.aliases[name].parent];
  if (!ic) throw new Error('missing icon: ' + name);
  return { body: ic.body, width: ic.width ?? coll.width ?? 24, height: ic.height ?? coll.height ?? 24 };
}

const MAT = {
  AdminPanel:'admin-panel-settings-rounded',Api:'api-rounded',Backup:'backup-rounded',Dns:'dns',HardDrive:'hard-disk-rounded',Lan:'lan-rounded',Monitoring:'monitoring-rounded',User:'person-rounded',
  Archive:'archive-rounded',ArrowClockwise:'refresh-rounded',ArrowDown:'arrow-downward-rounded',ArrowLeft:'arrow-back-rounded',
  ArrowRight:'arrow-forward-rounded',ArrowSquareOut:'open-in-new-rounded',ArrowsClockwise:'sync-rounded',BookOpen:'menu-book-rounded',
  Buildings:'apartment-rounded',Camera:'photo-camera-rounded',CaretDoubleDown:'keyboard-double-arrow-down-rounded',CaretDown:'expand-more-rounded',
  CaretLeft:'chevron-left-rounded',CaretRight:'chevron-right-rounded',CaretUp:'expand-less-rounded',ChartBar:'bar-chart-rounded',
  ChartLine:'show-chart-rounded',Check:'check-rounded',CheckCircle:'check-circle-rounded',CircleNotch:'progress-activity',
  Clipboard:'content-paste-rounded',Clock:'schedule-rounded',ClockCounterClockwise:'history-rounded',Copy:'content-copy-rounded',
  Cpu:'developer-board-rounded',Cube:'deployed-code',Database:'database',Desktop:'desktop-windows-rounded',DotsSixVertical:'drag-indicator',
  DotsThree:'more-horiz',DotsThreeVertical:'more-vert',DownloadSimple:'download-rounded',Eye:'visibility-rounded',EyeSlash:'visibility-off-rounded',FloppyDisk:'save-rounded',Folder:'folder-rounded',
  FolderOpen:'folder-open-rounded',Funnel:'filter-alt',Gear:'settings-rounded',GearSix:'settings-rounded',Globe:'public',
  HardDrives:'storage-rounded',Hexagon:'hexagon-rounded',House:'home-rounded',Image:'image-rounded',Info:'info-rounded',Key:'key-rounded',
  Lifebuoy:'support',Lightning:'bolt-rounded',ListDashes:'list-rounded',MagnifyingGlass:'search-rounded',Memory:'memory-rounded',
  Minus:'remove-rounded',Moon:'dark-mode-rounded',Package:'package-2',Pause:'pause-rounded',Pencil:'edit-rounded',PencilSimple:'edit-rounded',
  Play:'play-arrow-rounded',Plus:'add-rounded',Prohibit:'block',Question:'help-rounded',Receipt:'receipt-long-rounded',Scales:'balance-rounded',
  ShieldCheck:'verified-user-rounded',Sidebar:'dock-to-left',SidebarIcon:'dock-to-left',SignOut:'logout-rounded',SlidersHorizontal:'tune-rounded',
  SquaresFour:'grid-view-rounded',Stack:'stacks-rounded',Stop:'stop-rounded',Sun:'light-mode-rounded',Terminal:'terminal-rounded',
  Trash:'delete-rounded',TreeStructure:'account-tree-rounded',UsersThree:'groups-rounded',Warning:'warning-rounded',X:'close-rounded',XCircle:'cancel-rounded',
};

const LOG = {
  postgres:'postgresql',postgresql:'postgresql',redis:'redis',kafka:'kafka',ubuntu:'ubuntu',debian:'debian',
  docker:'docker',kubernetes:'kubernetes',k8s:'kubernetes',nginx:'nginx',rocky:'rocky-linux',
};

const HEAD = "// GENERATED by scripts/gen-icons.cjs — do not edit by hand.\n// Regenerate after changing the icon set. Data inlined from @iconify-json.\n";

let icon = HEAD +
  "import { Icon as Iconify, type IconifyIcon } from '@iconify/react';\n" +
  "import type { SVGProps, ReactElement } from 'react';\n\n" +
  "/**\n * Central icon module — Google Material Symbols Rounded (Iconify data,\n" +
  " * inlined offline). Import UI icons ONLY from here. Swap vendor = regen.\n *\n" +
  " * Components accept SVG-like props (className, strokeWidth, data-*, aria-*)\n" +
  " * for drop-in Phosphor compatibility; props are forwarded to @iconify/react\n" +
  " * (strokeWidth is a no-op — Material Symbols are filled, not stroked).\n */\n" +
  "export type IconProps = SVGProps<SVGSVGElement>;\n" +
  "export type Icon = (props: IconProps) => ReactElement;\n\n" +
  "const mk = (data: IconifyIcon): Icon =>\n  function IconCmp(props: IconProps) {\n    return <Iconify icon={data} {...(props as Record<string, unknown>)} />;\n  };\n\n";
for (const [ph, mn] of Object.entries(MAT)) {
  icon += `export const ${ph} = mk(${JSON.stringify(getIcon(ms, mn))});\n`;
}
fs.writeFileSync('src/shared/ui/icon.tsx', icon);

let tech = HEAD +
  "import type { IconifyIcon } from '@iconify/react';\n\n" +
  "/** Цветные бренд-логотипы (Iconify logos:), инлайн офлайн. slug → данные. */\n" +
  "export const LOGO_DATA: Record<string, IconifyIcon> = {\n";
for (const [slug, ln] of Object.entries(LOG)) {
  tech += `  ${slug}: ${JSON.stringify(getIcon(lg, ln))},\n`;
}
tech += "};\n";
fs.writeFileSync('src/shared/ui/tech-icon-data.ts', tech);

console.log('icon.tsx:', Object.keys(MAT).length, 'icons · tech-icon-data.ts:', Object.keys(LOG).length, 'logos');
