import plexorConfig from '@plexor/eslint-config';

export default [
  ...plexorConfig,
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'src/routeTree.gen.ts',
      // kubb output — generated (see web/tooling/codegen/kubb.config.ts); the
      // hand-written msw.test.ts inside is exercised by vitest, not eslint.
      'src/shared/api/src/**',
      // MSW service worker — generated by `msw init public/`.
      'public/**',
    ],
  },
];
