# tools/ef-migrations-add.ps1 — wrapper around `dotnet ef migrations add`
# that post-processes generated files to mark them as source-generated.
# Windows counterpart of ef-migrations-add.sh.
#
# Why this exists:
#   Same as the bash version. `dotnet ef migrations add` produces
#   Designer + Snapshot files that are pure tool output. They should
#   carry [GeneratedCode] so Roslyn analyzers skip them, but EF
#   doesn't emit that attribute by default. This wrapper post-
#   processes the generated files.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File tools/ef-migrations-add.ps1 `
#       -ContextName ClusterDbContext `
#       -MigrationName ClusterRuntimeId_Add `
#       -Project src/modules/Plexor.Modules.Clusters/Plexor.Modules.Clusters.Infrastructure `
#       -StartupProject src/host/Plexor.Migrator `
#       -OutputDir Migrations/Clusters
#
#   # One-time adoption on a project whose migrations pre-date the wrapper:
#   powershell -ExecutionPolicy Bypass -File tools/ef-migrations-add.ps1 -MarkExisting
#
# The Up()/Down() file is left untouched.

[CmdletBinding(DefaultParameterSetName = 'New')]
param(
    [Parameter(Mandatory = $true, Position = 0, ParameterSetName = 'New')]
    [string]$ContextName,

    [Parameter(Mandatory = $true, Position = 1, ParameterSetName = 'New')]
    [string]$MigrationName,

    [Parameter(Mandatory = $true, ParameterSetName = 'New')]
    [string]$Project,

    [Parameter(Mandatory = $true, ParameterSetName = 'New')]
    [string]$StartupProject,

    [Parameter(Mandatory = $true, ParameterSetName = 'New')]
    [string]$OutputDir,

    [Parameter(ParameterSetName = 'MarkExisting')]
    [switch]$MarkExisting
)

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$Root = Resolve-Path (Join-Path $ScriptDir '..')
Push-Location $Root
try {
    # Shared: header block + per-file marker application.

    $header = @"
// <auto-generated />
// This file is regenerated by `dotnet ef migrations add`. Hand
// edits are clobbered on the next run. Use `bash tools/ef-migrations-add.sh`
// (or the PowerShell wrapper) to regenerate with [GeneratedCode] preserved.
#nullable disable

using System.CodeDom.Compiler;

[GeneratedCode("EntityFrameworkCore.Design", "10.0.0")]
"@

    function Mark-File {
        param([System.IO.FileInfo]$File)
        if (-not $File.Exists) {
            Write-Warning "[ef-migrations-add] $($File.FullName) does not exist, skipping."
            return
        }
        $content = Get-Content $File.FullName -Raw
        # Idempotent: skip if BOTH markers are present (comment for
        # dotnet format, attribute for Roslyn analyzers).
        if ($content -match '<auto-generated />' -and $content -match 'GeneratedCode') {
            Write-Host "[ef-migrations-add] $($File.FullName) already has both markers, skipping."
            return
        }
        $newContent = $header + "`r`n" + $content
        Set-Content -Path $File.FullName -Value $newContent -NoNewline
        Write-Host "[ef-migrations-add] Marked $($File.FullName) as source-generated."
    }

    # --MarkExisting: scan all migrations under src/.
    if ($MarkExisting) {
        Write-Host "[ef-migrations-add] Scanning for migrations under src/..."
        $targets = Get-ChildItem -Path 'src' -Recurse -File -ErrorAction SilentlyContinue `
            | Where-Object {
                ($_.FullName -like '*/Migrations/*') -and
                (($_.Name -like '*.Designer.cs') -or ($_.Name -like '*ModelSnapshot.cs'))
            }
        if (-not $targets) {
            Write-Host "[ef-migrations-add] No migrations found."
            return
        }
        foreach ($t in $targets) { Write-Host "  $($t.FullName)" }
        $answer = Read-Host "[ef-migrations-add] Apply marker to $($targets.Count) file(s)? [y/N]"
        if ($answer -notin @('y', 'Y')) {
            Write-Host "[ef-migrations-add] Aborted."
            return
        }
        foreach ($t in $targets) { Mark-File -File $t }
        return
    }

    # Default: create a new migration.
    Write-Host "[ef-migrations-add] Running 'dotnet ef migrations add $ContextName $MigrationName ...'"
    & dotnet ef migrations add $ContextName $MigrationName `
        --project $Project `
        --startup-project $StartupProject `
        --output-dir $OutputDir
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet ef migrations add exited $LASTEXITCODE"
    }

    if (-not (Test-Path $OutputDir)) {
        throw "Output directory '$OutputDir' does not exist after migration."
    }

    Write-Host "[ef-migrations-add] Post-processing generated files in $OutputDir..."
    $recent = Get-ChildItem -Path $OutputDir -File -Recurse `
        -Include '*.Designer.cs', '*ModelSnapshot.cs' `
        -ErrorAction SilentlyContinue `
        | Where-Object { $_.LastWriteTime -gt (Get-Date).AddMinutes(-5) }
    if (-not $recent) {
        Write-Warning "[ef-migrations-add] No recent Designer or Snapshot files found in $OutputDir."
        return
    }
    foreach ($r in $recent) { Mark-File -File $r }
    Write-Host "[ef-migrations-add] Done."
} finally {
    Pop-Location
}
