#!/usr/bin/env bash
# tools/ef-migrations-add.sh — wrapper around `dotnet ef migrations add`
# that post-processes generated files to mark them as source-generated.
#
# Why this exists:
#   `dotnet ef migrations add` produces three file types per migration:
#     1. <Timestamp>_<Name>.cs              — the Up()/Down() body
#     2. <Timestamp>_<Name>.Designer.cs     — EF scaffolding
#     3. <Name>DbContextModelSnapshot.cs    — model snapshot
#   The Designer + Snapshot files are pure EF tool output; any hand
#   edit is clobbered on the next `migrations add`. They're effectively
#   source-generated code, but `dotnet ef` doesn't emit the
#   [GeneratedCode] attribute that Roslyn analyzers key on.
#
# What this wrapper does:
#   1. Runs `dotnet ef migrations add <Name> --context ... --project ...
#      --startup-project ... -o Migrations/<Context>`
#   2. After generation, locates the new Designer + Snapshot files
#      and prepends [System.CodeDom.Compiler.GeneratedCode(...)] +
#      a `// <auto-generated />` header. The attribute is what
#      Roslyn analyzers key on to skip the file. The header is
#      what `dotnet format` and our VerifyFormatOnBuild target
#      recognize when deciding whether a file is human-authored.
#   3. Idempotent: re-running on a file that already carries the
#      marker is a no-op.
#
# Usage:
#   bash tools/ef-migrations-add.sh <ContextName> <MigrationName> \
#       --project src/modules/Plexor.Modules.<X>/.../Infrastructure \
#       --startup-project src/host/Plexor.Migrator \
#       -o Migrations/<Context>
#
#   # One-time adoption on a project whose migrations pre-date
#   # the wrapper:
#   bash tools/ef-migrations-add.sh --mark-existing
#
# The Up()/Down() file is left untouched — that's the human-edited
# surface (and the only one that gets regenerated cleanly).

set -euo pipefail

# ---------- shared: marker header + application ----------

GENERATED_HEADER='// <auto-generated />
// This file is regenerated by `dotnet ef migrations add`. Hand
// edits are clobbered on the next run. Use `bash tools/ef-migrations-add.sh`
// to regenerate with [GeneratedCode] preserved.
#nullable disable

using System.CodeDom.Compiler;

[GeneratedCode("EntityFrameworkCore.Design", "10.0.0")]
'

# Mark a single file. Idempotent: skips files that already
# carry the <auto-generated /> marker.
mark_file() {
    local f="$1"
    if [ ! -f "$f" ]; then
        echo "[ef-migrations-add] WARNING: $f does not exist, skipping."
        return 0
    fi
    # Idempotent. The EF tool (EF Core 9+) emits `// <auto-generated />`
    # by default, which is enough for `dotnet format` to skip the file.
    # Our wrapper adds the [GeneratedCode] attribute Roslyn analyzers
    # key on; if BOTH markers are already present (idempotent re-run),
    # skip. Otherwise add the header that carries both.
    if grep -q '<auto-generated />' "$f" && grep -q 'GeneratedCode' "$f"; then
        echo "[ef-migrations-add] $f already has both markers, skipping."
        return 0
    fi
    local tmp
    tmp=$(mktemp)
    {
        printf '%s' "$GENERATED_HEADER"
        cat "$f"
    } > "$tmp"
    mv "$tmp" "$f"
    echo "[ef-migrations-add] Marked $f as source-generated."
}

# Apply the marker to every *.Designer.cs and *ModelSnapshot.cs
# file modified in the last 5 minutes (EF tool runs in sub-second;
# 5 minutes is generous enough to catch the just-created files
# without false positives on unrelated recent edits).
mark_recent() {
    local dir="$1"
    if [ ! -d "$dir" ]; then
        echo "[ef-migrations-add] WARNING: directory $dir does not exist."
        return 0
    fi
    local files
    mapfile -t files < <(find "$dir" \( -name '*.Designer.cs' -o -name '*ModelSnapshot.cs' \) -mmin -5)
    if [ "${#files[@]}" -eq 0 ]; then
        echo "[ef-migrations-add] No recent Designer or Snapshot files found in $dir."
        return 0
    fi
    local f
    for f in "${files[@]}"; do
        mark_file "$f"
    done
}

# ---------- modes ----------

# --mark-existing mode: walk every Migrations directory under src/
# and offer to apply the marker. Idempotent.
if [ "${1:-}" = "--mark-existing" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
    cd "$ROOT"

    echo "[ef-migrations-add] Scanning for migrations under src/..."
    mapfile -t TARGETS < <(find src -path '*/Migrations/*' \( -name '*.Designer.cs' -o -name '*ModelSnapshot.cs' \) 2>/dev/null)
    if [ "${#TARGETS[@]}" -eq 0 ]; then
        echo "[ef-migrations-add] No migrations found."
        exit 0
    fi
    printf 'Files to mark:\n'
    printf '  %s\n' "${TARGETS[@]}"
    echo "[ef-migrations-add] Apply marker to ${#TARGETS[@]} file(s)? [y/N]"
    read -r REPLY
    if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
        echo "[ef-migrations-add] Aborted."
        exit 0
    fi
    for f in "${TARGETS[@]}"; do
        mark_file "$f"
    done
    exit 0
fi

# Default mode: create a new migration.
if [ $# -lt 2 ]; then
    echo "Usage: $0 <ContextName> <MigrationName> [--project <path>] [--startup-project <path>] -o <output-dir>" >&2
    echo "       $0 --mark-existing    # apply marker to all existing migrations" >&2
    exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

echo "[ef-migrations-add] Running 'dotnet ef migrations add $1 $2 ...'"
dotnet ef migrations add "$@"

# Find the -o / --output-dir argument so we know where to look
# for the just-generated files.
OUTPUT_DIR=""
prev=""
for arg in "$@"; do
    if [ "$prev" = "-o" ] || [ "$prev" = "--output-dir" ]; then
        OUTPUT_DIR="$arg"
        break
    fi
    prev="$arg"
done

if [ -z "$OUTPUT_DIR" ] || [ ! -d "$OUTPUT_DIR" ]; then
    echo "[ef-migrations-add] ERROR: could not resolve output directory from -o." >&2
    echo "[ef-migrations-add] Pass -o Migrations/<Context> explicitly." >&2
    exit 3
fi

echo "[ef-migrations-add] Post-processing generated files in $OUTPUT_DIR..."
mark_recent "$OUTPUT_DIR"
echo "[ef-migrations-add] Done."
