/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { vSphereCloneRequestBodySchema } from "./vSphereCloneRequestBodySchema.ts";
import { vSphereCloneResponseSchema } from "./vSphereCloneResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Clone succeeded.
 */
export const cloneVSphereTemplate200Schema = z.lazy(() => vSphereCloneResponseSchema).describe("Body for the 200 response on POST /api/v1/vsphere/clone.")

/**
 * @description RFC 7807 error.
 */
export const cloneVSphereTemplate404Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const cloneVSphereTemplate502Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const cloneVSphereTemplate503Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const cloneVSphereTemplate504Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const cloneVSphereTemplateErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const cloneVSphereTemplateMutationRequestSchema = z.lazy(() => vSphereCloneRequestBodySchema).describe("Body for POST /api/v1/vsphere/clone.")

export const cloneVSphereTemplateMutationResponseSchema = z.lazy(() => cloneVSphereTemplate200Schema)