/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { z } from "zod";

 /**
 * @description Payload from the create-VM wizard.
 */
export const createVmRequestSchema = z.object({ "name": z.string().min(1), "project": z.string(), "vpcId": z.string().uuid().nullable().nullish(), "subnetId": z.string().uuid(), "machineType": z.string(), "vcpu": z.number().int().min(1).optional(), "ramGb": z.number().int().min(1).optional(), "diskGb": z.number().int().min(10), "image": z.string(), "diskEncrypted": z.boolean().default(true), "securityGroups": z.array(z.string()).optional(), "label": z.string().nullable().nullish(), "description": z.string().nullable().nullish(), "tags": z.array(z.string()).optional() }).describe("Payload from the create-VM wizard.");