/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload from the create-VM wizard.
 */
export const createVmRequestSchema = z.object({
    "name": z.string().min(1),
"project": z.string(),
"vpcId": z.uuid().nullish(),
"subnetId": z.uuid(),
"machineType": z.string(),
"vcpu": z.optional(z.int().min(1)),
"ramGb": z.optional(z.int().min(1)),
"diskGb": z.int().min(10),
"image": z.string(),
"diskEncrypted": z.optional(z.boolean().default(true)),
"securityGroups": z.optional(z.array(z.string())),
"label": z.string().nullish(),
"description": z.string().nullish(),
"tags": z.optional(z.array(z.string()))
    }).describe("Payload from the create-VM wizard.")