/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

export const deleteVmPathParamsSchema = z.object({
    "vmId": z.uuid()
    })

/**
 * @description Deleted.
 */
export const deleteVm204Schema = z.any()

/**
 * @description RFC 7807 error.
 */
export const deleteVm404Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const deleteVmErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const deleteVmMutationResponseSchema = z.lazy(() => deleteVm204Schema)