/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

export const deleteBrandingOrgPathParamsSchema = z.object({
    "orgId": z.uuid()
    })

/**
 * @description Reset (or already absent).
 */
export const deleteBrandingOrg204Schema = z.any()

/**
 * @description RFC 7807 error.
 */
export const deleteBrandingOrg404Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const deleteBrandingOrgErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const deleteBrandingOrgMutationResponseSchema = z.lazy(() => deleteBrandingOrg204Schema)