/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod";

 export const deleteVmPathParamsSchema = z.object({ "vmId": z.string().uuid() });

 /**
 * @description Deleted.
 */
export const deleteVm204Schema = z.any();

 /**
 * @description RFC 7807 error.
 */
export const deleteVm404Schema = z.lazy(() => problemDetailsSchema);

 /**
 * @description RFC 7807 error.
 */
export const deleteVmErrorSchema = z.lazy(() => problemDetailsSchema);

 export const deleteVmMutationResponseSchema = z.lazy(() => deleteVm204Schema);