/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Effective rollup of a definition for a scope (what ceiling applies here, after merging).
 */
export const effectiveQuotaEntrySchema = z.object({
    "definitionId": z.uuid(),
"metric": z.string(),
"scope": z.enum(["org", "team", "folder"]),
"scopeId": z.uuid(),
"effectiveCeiling": z.int().min(0),
"appliedAssignmentIds": z.array(z.uuid()).describe("The chain of assignment ids that contributed to the effective ceiling (folder → team → org → default).")
    }).describe("Effective rollup of a definition for a scope (what ceiling applies here, after merging).")