/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { auditQueryResponseSchema } from "./auditQueryResponseSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

export const getAuditQueryParamsSchema = z.object({
    "action": z.optional(z.string().describe("Filter to a single action wire name.")),
"orgId": z.optional(z.uuid().describe("Override the caller's tenant scope. Restricted to platform admins.")),
"actorUserId": z.optional(z.uuid().describe("Filter to a single actor (user or API-key owner).")),
"since": z.optional(z.iso.datetime().describe("ISO timestamp — only events fired at-or-after this boundary.")),
"before": z.optional(z.iso.datetime().describe("ISO timestamp — only events fired strictly before this boundary (offset cursor).")),
"limit": z.coerce.number().int().min(1).max(500).default(100)
    })

/**
 * @description Audit rows.
 */
export const getAudit200Schema = z.array(z.lazy(() => auditQueryResponseSchema).describe("One row in the audit timeline."))

/**
 * @description RFC 7807 error.
 */
export const getAuditErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const getAuditQueryResponseSchema = z.lazy(() => getAudit200Schema)