/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { brandingBootConfigSchema } from "./brandingBootConfigSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

/**
 * @description Resolved branding for the caller.
 */
export const getBrandingBoot200Schema = z.lazy(() => brandingBootConfigSchema).describe("Resolved branding for the caller — merges global row + per-org override. Written server-side into window.__PLEXOR_CONFIG__ before first paint.")

/**
 * @description RFC 7807 error.
 */
export const getBrandingBootErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const getBrandingBootQueryResponseSchema = z.lazy(() => getBrandingBoot200Schema)