/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { globalThemeConfigResponseSchema } from "./globalThemeConfigResponseSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

/**
 * @description Global branding configuration.
 */
export const getBrandingGlobal200Schema = z.lazy(() => globalThemeConfigResponseSchema).describe("Operator-global branding row (Plexor.Modules.Branding).")

/**
 * @description RFC 7807 error.
 */
export const getBrandingGlobalErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const getBrandingGlobalQueryResponseSchema = z.lazy(() => getBrandingGlobal200Schema)