/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { z } from "zod";

 /**
 * @description OK
 */
export const getHealth200Schema = z.any();

 export const getHealthQueryResponseSchema = z.lazy(() => getHealth200Schema);