/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

export const getOidcAuthorizeQueryParamsSchema = z.object({
    "org": z.uuid().describe("Tenant scope for the resulting session."),
"redirect": z.optional(z.string().describe("Post-login redirect target (path only, must be on this origin)."))
    })

/**
 * @description Redirect to the IdP\'s authorization endpoint.
 */
export const getOidcAuthorize302Schema = z.any()

/**
 * @description RFC 7807 error.
 */
export const getOidcAuthorizeErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const getOidcAuthorizeQueryResponseSchema = z.any()