/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { orgAuthProviderConfigResponseSchema } from "./orgAuthProviderConfigResponseSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

export const getOrgAuthProviderPathParamsSchema = z.object({
    "orgId": z.uuid()
    })

/**
 * @description The org\'s auth-provider config.
 */
export const getOrgAuthProvider200Schema = z.lazy(() => orgAuthProviderConfigResponseSchema).describe("The org's identity-provider configuration. Sensitive fields (client secrets, bind passwords) are write-only; the GET response carries a sentinel (`***`) instead of the real value.")

/**
 * @description RFC 7807 error.
 */
export const getOrgAuthProvider404Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const getOrgAuthProviderErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const getOrgAuthProviderQueryResponseSchema = z.lazy(() => getOrgAuthProvider200Schema)