/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

export const getOidcCallbackQueryParamsSchema = z.object({
    "code": z.string(),
"state": z.string()
    })

/**
 * @description Redirect to the post-login target with a session cookie set.
 */
export const getOidcCallback302Schema = z.any()

/**
 * @description RFC 7807 error.
 */
export const getOidcCallbackErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const getOidcCallbackQueryResponseSchema = z.any()