/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { vSphereInventoryResponseSchema } from "./vSphereInventoryResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description The latest cached inventory snapshot.
 */
export const getVSphereInventory200Schema = z.lazy(() => vSphereInventoryResponseSchema).describe("Top-level response for GET /api/v1/vsphere/inventory. Bundles the snapshot header + the per-resource row lists so the caller can render the inventory in a single round trip.")

/**
 * @description RFC 7807 error.
 */
export const getVSphereInventory503Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const getVSphereInventoryErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const getVSphereInventoryQueryResponseSchema = z.lazy(() => getVSphereInventory200Schema)