/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { nodeJoinRequestSchema } from "./nodeJoinRequestSchema.ts";
import { nodeJoinResponseSchema } from "./nodeJoinResponseSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

/**
 * @description Registered. Body carries the NodeId and URL.
 */
export const nodeJoin201Schema = z.lazy(() => nodeJoinResponseSchema).describe("Reply to a join. The agent stores both fields and uses controlPlaneUrl for further calls.")

/**
 * @description RFC 7807 error.
 */
export const nodeJoin400Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const nodeJoinMutationRequestSchema = z.lazy(() => nodeJoinRequestSchema).describe("First message the agent sends. The join token is not yet verified.")

export const nodeJoinMutationResponseSchema = z.lazy(() => nodeJoin201Schema)