/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { nodeCommandEnvelopeSchema } from "./nodeCommandEnvelopeSchema.ts";
import { z } from "zod/v4";

/**
 * @description Long-poll output. Empty array + current cursor means \'no new commands\'.
 */
export const nodeCommandPollResponseSchema = z.object({
    get "commands"(){
                return z.array(nodeCommandEnvelopeSchema.describe("One command targeted at a node, dequeued by /commands/poll."))
              },
"nextCursor": z.int()
    }).describe("Long-poll output. Empty array + current cursor means 'no new commands'.")