/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { nodeHardwareSchema } from "./nodeHardwareSchema.ts";
import { z } from "zod/v4";

/**
 * @description Periodic liveness ping from the agent.
 */
export const nodeHeartbeatRequestSchema = z.object({
    "nodeId": z.uuid(),
"sentAt": z.iso.datetime(),
get "hardware"(){
                return nodeHardwareSchema.describe("Hardware snapshot reported by the agent on join and on every heartbeat.")
              },
"runningVmCount": z.int().min(0)
    }).describe("Periodic liveness ping from the agent.")