/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Result of POST /iam/orgs/{orgId}/auth-provider/test. The test never persists side effects.
 */
export const orgAuthProviderTestResultSchema = z.object({
    "ok": z.boolean(),
"message": z.string().describe("Human-readable diagnostic. For OIDC: the discovery + token-exchange result. For LDAP: the bind result."),
"latencyMs": z.int().min(0).describe("Round-trip latency in milliseconds. Null when the test failed before a request was issued.").nullish(),
"details": z.object({
    
    }).catchall(z.any()).describe("Provider-specific diagnostics (discovery URL, JWKS URL, bind subject, ...). Free-form.").nullish()
    }).describe("Result of POST /iam/orgs/{orgId}/auth-provider/test. The test never persists side effects.")