/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Per-org override row. Null fields inherit the operator-global default.
 */
export const orgBrandingConfigResponseSchema = z.object({
    "orgId": z.uuid(),
"presetId": z.nullable(z.string().describe("Per-org theme preset override. Null = inherit.")),
"customAccent": z.nullable(z.string().describe("OKLCH color. Null = inherit.")),
"brandName": z.nullable(z.string().describe("Per-org brand name. Null = inherit.")),
"brandLogoUrl": z.nullable(z.url()),
"brandFaviconUrl": z.nullable(z.url()),
"updatedAt": z.iso.datetime()
    }).describe("Per-org override row. Null fields inherit the operator-global default.")