/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

/**
 * @description Signed out.
 */
export const postOidcLogout204Schema = z.any()

/**
 * @description RFC 7807 error.
 */
export const postOidcLogoutErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const postOidcLogoutMutationResponseSchema = z.lazy(() => postOidcLogout204Schema)