/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Local-credentials sign-in payload (sigill module). The FE trims + lowercases the email before sending so the backend can compare against the canonical address.
 */
export const postAuthLoginRequestSchema = z.object({
    "email": z.email().max(254).describe("Work email. The local-part is case-insensitive; the backend normalises to lowercase on persist."),
"password": z.string().min(1).max(128).describe("Plaintext password. TLS-only on the wire; never logged.")
    }).describe("Local-credentials sign-in payload (sigill module). The FE trims + lowercases the email before sending so the backend can compare against the canonical address.")