/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authLoginResponseSchema } from "./authLoginResponseSchema.ts";
import { postAuthLoginRequestSchema } from "./postAuthLoginRequestSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod/v4";

/**
 * @description Signed in. The `expiresIn` value is the access-token lifetime in seconds; the FE uses it to compute the absolute `expiresAt` (now + expiresIn * 1000).\n
 */
export const postAuthLogin200Schema = z.lazy(() => authLoginResponseSchema).describe("Successful sign-in. Returns the bearer access token (RS256 JWT the console stores as `Authorization: Bearer`), the opaque refresh token, the access-token lifetime in seconds, and the authenticated user record. The FE computes `expiresAt = Date.now() + expiresIn * 1000` and persists the triple to localStorage.\n")

/**
 * @description RFC 7807 error.
 */
export const postAuthLogin401Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const postAuthLogin422Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const postAuthLoginErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const postAuthLoginMutationRequestSchema = z.lazy(() => postAuthLoginRequestSchema).describe("Local-credentials sign-in payload (sigill module). The FE trims + lowercases the email before sending so the backend can compare against the canonical address.")

export const postAuthLoginMutationResponseSchema = z.lazy(() => postAuthLogin200Schema)