/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description The authenticated user record — used to seed the FE user cache after sign-in.
 */
export const postAuthLoginUserSchema = z.object({
    "id": z.uuid().describe("Stable user id (sigill.users.id)."),
"email": z.email().max(254),
"displayName": z.string().max(200),
"roles": z.array(z.string()).describe("Org-scoped role names (e.g. `admin`, `editor`, `viewer`). Empty in MVP; expanded in Phase 2 with team-scoped roles.")
    }).describe("The authenticated user record — used to seed the FE user cache after sign-in.")