/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { z } from "zod";

 /**
 * @description RFC 7807 problem details.
 */
export const problemDetailsSchema = z.object({ "type": z.string().optional(), "title": z.string().optional(), "status": z.number().int().optional(), "detail": z.string().optional(), "instance": z.string().nullable().nullish() }).describe("RFC 7807 problem details.");