/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description RFC 7807 problem details.
 */
export const problemDetailsSchema = z.object({
    "type": z.optional(z.string()),
"title": z.optional(z.string()),
"status": z.optional(z.int()),
"detail": z.optional(z.string()),
"instance": z.string().nullish()
    }).describe("RFC 7807 problem details.")