/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { z } from "zod";

 export const problemSchema = z.lazy(() => problemDetailsSchema);