/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { createVmRequestSchema } from "./createVmRequestSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { vmDetailSchema } from "./vmDetailSchema.ts";
import { z } from "zod";

 /**
 * @description VM accepted for provisioning.
 */
export const provisionVm201Schema = z.lazy(() => vmDetailSchema);

 /**
 * @description RFC 7807 error.
 */
export const provisionVm422Schema = z.lazy(() => problemDetailsSchema);

 /**
 * @description RFC 7807 error.
 */
export const provisionVmErrorSchema = z.lazy(() => problemDetailsSchema);

 export const provisionVmMutationRequestSchema = z.lazy(() => createVmRequestSchema);

 export const provisionVmMutationResponseSchema = z.lazy(() => provisionVm201Schema);