/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description One (definition, scope, scopeId, ceiling) tuple.
 */
export const quotaAssignmentSummarySchema = z.object({
    "id": z.uuid(),
"definitionId": z.uuid(),
"scope": z.enum(["org", "team", "folder"]),
"scopeId": z.uuid(),
"ceiling": z.int().min(0),
"updatedAt": z.iso.datetime()
    }).describe("One (definition, scope, scopeId, ceiling) tuple.")