/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { vmDetailSchema } from "./vmDetailSchema.ts";
import { z } from "zod";

 export const startVmPathParamsSchema = z.object({ "vmId": z.string().uuid() });

 /**
 * @description Start requested.
 */
export const startVm200Schema = z.lazy(() => vmDetailSchema);

 /**
 * @description RFC 7807 error.
 */
export const startVmErrorSchema = z.lazy(() => problemDetailsSchema);

 export const startVmMutationResponseSchema = z.lazy(() => startVm200Schema);