/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { orgAuthProviderTestResultSchema } from "./orgAuthProviderTestResultSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { upsertOrgAuthProviderRequestSchema } from "./upsertOrgAuthProviderRequestSchema.ts";
import { z } from "zod/v4";

export const testOrgAuthProviderPathParamsSchema = z.object({
    "orgId": z.uuid()
    })

/**
 * @description Test result.
 */
export const testOrgAuthProvider200Schema = z.lazy(() => orgAuthProviderTestResultSchema).describe("Result of POST /iam/orgs/{orgId}/auth-provider/test. The test never persists side effects.")

/**
 * @description RFC 7807 error.
 */
export const testOrgAuthProvider404Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const testOrgAuthProviderErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const testOrgAuthProviderMutationRequestSchema = z.lazy(() => upsertOrgAuthProviderRequestSchema).describe("Wire shape for PUT /iam/orgs/{orgId}/auth-provider. Omit a sensitive field to keep the stored value unchanged (write-only secrets).")

export const testOrgAuthProviderMutationResponseSchema = z.lazy(() => testOrgAuthProvider200Schema)