/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Active marketplace theme + the signature the FE boot script re-verifies.
 */
export const themeInstallationResponseSchema = z.object({
    "orgId": z.uuid(),
"themeId": z.string().max(64),
"name": z.string().max(128),
"version": z.string().max(64),
"author": z.string().max(128),
"manifestSignature": z.string().min(64).max(64).regex(/^[0-9a-fA-F]{64}$/).describe("Hex-encoded HMAC-SHA256 persisted on the row."),
"activatedAt": z.iso.datetime(),
"activatedBy": z.uuid()
    }).describe("Active marketplace theme + the signature the FE boot script re-verifies.")