/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { orgAuthProviderConfigResponseSchema } from "./orgAuthProviderConfigResponseSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { upsertOrgAuthProviderRequestSchema } from "./upsertOrgAuthProviderRequestSchema.ts";
import { z } from "zod/v4";

export const updateOrgAuthProviderPathParamsSchema = z.object({
    "orgId": z.uuid()
    })

/**
 * @description The upserted config (secrets returned as sentinels).
 */
export const updateOrgAuthProvider200Schema = z.lazy(() => orgAuthProviderConfigResponseSchema).describe("The org's identity-provider configuration. Sensitive fields (client secrets, bind passwords) are write-only; the GET response carries a sentinel (`***`) instead of the real value.")

/**
 * @description RFC 7807 error.
 */
export const updateOrgAuthProvider400Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const updateOrgAuthProvider404Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const updateOrgAuthProviderErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const updateOrgAuthProviderMutationRequestSchema = z.lazy(() => upsertOrgAuthProviderRequestSchema).describe("Wire shape for PUT /iam/orgs/{orgId}/auth-provider. Omit a sensitive field to keep the stored value unchanged (write-only secrets).")

export const updateOrgAuthProviderMutationResponseSchema = z.lazy(() => updateOrgAuthProvider200Schema)