/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { globalThemeConfigResponseSchema } from "./globalThemeConfigResponseSchema.ts";
import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { upsertGlobalThemeConfigRequestSchema } from "./upsertGlobalThemeConfigRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description The upserted global row.
 */
export const updateBrandingGlobal200Schema = z.lazy(() => globalThemeConfigResponseSchema).describe("Operator-global branding row (Plexor.Modules.Branding).")

/**
 * @description RFC 7807 error.
 */
export const updateBrandingGlobal400Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const updateBrandingGlobalErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const updateBrandingGlobalMutationRequestSchema = z.lazy(() => upsertGlobalThemeConfigRequestSchema).describe("Wire shape for PUT /branding/global.")

export const updateBrandingGlobalMutationResponseSchema = z.lazy(() => updateBrandingGlobal200Schema)