/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { themeInstallationResponseSchema } from "./themeInstallationResponseSchema.ts";
import { upsertThemeInstallationRequestSchema } from "./upsertThemeInstallationRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description The upserted installation row.
 */
export const updateBrandingTheme200Schema = z.lazy(() => themeInstallationResponseSchema).describe("Active marketplace theme + the signature the FE boot script re-verifies.")

/**
 * @description RFC 7807 error.
 */
export const updateBrandingTheme400Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const updateBrandingTheme403Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const updateBrandingTheme404Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const updateBrandingThemeErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const updateBrandingThemeMutationRequestSchema = z.lazy(() => upsertThemeInstallationRequestSchema).describe("Wire shape for PUT /branding/theme. The host looks the theme up in its bundled CommunityThemeRegistry and signs the canonical manifest with the purpose-bound IThemeManifestVerifier before persisting.\n")

export const updateBrandingThemeMutationResponseSchema = z.lazy(() => updateBrandingTheme200Schema)