/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Wire shape for PUT /branding/org/{orgId}. Null fields mean \"inherit the operator global default\".
 */
export const upsertOrgBrandingRequestSchema = z.object({
    "presetId": z.string().nullish(),
"customAccent": z.string().nullish(),
"brandName": z.string().max(128).nullish(),
"brandLogoUrl": z.url().nullish(),
"brandFaviconUrl": z.url().nullish()
    }).describe("Wire shape for PUT /branding/org/{orgId}. Null fields mean \"inherit the operator global default\".")