/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Wire shape for PUT /branding/theme. The host looks the theme up in its bundled CommunityThemeRegistry and signs the canonical manifest with the purpose-bound IThemeManifestVerifier before persisting.\n
 */
export const upsertThemeInstallationRequestSchema = z.object({
    "themeId": z.string().max(64).describe("Marketplace id from the host-side CommunityThemeRegistry.")
    }).describe("Wire shape for PUT /branding/theme. The host looks the theme up in its bundled CommunityThemeRegistry and signs the canonical manifest with the purpose-bound IThemeManifestVerifier before persisting.\n")