/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Wire shape for PUT /branding/global.
 */
export const upsertGlobalThemeConfigRequestSchema = z.object({
    "brandName": z.string().min(1).max(128),
"brandLogoUrl": z.url().nullish(),
"brandFaviconUrl": z.url().nullish(),
"defaultPresetId": z.string().min(1),
"customAccent": z.string().describe("OKLCH color string.").nullish()
    }).describe("Wire shape for PUT /branding/global.")