/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema.ts";
import { quotaAssignmentSummarySchema } from "./quotaAssignmentSummarySchema.ts";
import { upsertQuotaAssignmentRequestSchema } from "./upsertQuotaAssignmentRequestSchema.ts";
import { z } from "zod/v4";

export const upsertQuotaAssignmentQueryParamsSchema = z.object({
    "scope": z.optional(z.enum(["org", "team", "folder"]).describe("Filter to a single scope tier ('org', 'team', or 'folder').")),
"id": z.optional(z.uuid().describe("Filter to the resource with this id (orgId/teamId/folderId depending on scope)."))
    }).optional()

/**
 * @description The upserted assignment.
 */
export const upsertQuotaAssignment200Schema = z.lazy(() => quotaAssignmentSummarySchema).describe("One (definition, scope, scopeId, ceiling) tuple.")

/**
 * @description RFC 7807 error.
 */
export const upsertQuotaAssignment400Schema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

/**
 * @description RFC 7807 error.
 */
export const upsertQuotaAssignmentErrorSchema = z.lazy(() => problemDetailsSchema).describe("RFC 7807 problem details.")

export const upsertQuotaAssignmentMutationRequestSchema = z.lazy(() => upsertQuotaAssignmentRequestSchema).describe("Wire shape for PUT /quotas/assignments. The (definitionId, scope, scopeId) tuple is the natural key.")

export const upsertQuotaAssignmentMutationResponseSchema = z.lazy(() => upsertQuotaAssignment200Schema)