/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Wire shape for PUT /iam/orgs/{orgId}/auth-provider. Omit a sensitive field to keep the stored value unchanged (write-only secrets).
 */
export const upsertOrgAuthProviderRequestSchema = z.object({
    "provider": z.enum(["local", "oidc", "ldap"]),
"oidc": z.object({
    "issuer": z.optional(z.url()),
"clientId": z.optional(z.string().min(1)),
"clientSecret": z.string().describe("Write-only. Omit (or send the sentinel `***`) to keep the existing value.").nullish(),
"scopes": z.optional(z.array(z.string())),
"redirectUri": z.optional(z.url()),
"claimMappings": z.optional(z.object({
    
    }).catchall(z.string()))
    }).nullish(),
"ldap": z.object({
    "server": z.optional(z.string()),
"baseDn": z.optional(z.string()),
"bindDn": z.optional(z.string()),
"bindPassword": z.string().describe("Write-only. Omit (or send the sentinel `***`) to keep the existing value.").nullish(),
"userFilter": z.optional(z.string()),
"roleAttribute": z.string().nullish()
    }).nullish()
    }).describe("Wire shape for PUT /iam/orgs/{orgId}/auth-provider. Omit a sensitive field to keep the stored value unchanged (write-only secrets).")