/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { vmSchema } from "./vmSchema.ts";
import { z } from "zod";

 export const vmListSchema = z.object({ "items": z.array(z.lazy(() => vmSchema)), "page": z.number().int(), "pageSize": z.number().int(), "total": z.number().int() });