/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { vmStatusSchema } from "./vmStatusSchema.ts";
import { z } from "zod/v4";

/**
 * @description A virtual machine as shown in the list.
 */
export const vmSchema = z.object({
    "id": z.uuid(),
"name": z.string(),
get "status"(){
                return vmStatusSchema.describe("Lifecycle state of a VM.")
              },
"internalIp": z.string(),
"zone": z.string(),
"machineType": z.string(),
"vcpu": z.int(),
"ramGb": z.int(),
"diskGb": z.int(),
"tags": z.optional(z.array(z.string())),
"createdAt": z.iso.datetime()
    }).describe("A virtual machine as shown in the list.")