/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { vmStatusSchema } from "./vmStatusSchema.ts";
import { z } from "zod";

 /**
 * @description A virtual machine as shown in the list.
 */
export const vmSchema = z.object({ "id": z.string().uuid(), "name": z.string(), "status": z.lazy(() => vmStatusSchema), "internalIp": z.string(), "zone": z.string(), "machineType": z.string(), "vcpu": z.number().int(), "ramGb": z.number().int(), "diskGb": z.number().int(), "tags": z.array(z.string()).optional(), "createdAt": z.string().datetime() }).describe("A virtual machine as shown in the list.");