/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

 import { z } from "zod";

 /**
 * @description Lifecycle state of a VM.
 */
export const vmStatusSchema = z.enum(["provisioning", "running", "stopped", "error", "idle"]).describe("Lifecycle state of a VM.");