/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Body for the 200 response on POST /api/v1/vsphere/clone.
 */
export const vSphereCloneResponseSchema = z.object({
    "runId": z.uuid().describe("Audit-trail row id (UUID v7). Null when the service omits it.").nullish(),
"vmMoref": z.string().describe("vCenter mo-ref for the new VM."),
"status": z.enum(["SUCCESS"])
    }).describe("Body for the 200 response on POST /api/v1/vsphere/clone.")