/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Body for the 202 response on POST /api/v1/vsphere/inventory/refresh.
 */
export const vSphereInventoryRefreshResponseSchema = z.object({
    "snapshotId": z.uuid().describe("The newly written snapshot id."),
"status": z.enum(["SUCCESS"])
    }).describe("Body for the 202 response on POST /api/v1/vsphere/inventory/refresh.")