/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description ESXi host row in the vSphere inventory snapshot.
 */
export const vSphereInventoryHostRowSchema = z.object({
    "moref": z.string().describe("Host mo-ref."),
"name": z.string(),
"clusterMoref": z.string().describe("Parent cluster mo-ref."),
"connectionState": z.enum(["CONNECTED", "DISCONNECTED", "NOT_RESPONDING"]),
"cpuCores": z.int().min(0).describe("Total logical CPU cores (sockets × cores)."),
"memoryMib": z.int().min(0).describe("Total physical memory in MiB.")
    }).describe("ESXi host row in the vSphere inventory snapshot.")