/* eslint-disable */
// @ts-nocheck
// Generated by kubb — do not edit. Run `bun run generate` from web/tooling/codegen.

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { vSphereInventoryClusterRowSchema } from "./vSphereInventoryClusterRowSchema.ts";
import { vSphereInventoryHostRowSchema } from "./vSphereInventoryHostRowSchema.ts";
import { vSphereInventorySnapshotHeaderSchema } from "./vSphereInventorySnapshotHeaderSchema.ts";
import { vSphereInventoryVirtualMachineRowSchema } from "./vSphereInventoryVirtualMachineRowSchema.ts";
import { z } from "zod/v4";

/**
 * @description Top-level response for GET /api/v1/vsphere/inventory. Bundles the snapshot header + the per-resource row lists so the caller can render the inventory in a single round trip.
 */
export const vSphereInventoryResponseSchema = z.object({
    get "snapshot"(){
                return vSphereInventorySnapshotHeaderSchema.describe("Snapshot header for GET /api/v1/vsphere/inventory. Carries the snapshot id + per-resource row counts + the refresh timestamp.")
              },
get "clusters"(){
                return z.array(vSphereInventoryClusterRowSchema.describe("Cluster row in the vSphere inventory snapshot."))
              },
get "hosts"(){
                return z.array(vSphereInventoryHostRowSchema.describe("ESXi host row in the vSphere inventory snapshot."))
              },
get "virtualMachines"(){
                return z.array(vSphereInventoryVirtualMachineRowSchema.describe("Virtual machine row in the vSphere inventory snapshot (non-template only)."))
              }
    }).describe("Top-level response for GET /api/v1/vsphere/inventory. Bundles the snapshot header + the per-resource row lists so the caller can render the inventory in a single round trip.")